stages:
  - publish

variables:
  APP_NAME: bid-engine
  APP_TYPE: backend

publish-test:
  stage: publish
  image: docker:24.0.2
  tags:
    - saas
  variables:
    ENV: test
    TAG_COMMIT: $HARBOR_HOST/$APP_TYPE/$APP_NAME-$ENV:latest
    TAG_LATEST: $HARBOR_HOST/$APP_TYPE/$APP_NAME-$ENV:$CI_COMMIT_SHORT_SHA
  script:
    - mv conf/conf-container.yml conf/conf-container.yml
    - docker login -u $HARBOR_USER -p $HARBOR_TOKEN $HARBOR_HOST
    - docker build -t $TAG_COMMIT -t $TAG_LATEST -f Dockerfile .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  when: manual