// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newAgentSessionMap(db *gorm.DB, opts ...gen.DOOption) agentSessionMap {
	_agentSessionMap := agentSessionMap{}

	_agentSessionMap.agentSessionMapDo.UseDB(db, opts...)
	_agentSessionMap.agentSessionMapDo.UseModel(&model.AgentSessionMap{})

	tableName := _agentSessionMap.agentSessionMapDo.TableName()
	_agentSessionMap.ALL = field.NewAsterisk(tableName)
	_agentSessionMap.ID = field.NewInt64(tableName, "id")
	_agentSessionMap.OurConversationID = field.NewString(tableName, "our_conversation_id")
	_agentSessionMap.AgentConversationID = field.NewString(tableName, "agent_conversation_id")
	_agentSessionMap.AgentID = field.NewString(tableName, "agent_id")
	_agentSessionMap.CreatedAt = field.NewTime(tableName, "created_at")
	_agentSessionMap.UpdatedAt = field.NewTime(tableName, "updated_at")

	_agentSessionMap.fillFieldMap()

	return _agentSessionMap
}

type agentSessionMap struct {
	agentSessionMapDo agentSessionMapDo

	ALL                 field.Asterisk
	ID                  field.Int64 // 自增主键
	OurConversationID   field.String
	AgentConversationID field.String
	AgentID             field.String
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (a agentSessionMap) Table(newTableName string) *agentSessionMap {
	a.agentSessionMapDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentSessionMap) As(alias string) *agentSessionMap {
	a.agentSessionMapDo.DO = *(a.agentSessionMapDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentSessionMap) updateTableName(table string) *agentSessionMap {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.OurConversationID = field.NewString(table, "our_conversation_id")
	a.AgentConversationID = field.NewString(table, "agent_conversation_id")
	a.AgentID = field.NewString(table, "agent_id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *agentSessionMap) WithContext(ctx context.Context) *agentSessionMapDo {
	return a.agentSessionMapDo.WithContext(ctx)
}

func (a agentSessionMap) TableName() string { return a.agentSessionMapDo.TableName() }

func (a agentSessionMap) Alias() string { return a.agentSessionMapDo.Alias() }

func (a *agentSessionMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentSessionMap) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["our_conversation_id"] = a.OurConversationID
	a.fieldMap["agent_conversation_id"] = a.AgentConversationID
	a.fieldMap["agent_id"] = a.AgentID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a agentSessionMap) clone(db *gorm.DB) agentSessionMap {
	a.agentSessionMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentSessionMap) replaceDB(db *gorm.DB) agentSessionMap {
	a.agentSessionMapDo.ReplaceDB(db)
	return a
}

type agentSessionMapDo struct{ gen.DO }

func (a agentSessionMapDo) Debug() *agentSessionMapDo {
	return a.withDO(a.DO.Debug())
}

func (a agentSessionMapDo) WithContext(ctx context.Context) *agentSessionMapDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentSessionMapDo) ReadDB() *agentSessionMapDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentSessionMapDo) WriteDB() *agentSessionMapDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentSessionMapDo) Session(config *gorm.Session) *agentSessionMapDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentSessionMapDo) Clauses(conds ...clause.Expression) *agentSessionMapDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentSessionMapDo) Returning(value interface{}, columns ...string) *agentSessionMapDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentSessionMapDo) Not(conds ...gen.Condition) *agentSessionMapDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentSessionMapDo) Or(conds ...gen.Condition) *agentSessionMapDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentSessionMapDo) Select(conds ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentSessionMapDo) Where(conds ...gen.Condition) *agentSessionMapDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentSessionMapDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *agentSessionMapDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a agentSessionMapDo) Order(conds ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentSessionMapDo) Distinct(cols ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentSessionMapDo) Omit(cols ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentSessionMapDo) Join(table schema.Tabler, on ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentSessionMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentSessionMapDo) RightJoin(table schema.Tabler, on ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentSessionMapDo) Group(cols ...field.Expr) *agentSessionMapDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentSessionMapDo) Having(conds ...gen.Condition) *agentSessionMapDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentSessionMapDo) Limit(limit int) *agentSessionMapDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentSessionMapDo) Offset(offset int) *agentSessionMapDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentSessionMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *agentSessionMapDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentSessionMapDo) Unscoped() *agentSessionMapDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentSessionMapDo) Create(values ...*model.AgentSessionMap) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentSessionMapDo) CreateInBatches(values []*model.AgentSessionMap, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentSessionMapDo) Save(values ...*model.AgentSessionMap) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentSessionMapDo) First() (*model.AgentSessionMap, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentSessionMap), nil
	}
}

func (a agentSessionMapDo) Take() (*model.AgentSessionMap, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentSessionMap), nil
	}
}

func (a agentSessionMapDo) Last() (*model.AgentSessionMap, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentSessionMap), nil
	}
}

func (a agentSessionMapDo) Find() ([]*model.AgentSessionMap, error) {
	result, err := a.DO.Find()
	return result.([]*model.AgentSessionMap), err
}

func (a agentSessionMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AgentSessionMap, err error) {
	buf := make([]*model.AgentSessionMap, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentSessionMapDo) FindInBatches(result *[]*model.AgentSessionMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentSessionMapDo) Attrs(attrs ...field.AssignExpr) *agentSessionMapDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentSessionMapDo) Assign(attrs ...field.AssignExpr) *agentSessionMapDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentSessionMapDo) Joins(fields ...field.RelationField) *agentSessionMapDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentSessionMapDo) Preload(fields ...field.RelationField) *agentSessionMapDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentSessionMapDo) FirstOrInit() (*model.AgentSessionMap, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentSessionMap), nil
	}
}

func (a agentSessionMapDo) FirstOrCreate() (*model.AgentSessionMap, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AgentSessionMap), nil
	}
}

func (a agentSessionMapDo) FindByPage(offset int, limit int) (result []*model.AgentSessionMap, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentSessionMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentSessionMapDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentSessionMapDo) Delete(models ...*model.AgentSessionMap) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentSessionMapDo) withDO(do gen.Dao) *agentSessionMapDo {
	a.DO = *do.(*gen.DO)
	return a
}
