// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3RunControl(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3RunControl {
	_bidAnalysisV3RunControl := bidAnalysisV3RunControl{}

	_bidAnalysisV3RunControl.bidAnalysisV3RunControlDo.UseDB(db, opts...)
	_bidAnalysisV3RunControl.bidAnalysisV3RunControlDo.UseModel(&model.BidAnalysisV3RunControl{})

	tableName := _bidAnalysisV3RunControl.bidAnalysisV3RunControlDo.TableName()
	_bidAnalysisV3RunControl.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3RunControl.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3RunControl.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3RunControl.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3RunControl.Action = field.NewString(tableName, "action")
	_bidAnalysisV3RunControl.Mode = field.NewString(tableName, "mode")
	_bidAnalysisV3RunControl.TargetStage = field.NewString(tableName, "target_stage")
	_bidAnalysisV3RunControl.ResumeStage = field.NewString(tableName, "resume_stage")
	_bidAnalysisV3RunControl.Status = field.NewString(tableName, "status")
	_bidAnalysisV3RunControl.OperatorID = field.NewInt64(tableName, "operator_id")
	_bidAnalysisV3RunControl.LastError = field.NewString(tableName, "last_error")
	_bidAnalysisV3RunControl.RequestedAt = field.NewTime(tableName, "requested_at")
	_bidAnalysisV3RunControl.AppliedAt = field.NewTime(tableName, "applied_at")
	_bidAnalysisV3RunControl.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3RunControl.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3RunControl.fillFieldMap()

	return _bidAnalysisV3RunControl
}

type bidAnalysisV3RunControl struct {
	bidAnalysisV3RunControlDo bidAnalysisV3RunControlDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键
	ProjectID   field.Int64  // 招标解析项目ID
	RunID       field.Int64  // 解析运行ID
	Action      field.String // pause/skip
	Mode        field.String // after_stage/discard_current
	TargetStage field.String // 请求作用的阶段
	ResumeStage field.String // 暂停后继续或跳过后进入的阶段
	Status      field.String // requested/applying/applied/cancelled/failed
	OperatorID  field.Int64  // 操作人ID
	LastError   field.String // 应用控制失败原因
	RequestedAt field.Time   // 请求时间
	AppliedAt   field.Time   // 生效时间
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3RunControl) Table(newTableName string) *bidAnalysisV3RunControl {
	b.bidAnalysisV3RunControlDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3RunControl) As(alias string) *bidAnalysisV3RunControl {
	b.bidAnalysisV3RunControlDo.DO = *(b.bidAnalysisV3RunControlDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3RunControl) updateTableName(table string) *bidAnalysisV3RunControl {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.Action = field.NewString(table, "action")
	b.Mode = field.NewString(table, "mode")
	b.TargetStage = field.NewString(table, "target_stage")
	b.ResumeStage = field.NewString(table, "resume_stage")
	b.Status = field.NewString(table, "status")
	b.OperatorID = field.NewInt64(table, "operator_id")
	b.LastError = field.NewString(table, "last_error")
	b.RequestedAt = field.NewTime(table, "requested_at")
	b.AppliedAt = field.NewTime(table, "applied_at")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3RunControl) WithContext(ctx context.Context) *bidAnalysisV3RunControlDo {
	return b.bidAnalysisV3RunControlDo.WithContext(ctx)
}

func (b bidAnalysisV3RunControl) TableName() string { return b.bidAnalysisV3RunControlDo.TableName() }

func (b bidAnalysisV3RunControl) Alias() string { return b.bidAnalysisV3RunControlDo.Alias() }

func (b *bidAnalysisV3RunControl) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3RunControl) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 14)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["action"] = b.Action
	b.fieldMap["mode"] = b.Mode
	b.fieldMap["target_stage"] = b.TargetStage
	b.fieldMap["resume_stage"] = b.ResumeStage
	b.fieldMap["status"] = b.Status
	b.fieldMap["operator_id"] = b.OperatorID
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["requested_at"] = b.RequestedAt
	b.fieldMap["applied_at"] = b.AppliedAt
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3RunControl) clone(db *gorm.DB) bidAnalysisV3RunControl {
	b.bidAnalysisV3RunControlDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3RunControl) replaceDB(db *gorm.DB) bidAnalysisV3RunControl {
	b.bidAnalysisV3RunControlDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3RunControlDo struct{ gen.DO }

func (b bidAnalysisV3RunControlDo) Debug() *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3RunControlDo) WithContext(ctx context.Context) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3RunControlDo) ReadDB() *bidAnalysisV3RunControlDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3RunControlDo) WriteDB() *bidAnalysisV3RunControlDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3RunControlDo) Session(config *gorm.Session) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3RunControlDo) Clauses(conds ...clause.Expression) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3RunControlDo) Returning(value interface{}, columns ...string) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3RunControlDo) Not(conds ...gen.Condition) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3RunControlDo) Or(conds ...gen.Condition) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3RunControlDo) Select(conds ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3RunControlDo) Where(conds ...gen.Condition) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3RunControlDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3RunControlDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3RunControlDo) Order(conds ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3RunControlDo) Distinct(cols ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3RunControlDo) Omit(cols ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3RunControlDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3RunControlDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3RunControlDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3RunControlDo) Group(cols ...field.Expr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3RunControlDo) Having(conds ...gen.Condition) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3RunControlDo) Limit(limit int) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3RunControlDo) Offset(offset int) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3RunControlDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3RunControlDo) Unscoped() *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3RunControlDo) Create(values ...*model.BidAnalysisV3RunControl) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3RunControlDo) CreateInBatches(values []*model.BidAnalysisV3RunControl, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3RunControlDo) Save(values ...*model.BidAnalysisV3RunControl) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3RunControlDo) First() (*model.BidAnalysisV3RunControl, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3RunControl), nil
	}
}

func (b bidAnalysisV3RunControlDo) Take() (*model.BidAnalysisV3RunControl, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3RunControl), nil
	}
}

func (b bidAnalysisV3RunControlDo) Last() (*model.BidAnalysisV3RunControl, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3RunControl), nil
	}
}

func (b bidAnalysisV3RunControlDo) Find() ([]*model.BidAnalysisV3RunControl, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3RunControl), err
}

func (b bidAnalysisV3RunControlDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3RunControl, err error) {
	buf := make([]*model.BidAnalysisV3RunControl, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3RunControlDo) FindInBatches(result *[]*model.BidAnalysisV3RunControl, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3RunControlDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3RunControlDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3RunControlDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3RunControlDo) Joins(fields ...field.RelationField) *bidAnalysisV3RunControlDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3RunControlDo) Preload(fields ...field.RelationField) *bidAnalysisV3RunControlDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3RunControlDo) FirstOrInit() (*model.BidAnalysisV3RunControl, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3RunControl), nil
	}
}

func (b bidAnalysisV3RunControlDo) FirstOrCreate() (*model.BidAnalysisV3RunControl, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3RunControl), nil
	}
}

func (b bidAnalysisV3RunControlDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3RunControl, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3RunControlDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3RunControlDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3RunControlDo) Delete(models ...*model.BidAnalysisV3RunControl) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3RunControlDo) withDO(do gen.Dao) *bidAnalysisV3RunControlDo {
	b.DO = *do.(*gen.DO)
	return b
}
