// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3StageTask(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3StageTask {
	_bidAnalysisV3StageTask := bidAnalysisV3StageTask{}

	_bidAnalysisV3StageTask.bidAnalysisV3StageTaskDo.UseDB(db, opts...)
	_bidAnalysisV3StageTask.bidAnalysisV3StageTaskDo.UseModel(&model.BidAnalysisV3StageTask{})

	tableName := _bidAnalysisV3StageTask.bidAnalysisV3StageTaskDo.TableName()
	_bidAnalysisV3StageTask.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3StageTask.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3StageTask.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3StageTask.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3StageTask.Stage = field.NewString(tableName, "stage")
	_bidAnalysisV3StageTask.TaskType = field.NewString(tableName, "task_type")
	_bidAnalysisV3StageTask.UnitKey = field.NewString(tableName, "unit_key")
	_bidAnalysisV3StageTask.PageStart = field.NewInt32(tableName, "page_start")
	_bidAnalysisV3StageTask.PageEnd = field.NewInt32(tableName, "page_end")
	_bidAnalysisV3StageTask.ChapterID = field.NewInt64(tableName, "chapter_id")
	_bidAnalysisV3StageTask.Status = field.NewString(tableName, "status")
	_bidAnalysisV3StageTask.Attempts = field.NewInt32(tableName, "attempts")
	_bidAnalysisV3StageTask.PayloadHash = field.NewString(tableName, "payload_hash")
	_bidAnalysisV3StageTask.ResultHash = field.NewString(tableName, "result_hash")
	_bidAnalysisV3StageTask.LastError = field.NewString(tableName, "last_error")
	_bidAnalysisV3StageTask.StartedAt = field.NewTime(tableName, "started_at")
	_bidAnalysisV3StageTask.CompletedAt = field.NewTime(tableName, "completed_at")
	_bidAnalysisV3StageTask.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3StageTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3StageTask.fillFieldMap()

	return _bidAnalysisV3StageTask
}

type bidAnalysisV3StageTask struct {
	bidAnalysisV3StageTaskDo bidAnalysisV3StageTaskDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键
	ProjectID   field.Int64  // 招标解析项目ID
	RunID       field.Int64  // 解析运行ID
	Stage       field.String // 当前处理阶段
	TaskType    field.String // 任务类型
	UnitKey     field.String // 任务单元唯一键
	PageStart   field.Int32  // 起始页码
	PageEnd     field.Int32  // 结束页码
	ChapterID   field.Int64  // 章节ID
	Status      field.String // pending/running/succeeded/failed/cancelled
	Attempts    field.Int32  // 已尝试次数
	PayloadHash field.String // payload_hash字段
	ResultHash  field.String // result_hash字段
	LastError   field.String // 最近一次错误信息
	StartedAt   field.Time   // 开始时间
	CompletedAt field.Time   // 完成时间
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3StageTask) Table(newTableName string) *bidAnalysisV3StageTask {
	b.bidAnalysisV3StageTaskDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3StageTask) As(alias string) *bidAnalysisV3StageTask {
	b.bidAnalysisV3StageTaskDo.DO = *(b.bidAnalysisV3StageTaskDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3StageTask) updateTableName(table string) *bidAnalysisV3StageTask {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.Stage = field.NewString(table, "stage")
	b.TaskType = field.NewString(table, "task_type")
	b.UnitKey = field.NewString(table, "unit_key")
	b.PageStart = field.NewInt32(table, "page_start")
	b.PageEnd = field.NewInt32(table, "page_end")
	b.ChapterID = field.NewInt64(table, "chapter_id")
	b.Status = field.NewString(table, "status")
	b.Attempts = field.NewInt32(table, "attempts")
	b.PayloadHash = field.NewString(table, "payload_hash")
	b.ResultHash = field.NewString(table, "result_hash")
	b.LastError = field.NewString(table, "last_error")
	b.StartedAt = field.NewTime(table, "started_at")
	b.CompletedAt = field.NewTime(table, "completed_at")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3StageTask) WithContext(ctx context.Context) *bidAnalysisV3StageTaskDo {
	return b.bidAnalysisV3StageTaskDo.WithContext(ctx)
}

func (b bidAnalysisV3StageTask) TableName() string { return b.bidAnalysisV3StageTaskDo.TableName() }

func (b bidAnalysisV3StageTask) Alias() string { return b.bidAnalysisV3StageTaskDo.Alias() }

func (b *bidAnalysisV3StageTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3StageTask) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 18)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["task_type"] = b.TaskType
	b.fieldMap["unit_key"] = b.UnitKey
	b.fieldMap["page_start"] = b.PageStart
	b.fieldMap["page_end"] = b.PageEnd
	b.fieldMap["chapter_id"] = b.ChapterID
	b.fieldMap["status"] = b.Status
	b.fieldMap["attempts"] = b.Attempts
	b.fieldMap["payload_hash"] = b.PayloadHash
	b.fieldMap["result_hash"] = b.ResultHash
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["started_at"] = b.StartedAt
	b.fieldMap["completed_at"] = b.CompletedAt
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3StageTask) clone(db *gorm.DB) bidAnalysisV3StageTask {
	b.bidAnalysisV3StageTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3StageTask) replaceDB(db *gorm.DB) bidAnalysisV3StageTask {
	b.bidAnalysisV3StageTaskDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3StageTaskDo struct{ gen.DO }

func (b bidAnalysisV3StageTaskDo) Debug() *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3StageTaskDo) WithContext(ctx context.Context) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3StageTaskDo) ReadDB() *bidAnalysisV3StageTaskDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3StageTaskDo) WriteDB() *bidAnalysisV3StageTaskDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3StageTaskDo) Session(config *gorm.Session) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3StageTaskDo) Clauses(conds ...clause.Expression) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3StageTaskDo) Returning(value interface{}, columns ...string) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3StageTaskDo) Not(conds ...gen.Condition) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3StageTaskDo) Or(conds ...gen.Condition) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3StageTaskDo) Select(conds ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3StageTaskDo) Where(conds ...gen.Condition) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3StageTaskDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3StageTaskDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3StageTaskDo) Order(conds ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3StageTaskDo) Distinct(cols ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3StageTaskDo) Omit(cols ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3StageTaskDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3StageTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3StageTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3StageTaskDo) Group(cols ...field.Expr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3StageTaskDo) Having(conds ...gen.Condition) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3StageTaskDo) Limit(limit int) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3StageTaskDo) Offset(offset int) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3StageTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3StageTaskDo) Unscoped() *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3StageTaskDo) Create(values ...*model.BidAnalysisV3StageTask) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3StageTaskDo) CreateInBatches(values []*model.BidAnalysisV3StageTask, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3StageTaskDo) Save(values ...*model.BidAnalysisV3StageTask) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3StageTaskDo) First() (*model.BidAnalysisV3StageTask, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageTask), nil
	}
}

func (b bidAnalysisV3StageTaskDo) Take() (*model.BidAnalysisV3StageTask, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageTask), nil
	}
}

func (b bidAnalysisV3StageTaskDo) Last() (*model.BidAnalysisV3StageTask, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageTask), nil
	}
}

func (b bidAnalysisV3StageTaskDo) Find() ([]*model.BidAnalysisV3StageTask, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3StageTask), err
}

func (b bidAnalysisV3StageTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3StageTask, err error) {
	buf := make([]*model.BidAnalysisV3StageTask, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3StageTaskDo) FindInBatches(result *[]*model.BidAnalysisV3StageTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3StageTaskDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3StageTaskDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3StageTaskDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3StageTaskDo) Joins(fields ...field.RelationField) *bidAnalysisV3StageTaskDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3StageTaskDo) Preload(fields ...field.RelationField) *bidAnalysisV3StageTaskDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3StageTaskDo) FirstOrInit() (*model.BidAnalysisV3StageTask, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageTask), nil
	}
}

func (b bidAnalysisV3StageTaskDo) FirstOrCreate() (*model.BidAnalysisV3StageTask, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageTask), nil
	}
}

func (b bidAnalysisV3StageTaskDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3StageTask, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3StageTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3StageTaskDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3StageTaskDo) Delete(models ...*model.BidAnalysisV3StageTask) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3StageTaskDo) withDO(do gen.Dao) *bidAnalysisV3StageTaskDo {
	b.DO = *do.(*gen.DO)
	return b
}
