// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3LlmCall(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3LlmCall {
	_bidAnalysisV3LlmCall := bidAnalysisV3LlmCall{}

	_bidAnalysisV3LlmCall.bidAnalysisV3LlmCallDo.UseDB(db, opts...)
	_bidAnalysisV3LlmCall.bidAnalysisV3LlmCallDo.UseModel(&model.BidAnalysisV3LlmCall{})

	tableName := _bidAnalysisV3LlmCall.bidAnalysisV3LlmCallDo.TableName()
	_bidAnalysisV3LlmCall.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3LlmCall.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3LlmCall.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3LlmCall.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3LlmCall.TaskID = field.NewInt64(tableName, "task_id")
	_bidAnalysisV3LlmCall.Feature = field.NewString(tableName, "feature")
	_bidAnalysisV3LlmCall.Provider = field.NewString(tableName, "provider")
	_bidAnalysisV3LlmCall.Model = field.NewString(tableName, "model")
	_bidAnalysisV3LlmCall.RequestHash = field.NewString(tableName, "request_hash")
	_bidAnalysisV3LlmCall.ResponseHash = field.NewString(tableName, "response_hash")
	_bidAnalysisV3LlmCall.PromptTokens = field.NewInt32(tableName, "prompt_tokens")
	_bidAnalysisV3LlmCall.CompletionTokens = field.NewInt32(tableName, "completion_tokens")
	_bidAnalysisV3LlmCall.LatencyMs = field.NewInt64(tableName, "latency_ms")
	_bidAnalysisV3LlmCall.Status = field.NewString(tableName, "status")
	_bidAnalysisV3LlmCall.ErrorCode = field.NewString(tableName, "error_code")
	_bidAnalysisV3LlmCall.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3LlmCall.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3LlmCall.fillFieldMap()

	return _bidAnalysisV3LlmCall
}

type bidAnalysisV3LlmCall struct {
	bidAnalysisV3LlmCallDo bidAnalysisV3LlmCallDo

	ALL              field.Asterisk
	ID               field.Int64  // 主键
	ProjectID        field.Int64  // 招标解析项目ID
	RunID            field.Int64  // 解析运行ID
	TaskID           field.Int64  // 阶段任务ID
	Feature          field.String // LLM功能名称
	Provider         field.String // 模型提供商
	Model            field.String // 模型名称
	RequestHash      field.String // 请求内容哈希
	ResponseHash     field.String // 响应内容哈希
	PromptTokens     field.Int32  // 输入Token数量
	CompletionTokens field.Int32  // 输出Token数量
	LatencyMs        field.Int64  // 调用耗时（毫秒）
	Status           field.String // 状态
	ErrorCode        field.String // 错误代码
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3LlmCall) Table(newTableName string) *bidAnalysisV3LlmCall {
	b.bidAnalysisV3LlmCallDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3LlmCall) As(alias string) *bidAnalysisV3LlmCall {
	b.bidAnalysisV3LlmCallDo.DO = *(b.bidAnalysisV3LlmCallDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3LlmCall) updateTableName(table string) *bidAnalysisV3LlmCall {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.TaskID = field.NewInt64(table, "task_id")
	b.Feature = field.NewString(table, "feature")
	b.Provider = field.NewString(table, "provider")
	b.Model = field.NewString(table, "model")
	b.RequestHash = field.NewString(table, "request_hash")
	b.ResponseHash = field.NewString(table, "response_hash")
	b.PromptTokens = field.NewInt32(table, "prompt_tokens")
	b.CompletionTokens = field.NewInt32(table, "completion_tokens")
	b.LatencyMs = field.NewInt64(table, "latency_ms")
	b.Status = field.NewString(table, "status")
	b.ErrorCode = field.NewString(table, "error_code")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3LlmCall) WithContext(ctx context.Context) *bidAnalysisV3LlmCallDo {
	return b.bidAnalysisV3LlmCallDo.WithContext(ctx)
}

func (b bidAnalysisV3LlmCall) TableName() string { return b.bidAnalysisV3LlmCallDo.TableName() }

func (b bidAnalysisV3LlmCall) Alias() string { return b.bidAnalysisV3LlmCallDo.Alias() }

func (b *bidAnalysisV3LlmCall) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3LlmCall) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 16)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["task_id"] = b.TaskID
	b.fieldMap["feature"] = b.Feature
	b.fieldMap["provider"] = b.Provider
	b.fieldMap["model"] = b.Model
	b.fieldMap["request_hash"] = b.RequestHash
	b.fieldMap["response_hash"] = b.ResponseHash
	b.fieldMap["prompt_tokens"] = b.PromptTokens
	b.fieldMap["completion_tokens"] = b.CompletionTokens
	b.fieldMap["latency_ms"] = b.LatencyMs
	b.fieldMap["status"] = b.Status
	b.fieldMap["error_code"] = b.ErrorCode
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3LlmCall) clone(db *gorm.DB) bidAnalysisV3LlmCall {
	b.bidAnalysisV3LlmCallDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3LlmCall) replaceDB(db *gorm.DB) bidAnalysisV3LlmCall {
	b.bidAnalysisV3LlmCallDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3LlmCallDo struct{ gen.DO }

func (b bidAnalysisV3LlmCallDo) Debug() *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3LlmCallDo) WithContext(ctx context.Context) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3LlmCallDo) ReadDB() *bidAnalysisV3LlmCallDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3LlmCallDo) WriteDB() *bidAnalysisV3LlmCallDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3LlmCallDo) Session(config *gorm.Session) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3LlmCallDo) Clauses(conds ...clause.Expression) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3LlmCallDo) Returning(value interface{}, columns ...string) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3LlmCallDo) Not(conds ...gen.Condition) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3LlmCallDo) Or(conds ...gen.Condition) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3LlmCallDo) Select(conds ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3LlmCallDo) Where(conds ...gen.Condition) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3LlmCallDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3LlmCallDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3LlmCallDo) Order(conds ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3LlmCallDo) Distinct(cols ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3LlmCallDo) Omit(cols ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3LlmCallDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3LlmCallDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3LlmCallDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3LlmCallDo) Group(cols ...field.Expr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3LlmCallDo) Having(conds ...gen.Condition) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3LlmCallDo) Limit(limit int) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3LlmCallDo) Offset(offset int) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3LlmCallDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3LlmCallDo) Unscoped() *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3LlmCallDo) Create(values ...*model.BidAnalysisV3LlmCall) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3LlmCallDo) CreateInBatches(values []*model.BidAnalysisV3LlmCall, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3LlmCallDo) Save(values ...*model.BidAnalysisV3LlmCall) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3LlmCallDo) First() (*model.BidAnalysisV3LlmCall, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3LlmCall), nil
	}
}

func (b bidAnalysisV3LlmCallDo) Take() (*model.BidAnalysisV3LlmCall, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3LlmCall), nil
	}
}

func (b bidAnalysisV3LlmCallDo) Last() (*model.BidAnalysisV3LlmCall, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3LlmCall), nil
	}
}

func (b bidAnalysisV3LlmCallDo) Find() ([]*model.BidAnalysisV3LlmCall, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3LlmCall), err
}

func (b bidAnalysisV3LlmCallDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3LlmCall, err error) {
	buf := make([]*model.BidAnalysisV3LlmCall, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3LlmCallDo) FindInBatches(result *[]*model.BidAnalysisV3LlmCall, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3LlmCallDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3LlmCallDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3LlmCallDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3LlmCallDo) Joins(fields ...field.RelationField) *bidAnalysisV3LlmCallDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3LlmCallDo) Preload(fields ...field.RelationField) *bidAnalysisV3LlmCallDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3LlmCallDo) FirstOrInit() (*model.BidAnalysisV3LlmCall, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3LlmCall), nil
	}
}

func (b bidAnalysisV3LlmCallDo) FirstOrCreate() (*model.BidAnalysisV3LlmCall, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3LlmCall), nil
	}
}

func (b bidAnalysisV3LlmCallDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3LlmCall, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3LlmCallDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3LlmCallDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3LlmCallDo) Delete(models ...*model.BidAnalysisV3LlmCall) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3LlmCallDo) withDO(do gen.Dao) *bidAnalysisV3LlmCallDo {
	b.DO = *do.(*gen.DO)
	return b
}
