// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3Project(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3Project {
	_bidAnalysisV3Project := bidAnalysisV3Project{}

	_bidAnalysisV3Project.bidAnalysisV3ProjectDo.UseDB(db, opts...)
	_bidAnalysisV3Project.bidAnalysisV3ProjectDo.UseModel(&model.BidAnalysisV3Project{})

	tableName := _bidAnalysisV3Project.bidAnalysisV3ProjectDo.TableName()
	_bidAnalysisV3Project.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3Project.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3Project.Name = field.NewString(tableName, "name")
	_bidAnalysisV3Project.SourceFileName = field.NewString(tableName, "source_file_name")
	_bidAnalysisV3Project.SourceBucket = field.NewString(tableName, "source_bucket")
	_bidAnalysisV3Project.SourceObject = field.NewString(tableName, "source_object")
	_bidAnalysisV3Project.SourceSha256 = field.NewString(tableName, "source_sha256")
	_bidAnalysisV3Project.NormalizedPdfBucket = field.NewString(tableName, "normalized_pdf_bucket")
	_bidAnalysisV3Project.NormalizedPdfObject = field.NewString(tableName, "normalized_pdf_object")
	_bidAnalysisV3Project.Status = field.NewString(tableName, "status")
	_bidAnalysisV3Project.Stage = field.NewString(tableName, "stage")
	_bidAnalysisV3Project.Progress = field.NewInt32(tableName, "progress")
	_bidAnalysisV3Project.CurrentRunID = field.NewInt64(tableName, "current_run_id")
	_bidAnalysisV3Project.PageCount = field.NewInt32(tableName, "page_count")
	_bidAnalysisV3Project.WarningCount = field.NewInt32(tableName, "warning_count")
	_bidAnalysisV3Project.LastError = field.NewString(tableName, "last_error")
	_bidAnalysisV3Project.UserID = field.NewInt64(tableName, "user_id")
	_bidAnalysisV3Project.UserTeamID = field.NewInt32(tableName, "user_team_id")
	_bidAnalysisV3Project.UserCompanyID = field.NewInt32(tableName, "user_company_id")
	_bidAnalysisV3Project.IsInternal = field.NewBool(tableName, "is_internal")
	_bidAnalysisV3Project.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3Project.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3Project.fillFieldMap()

	return _bidAnalysisV3Project
}

type bidAnalysisV3Project struct {
	bidAnalysisV3ProjectDo bidAnalysisV3ProjectDo

	ALL                 field.Asterisk
	ID                  field.Int64  // 主键
	Name                field.String // 项目名称
	SourceFileName      field.String // 原始文件名
	SourceBucket        field.String // 源文件桶
	SourceObject        field.String // 源文件对象键
	SourceSha256        field.String // 源文件SHA256
	NormalizedPdfBucket field.String // 规范化PDF桶
	NormalizedPdfObject field.String // 规范化PDF对象键
	Status              field.String // running/paused/succeeded/succeeded_with_warnings/failed
	Stage               field.String // 当前阶段
	Progress            field.Int32  // 0-100
	CurrentRunID        field.Int64  // 当前生效解析运行ID
	PageCount           field.Int32  // 文档总页数
	WarningCount        field.Int32  // 告警数量
	LastError           field.String // 最近一次错误信息
	UserID              field.Int64  // 用户ID
	UserTeamID          field.Int32  // 用户团队ID
	UserCompanyID       field.Int32  // 用户公司ID
	IsInternal          field.Bool   // 是否内部项目
	CreatedAt           field.Time   // 创建时间
	UpdatedAt           field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3Project) Table(newTableName string) *bidAnalysisV3Project {
	b.bidAnalysisV3ProjectDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3Project) As(alias string) *bidAnalysisV3Project {
	b.bidAnalysisV3ProjectDo.DO = *(b.bidAnalysisV3ProjectDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3Project) updateTableName(table string) *bidAnalysisV3Project {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Name = field.NewString(table, "name")
	b.SourceFileName = field.NewString(table, "source_file_name")
	b.SourceBucket = field.NewString(table, "source_bucket")
	b.SourceObject = field.NewString(table, "source_object")
	b.SourceSha256 = field.NewString(table, "source_sha256")
	b.NormalizedPdfBucket = field.NewString(table, "normalized_pdf_bucket")
	b.NormalizedPdfObject = field.NewString(table, "normalized_pdf_object")
	b.Status = field.NewString(table, "status")
	b.Stage = field.NewString(table, "stage")
	b.Progress = field.NewInt32(table, "progress")
	b.CurrentRunID = field.NewInt64(table, "current_run_id")
	b.PageCount = field.NewInt32(table, "page_count")
	b.WarningCount = field.NewInt32(table, "warning_count")
	b.LastError = field.NewString(table, "last_error")
	b.UserID = field.NewInt64(table, "user_id")
	b.UserTeamID = field.NewInt32(table, "user_team_id")
	b.UserCompanyID = field.NewInt32(table, "user_company_id")
	b.IsInternal = field.NewBool(table, "is_internal")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3Project) WithContext(ctx context.Context) *bidAnalysisV3ProjectDo {
	return b.bidAnalysisV3ProjectDo.WithContext(ctx)
}

func (b bidAnalysisV3Project) TableName() string { return b.bidAnalysisV3ProjectDo.TableName() }

func (b bidAnalysisV3Project) Alias() string { return b.bidAnalysisV3ProjectDo.Alias() }

func (b *bidAnalysisV3Project) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3Project) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 21)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["source_file_name"] = b.SourceFileName
	b.fieldMap["source_bucket"] = b.SourceBucket
	b.fieldMap["source_object"] = b.SourceObject
	b.fieldMap["source_sha256"] = b.SourceSha256
	b.fieldMap["normalized_pdf_bucket"] = b.NormalizedPdfBucket
	b.fieldMap["normalized_pdf_object"] = b.NormalizedPdfObject
	b.fieldMap["status"] = b.Status
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["progress"] = b.Progress
	b.fieldMap["current_run_id"] = b.CurrentRunID
	b.fieldMap["page_count"] = b.PageCount
	b.fieldMap["warning_count"] = b.WarningCount
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["user_team_id"] = b.UserTeamID
	b.fieldMap["user_company_id"] = b.UserCompanyID
	b.fieldMap["is_internal"] = b.IsInternal
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3Project) clone(db *gorm.DB) bidAnalysisV3Project {
	b.bidAnalysisV3ProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3Project) replaceDB(db *gorm.DB) bidAnalysisV3Project {
	b.bidAnalysisV3ProjectDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3ProjectDo struct{ gen.DO }

func (b bidAnalysisV3ProjectDo) Debug() *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3ProjectDo) WithContext(ctx context.Context) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3ProjectDo) ReadDB() *bidAnalysisV3ProjectDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3ProjectDo) WriteDB() *bidAnalysisV3ProjectDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3ProjectDo) Session(config *gorm.Session) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3ProjectDo) Clauses(conds ...clause.Expression) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3ProjectDo) Returning(value interface{}, columns ...string) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3ProjectDo) Not(conds ...gen.Condition) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3ProjectDo) Or(conds ...gen.Condition) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3ProjectDo) Select(conds ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3ProjectDo) Where(conds ...gen.Condition) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3ProjectDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3ProjectDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3ProjectDo) Order(conds ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3ProjectDo) Distinct(cols ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3ProjectDo) Omit(cols ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3ProjectDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3ProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3ProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3ProjectDo) Group(cols ...field.Expr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3ProjectDo) Having(conds ...gen.Condition) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3ProjectDo) Limit(limit int) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3ProjectDo) Offset(offset int) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3ProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3ProjectDo) Unscoped() *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3ProjectDo) Create(values ...*model.BidAnalysisV3Project) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3ProjectDo) CreateInBatches(values []*model.BidAnalysisV3Project, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3ProjectDo) Save(values ...*model.BidAnalysisV3Project) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3ProjectDo) First() (*model.BidAnalysisV3Project, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Project), nil
	}
}

func (b bidAnalysisV3ProjectDo) Take() (*model.BidAnalysisV3Project, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Project), nil
	}
}

func (b bidAnalysisV3ProjectDo) Last() (*model.BidAnalysisV3Project, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Project), nil
	}
}

func (b bidAnalysisV3ProjectDo) Find() ([]*model.BidAnalysisV3Project, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3Project), err
}

func (b bidAnalysisV3ProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3Project, err error) {
	buf := make([]*model.BidAnalysisV3Project, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3ProjectDo) FindInBatches(result *[]*model.BidAnalysisV3Project, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3ProjectDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3ProjectDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3ProjectDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3ProjectDo) Joins(fields ...field.RelationField) *bidAnalysisV3ProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3ProjectDo) Preload(fields ...field.RelationField) *bidAnalysisV3ProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3ProjectDo) FirstOrInit() (*model.BidAnalysisV3Project, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Project), nil
	}
}

func (b bidAnalysisV3ProjectDo) FirstOrCreate() (*model.BidAnalysisV3Project, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Project), nil
	}
}

func (b bidAnalysisV3ProjectDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3Project, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3ProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3ProjectDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3ProjectDo) Delete(models ...*model.BidAnalysisV3Project) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3ProjectDo) withDO(do gen.Dao) *bidAnalysisV3ProjectDo {
	b.DO = *do.(*gen.DO)
	return b
}
