// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3DerivedTableEvidence(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3DerivedTableEvidence {
	_bidAnalysisV3DerivedTableEvidence := bidAnalysisV3DerivedTableEvidence{}

	_bidAnalysisV3DerivedTableEvidence.bidAnalysisV3DerivedTableEvidenceDo.UseDB(db, opts...)
	_bidAnalysisV3DerivedTableEvidence.bidAnalysisV3DerivedTableEvidenceDo.UseModel(&model.BidAnalysisV3DerivedTableEvidence{})

	tableName := _bidAnalysisV3DerivedTableEvidence.bidAnalysisV3DerivedTableEvidenceDo.TableName()
	_bidAnalysisV3DerivedTableEvidence.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3DerivedTableEvidence.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3DerivedTableEvidence.DerivedTableID = field.NewInt64(tableName, "derived_table_id")
	_bidAnalysisV3DerivedTableEvidence.SourceKind = field.NewString(tableName, "source_kind")
	_bidAnalysisV3DerivedTableEvidence.BlockID = field.NewInt64(tableName, "block_id")
	_bidAnalysisV3DerivedTableEvidence.SourceTableID = field.NewInt64(tableName, "source_table_id")
	_bidAnalysisV3DerivedTableEvidence.PageNo = field.NewInt32(tableName, "page_no")
	_bidAnalysisV3DerivedTableEvidence.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidAnalysisV3DerivedTableEvidence.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3DerivedTableEvidence.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3DerivedTableEvidence.fillFieldMap()

	return _bidAnalysisV3DerivedTableEvidence
}

type bidAnalysisV3DerivedTableEvidence struct {
	bidAnalysisV3DerivedTableEvidenceDo bidAnalysisV3DerivedTableEvidenceDo

	ALL            field.Asterisk
	ID             field.Int64  // 主键
	DerivedTableID field.Int64  // 归并表ID
	SourceKind     field.String // 证据来源类型
	BlockID        field.Int64  // 文档文本块ID
	SourceTableID  field.Int64  // 原文表格ID
	PageNo         field.Int32  // 全局页码
	SortOrder      field.Int32  // 排序序号
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3DerivedTableEvidence) Table(newTableName string) *bidAnalysisV3DerivedTableEvidence {
	b.bidAnalysisV3DerivedTableEvidenceDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3DerivedTableEvidence) As(alias string) *bidAnalysisV3DerivedTableEvidence {
	b.bidAnalysisV3DerivedTableEvidenceDo.DO = *(b.bidAnalysisV3DerivedTableEvidenceDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3DerivedTableEvidence) updateTableName(table string) *bidAnalysisV3DerivedTableEvidence {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.DerivedTableID = field.NewInt64(table, "derived_table_id")
	b.SourceKind = field.NewString(table, "source_kind")
	b.BlockID = field.NewInt64(table, "block_id")
	b.SourceTableID = field.NewInt64(table, "source_table_id")
	b.PageNo = field.NewInt32(table, "page_no")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3DerivedTableEvidence) WithContext(ctx context.Context) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.bidAnalysisV3DerivedTableEvidenceDo.WithContext(ctx)
}

func (b bidAnalysisV3DerivedTableEvidence) TableName() string {
	return b.bidAnalysisV3DerivedTableEvidenceDo.TableName()
}

func (b bidAnalysisV3DerivedTableEvidence) Alias() string {
	return b.bidAnalysisV3DerivedTableEvidenceDo.Alias()
}

func (b *bidAnalysisV3DerivedTableEvidence) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3DerivedTableEvidence) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["derived_table_id"] = b.DerivedTableID
	b.fieldMap["source_kind"] = b.SourceKind
	b.fieldMap["block_id"] = b.BlockID
	b.fieldMap["source_table_id"] = b.SourceTableID
	b.fieldMap["page_no"] = b.PageNo
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3DerivedTableEvidence) clone(db *gorm.DB) bidAnalysisV3DerivedTableEvidence {
	b.bidAnalysisV3DerivedTableEvidenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3DerivedTableEvidence) replaceDB(db *gorm.DB) bidAnalysisV3DerivedTableEvidence {
	b.bidAnalysisV3DerivedTableEvidenceDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3DerivedTableEvidenceDo struct{ gen.DO }

func (b bidAnalysisV3DerivedTableEvidenceDo) Debug() *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3DerivedTableEvidenceDo) WithContext(ctx context.Context) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) ReadDB() *bidAnalysisV3DerivedTableEvidenceDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) WriteDB() *bidAnalysisV3DerivedTableEvidenceDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Session(config *gorm.Session) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Clauses(conds ...clause.Expression) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Returning(value interface{}, columns ...string) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Not(conds ...gen.Condition) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Or(conds ...gen.Condition) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Select(conds ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Where(conds ...gen.Condition) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Order(conds ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Distinct(cols ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Omit(cols ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Group(cols ...field.Expr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Having(conds ...gen.Condition) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Limit(limit int) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Offset(offset int) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Unscoped() *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Create(values ...*model.BidAnalysisV3DerivedTableEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) CreateInBatches(values []*model.BidAnalysisV3DerivedTableEvidence, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3DerivedTableEvidenceDo) Save(values ...*model.BidAnalysisV3DerivedTableEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) First() (*model.BidAnalysisV3DerivedTableEvidence, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DerivedTableEvidence), nil
	}
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Take() (*model.BidAnalysisV3DerivedTableEvidence, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DerivedTableEvidence), nil
	}
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Last() (*model.BidAnalysisV3DerivedTableEvidence, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DerivedTableEvidence), nil
	}
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Find() ([]*model.BidAnalysisV3DerivedTableEvidence, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3DerivedTableEvidence), err
}

func (b bidAnalysisV3DerivedTableEvidenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3DerivedTableEvidence, err error) {
	buf := make([]*model.BidAnalysisV3DerivedTableEvidence, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3DerivedTableEvidenceDo) FindInBatches(result *[]*model.BidAnalysisV3DerivedTableEvidence, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3DerivedTableEvidenceDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Joins(fields ...field.RelationField) *bidAnalysisV3DerivedTableEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Preload(fields ...field.RelationField) *bidAnalysisV3DerivedTableEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3DerivedTableEvidenceDo) FirstOrInit() (*model.BidAnalysisV3DerivedTableEvidence, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DerivedTableEvidence), nil
	}
}

func (b bidAnalysisV3DerivedTableEvidenceDo) FirstOrCreate() (*model.BidAnalysisV3DerivedTableEvidence, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DerivedTableEvidence), nil
	}
}

func (b bidAnalysisV3DerivedTableEvidenceDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3DerivedTableEvidence, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3DerivedTableEvidenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3DerivedTableEvidenceDo) Delete(models ...*model.BidAnalysisV3DerivedTableEvidence) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3DerivedTableEvidenceDo) withDO(do gen.Dao) *bidAnalysisV3DerivedTableEvidenceDo {
	b.DO = *do.(*gen.DO)
	return b
}
