// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidOutlineValue(db *gorm.DB, opts ...gen.DOOption) bidOutlineValue {
	_bidOutlineValue := bidOutlineValue{}

	_bidOutlineValue.bidOutlineValueDo.UseDB(db, opts...)
	_bidOutlineValue.bidOutlineValueDo.UseModel(&model.BidOutlineValue{})

	tableName := _bidOutlineValue.bidOutlineValueDo.TableName()
	_bidOutlineValue.ALL = field.NewAsterisk(tableName)
	_bidOutlineValue.ID = field.NewInt64(tableName, "id")
	_bidOutlineValue.ProjectID = field.NewInt64(tableName, "project_id")
	_bidOutlineValue.OutlineID = field.NewInt64(tableName, "outline_id")
	_bidOutlineValue.Content = field.NewString(tableName, "content")
	_bidOutlineValue.Status = field.NewBool(tableName, "status")
	_bidOutlineValue.LatestUserID = field.NewInt64(tableName, "latest_user_id")
	_bidOutlineValue.Source = field.NewString(tableName, "source")
	_bidOutlineValue.CreatedAt = field.NewTime(tableName, "created_at")
	_bidOutlineValue.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidOutlineValue.fillFieldMap()

	return _bidOutlineValue
}

type bidOutlineValue struct {
	bidOutlineValueDo bidOutlineValueDo

	ALL          field.Asterisk
	ID           field.Int64
	ProjectID    field.Int64  // 所属投标生成项目ID（bid_project.id）
	OutlineID    field.Int64  // 大纲标题ID
	Content      field.String // 对应标题的正文
	Status       field.Bool   // 是否已审核：1是，0否
	LatestUserID field.Int64  // 最近修改人用户ID
	Source       field.String // 数据来源,枚举：agent/user
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidOutlineValue) Table(newTableName string) *bidOutlineValue {
	b.bidOutlineValueDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidOutlineValue) As(alias string) *bidOutlineValue {
	b.bidOutlineValueDo.DO = *(b.bidOutlineValueDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidOutlineValue) updateTableName(table string) *bidOutlineValue {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.OutlineID = field.NewInt64(table, "outline_id")
	b.Content = field.NewString(table, "content")
	b.Status = field.NewBool(table, "status")
	b.LatestUserID = field.NewInt64(table, "latest_user_id")
	b.Source = field.NewString(table, "source")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidOutlineValue) WithContext(ctx context.Context) *bidOutlineValueDo {
	return b.bidOutlineValueDo.WithContext(ctx)
}

func (b bidOutlineValue) TableName() string { return b.bidOutlineValueDo.TableName() }

func (b bidOutlineValue) Alias() string { return b.bidOutlineValueDo.Alias() }

func (b *bidOutlineValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidOutlineValue) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 9)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["outline_id"] = b.OutlineID
	b.fieldMap["content"] = b.Content
	b.fieldMap["status"] = b.Status
	b.fieldMap["latest_user_id"] = b.LatestUserID
	b.fieldMap["source"] = b.Source
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidOutlineValue) clone(db *gorm.DB) bidOutlineValue {
	b.bidOutlineValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidOutlineValue) replaceDB(db *gorm.DB) bidOutlineValue {
	b.bidOutlineValueDo.ReplaceDB(db)
	return b
}

type bidOutlineValueDo struct{ gen.DO }

func (b bidOutlineValueDo) Debug() *bidOutlineValueDo {
	return b.withDO(b.DO.Debug())
}

func (b bidOutlineValueDo) WithContext(ctx context.Context) *bidOutlineValueDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidOutlineValueDo) ReadDB() *bidOutlineValueDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidOutlineValueDo) WriteDB() *bidOutlineValueDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidOutlineValueDo) Session(config *gorm.Session) *bidOutlineValueDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidOutlineValueDo) Clauses(conds ...clause.Expression) *bidOutlineValueDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidOutlineValueDo) Returning(value interface{}, columns ...string) *bidOutlineValueDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidOutlineValueDo) Not(conds ...gen.Condition) *bidOutlineValueDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidOutlineValueDo) Or(conds ...gen.Condition) *bidOutlineValueDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidOutlineValueDo) Select(conds ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidOutlineValueDo) Where(conds ...gen.Condition) *bidOutlineValueDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidOutlineValueDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidOutlineValueDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidOutlineValueDo) Order(conds ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidOutlineValueDo) Distinct(cols ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidOutlineValueDo) Omit(cols ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidOutlineValueDo) Join(table schema.Tabler, on ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidOutlineValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidOutlineValueDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidOutlineValueDo) Group(cols ...field.Expr) *bidOutlineValueDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidOutlineValueDo) Having(conds ...gen.Condition) *bidOutlineValueDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidOutlineValueDo) Limit(limit int) *bidOutlineValueDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidOutlineValueDo) Offset(offset int) *bidOutlineValueDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidOutlineValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidOutlineValueDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidOutlineValueDo) Unscoped() *bidOutlineValueDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidOutlineValueDo) Create(values ...*model.BidOutlineValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidOutlineValueDo) CreateInBatches(values []*model.BidOutlineValue, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidOutlineValueDo) Save(values ...*model.BidOutlineValue) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidOutlineValueDo) First() (*model.BidOutlineValue, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidOutlineValue), nil
	}
}

func (b bidOutlineValueDo) Take() (*model.BidOutlineValue, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidOutlineValue), nil
	}
}

func (b bidOutlineValueDo) Last() (*model.BidOutlineValue, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidOutlineValue), nil
	}
}

func (b bidOutlineValueDo) Find() ([]*model.BidOutlineValue, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidOutlineValue), err
}

func (b bidOutlineValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidOutlineValue, err error) {
	buf := make([]*model.BidOutlineValue, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidOutlineValueDo) FindInBatches(result *[]*model.BidOutlineValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidOutlineValueDo) Attrs(attrs ...field.AssignExpr) *bidOutlineValueDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidOutlineValueDo) Assign(attrs ...field.AssignExpr) *bidOutlineValueDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidOutlineValueDo) Joins(fields ...field.RelationField) *bidOutlineValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidOutlineValueDo) Preload(fields ...field.RelationField) *bidOutlineValueDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidOutlineValueDo) FirstOrInit() (*model.BidOutlineValue, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidOutlineValue), nil
	}
}

func (b bidOutlineValueDo) FirstOrCreate() (*model.BidOutlineValue, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidOutlineValue), nil
	}
}

func (b bidOutlineValueDo) FindByPage(offset int, limit int) (result []*model.BidOutlineValue, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidOutlineValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidOutlineValueDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidOutlineValueDo) Delete(models ...*model.BidOutlineValue) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidOutlineValueDo) withDO(do gen.Dao) *bidOutlineValueDo {
	b.DO = *do.(*gen.DO)
	return b
}
