// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3FieldValueEvidence(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3FieldValueEvidence {
	_bidAnalysisV3FieldValueEvidence := bidAnalysisV3FieldValueEvidence{}

	_bidAnalysisV3FieldValueEvidence.bidAnalysisV3FieldValueEvidenceDo.UseDB(db, opts...)
	_bidAnalysisV3FieldValueEvidence.bidAnalysisV3FieldValueEvidenceDo.UseModel(&model.BidAnalysisV3FieldValueEvidence{})

	tableName := _bidAnalysisV3FieldValueEvidence.bidAnalysisV3FieldValueEvidenceDo.TableName()
	_bidAnalysisV3FieldValueEvidence.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3FieldValueEvidence.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3FieldValueEvidence.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3FieldValueEvidence.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3FieldValueEvidence.FieldValueID = field.NewInt64(tableName, "field_value_id")
	_bidAnalysisV3FieldValueEvidence.SourceKind = field.NewString(tableName, "source_kind")
	_bidAnalysisV3FieldValueEvidence.BlockID = field.NewInt64(tableName, "block_id")
	_bidAnalysisV3FieldValueEvidence.SourceTableID = field.NewInt64(tableName, "source_table_id")
	_bidAnalysisV3FieldValueEvidence.PageNo = field.NewInt32(tableName, "page_no")
	_bidAnalysisV3FieldValueEvidence.Quote = field.NewString(tableName, "quote")
	_bidAnalysisV3FieldValueEvidence.BboxLeft = field.NewFloat64(tableName, "bbox_left")
	_bidAnalysisV3FieldValueEvidence.BboxTop = field.NewFloat64(tableName, "bbox_top")
	_bidAnalysisV3FieldValueEvidence.BboxWidth = field.NewFloat64(tableName, "bbox_width")
	_bidAnalysisV3FieldValueEvidence.BboxHeight = field.NewFloat64(tableName, "bbox_height")
	_bidAnalysisV3FieldValueEvidence.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidAnalysisV3FieldValueEvidence.ContentHash = field.NewString(tableName, "content_hash")
	_bidAnalysisV3FieldValueEvidence.CreatedBy = field.NewInt64(tableName, "created_by")
	_bidAnalysisV3FieldValueEvidence.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3FieldValueEvidence.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3FieldValueEvidence.fillFieldMap()

	return _bidAnalysisV3FieldValueEvidence
}

type bidAnalysisV3FieldValueEvidence struct {
	bidAnalysisV3FieldValueEvidenceDo bidAnalysisV3FieldValueEvidenceDo

	ALL           field.Asterisk
	ID            field.Int64   // 主键
	ProjectID     field.Int64   // 招标解析项目ID
	RunID         field.Int64   // 解析运行ID
	FieldValueID  field.Int64   // 字段值ID
	SourceKind    field.String  // text_block/source_table/manual_text/manual_table
	BlockID       field.Int64   // 文档文本块ID
	SourceTableID field.Int64   // 原文表格ID
	PageNo        field.Int32   // 全局页码
	Quote         field.String  // 证据原文摘要
	BboxLeft      field.Float64 // 归一化左侧坐标
	BboxTop       field.Float64 // 归一化顶部坐标
	BboxWidth     field.Float64 // 归一化区域宽度
	BboxHeight    field.Float64 // 归一化区域高度
	SortOrder     field.Int32   // 排序序号
	ContentHash   field.String  // 内容哈希
	CreatedBy     field.Int64   // 创建人ID
	CreatedAt     field.Time    // 创建时间
	UpdatedAt     field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3FieldValueEvidence) Table(newTableName string) *bidAnalysisV3FieldValueEvidence {
	b.bidAnalysisV3FieldValueEvidenceDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3FieldValueEvidence) As(alias string) *bidAnalysisV3FieldValueEvidence {
	b.bidAnalysisV3FieldValueEvidenceDo.DO = *(b.bidAnalysisV3FieldValueEvidenceDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3FieldValueEvidence) updateTableName(table string) *bidAnalysisV3FieldValueEvidence {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.FieldValueID = field.NewInt64(table, "field_value_id")
	b.SourceKind = field.NewString(table, "source_kind")
	b.BlockID = field.NewInt64(table, "block_id")
	b.SourceTableID = field.NewInt64(table, "source_table_id")
	b.PageNo = field.NewInt32(table, "page_no")
	b.Quote = field.NewString(table, "quote")
	b.BboxLeft = field.NewFloat64(table, "bbox_left")
	b.BboxTop = field.NewFloat64(table, "bbox_top")
	b.BboxWidth = field.NewFloat64(table, "bbox_width")
	b.BboxHeight = field.NewFloat64(table, "bbox_height")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.ContentHash = field.NewString(table, "content_hash")
	b.CreatedBy = field.NewInt64(table, "created_by")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3FieldValueEvidence) WithContext(ctx context.Context) *bidAnalysisV3FieldValueEvidenceDo {
	return b.bidAnalysisV3FieldValueEvidenceDo.WithContext(ctx)
}

func (b bidAnalysisV3FieldValueEvidence) TableName() string {
	return b.bidAnalysisV3FieldValueEvidenceDo.TableName()
}

func (b bidAnalysisV3FieldValueEvidence) Alias() string {
	return b.bidAnalysisV3FieldValueEvidenceDo.Alias()
}

func (b *bidAnalysisV3FieldValueEvidence) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3FieldValueEvidence) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 18)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["field_value_id"] = b.FieldValueID
	b.fieldMap["source_kind"] = b.SourceKind
	b.fieldMap["block_id"] = b.BlockID
	b.fieldMap["source_table_id"] = b.SourceTableID
	b.fieldMap["page_no"] = b.PageNo
	b.fieldMap["quote"] = b.Quote
	b.fieldMap["bbox_left"] = b.BboxLeft
	b.fieldMap["bbox_top"] = b.BboxTop
	b.fieldMap["bbox_width"] = b.BboxWidth
	b.fieldMap["bbox_height"] = b.BboxHeight
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["content_hash"] = b.ContentHash
	b.fieldMap["created_by"] = b.CreatedBy
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3FieldValueEvidence) clone(db *gorm.DB) bidAnalysisV3FieldValueEvidence {
	b.bidAnalysisV3FieldValueEvidenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3FieldValueEvidence) replaceDB(db *gorm.DB) bidAnalysisV3FieldValueEvidence {
	b.bidAnalysisV3FieldValueEvidenceDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3FieldValueEvidenceDo struct{ gen.DO }

func (b bidAnalysisV3FieldValueEvidenceDo) Debug() *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3FieldValueEvidenceDo) WithContext(ctx context.Context) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3FieldValueEvidenceDo) ReadDB() *bidAnalysisV3FieldValueEvidenceDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3FieldValueEvidenceDo) WriteDB() *bidAnalysisV3FieldValueEvidenceDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3FieldValueEvidenceDo) Session(config *gorm.Session) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Clauses(conds ...clause.Expression) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Returning(value interface{}, columns ...string) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Not(conds ...gen.Condition) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Or(conds ...gen.Condition) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Select(conds ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Where(conds ...gen.Condition) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3FieldValueEvidenceDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Order(conds ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Distinct(cols ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Omit(cols ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Group(cols ...field.Expr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Having(conds ...gen.Condition) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Limit(limit int) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Offset(offset int) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Unscoped() *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3FieldValueEvidenceDo) Create(values ...*model.BidAnalysisV3FieldValueEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3FieldValueEvidenceDo) CreateInBatches(values []*model.BidAnalysisV3FieldValueEvidence, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3FieldValueEvidenceDo) Save(values ...*model.BidAnalysisV3FieldValueEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3FieldValueEvidenceDo) First() (*model.BidAnalysisV3FieldValueEvidence, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3FieldValueEvidence), nil
	}
}

func (b bidAnalysisV3FieldValueEvidenceDo) Take() (*model.BidAnalysisV3FieldValueEvidence, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3FieldValueEvidence), nil
	}
}

func (b bidAnalysisV3FieldValueEvidenceDo) Last() (*model.BidAnalysisV3FieldValueEvidence, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3FieldValueEvidence), nil
	}
}

func (b bidAnalysisV3FieldValueEvidenceDo) Find() ([]*model.BidAnalysisV3FieldValueEvidence, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3FieldValueEvidence), err
}

func (b bidAnalysisV3FieldValueEvidenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3FieldValueEvidence, err error) {
	buf := make([]*model.BidAnalysisV3FieldValueEvidence, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3FieldValueEvidenceDo) FindInBatches(result *[]*model.BidAnalysisV3FieldValueEvidence, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3FieldValueEvidenceDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3FieldValueEvidenceDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3FieldValueEvidenceDo) Joins(fields ...field.RelationField) *bidAnalysisV3FieldValueEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3FieldValueEvidenceDo) Preload(fields ...field.RelationField) *bidAnalysisV3FieldValueEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3FieldValueEvidenceDo) FirstOrInit() (*model.BidAnalysisV3FieldValueEvidence, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3FieldValueEvidence), nil
	}
}

func (b bidAnalysisV3FieldValueEvidenceDo) FirstOrCreate() (*model.BidAnalysisV3FieldValueEvidence, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3FieldValueEvidence), nil
	}
}

func (b bidAnalysisV3FieldValueEvidenceDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3FieldValueEvidence, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3FieldValueEvidenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3FieldValueEvidenceDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3FieldValueEvidenceDo) Delete(models ...*model.BidAnalysisV3FieldValueEvidence) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3FieldValueEvidenceDo) withDO(do gen.Dao) *bidAnalysisV3FieldValueEvidenceDo {
	b.DO = *do.(*gen.DO)
	return b
}
