// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidGenProject(db *gorm.DB, opts ...gen.DOOption) bidGenProject {
	_bidGenProject := bidGenProject{}

	_bidGenProject.bidGenProjectDo.UseDB(db, opts...)
	_bidGenProject.bidGenProjectDo.UseModel(&model.BidGenProject{})

	tableName := _bidGenProject.bidGenProjectDo.TableName()
	_bidGenProject.ALL = field.NewAsterisk(tableName)
	_bidGenProject.ID = field.NewInt64(tableName, "id")
	_bidGenProject.Name = field.NewString(tableName, "name")
	_bidGenProject.CreateType = field.NewString(tableName, "create_type")
	_bidGenProject.TenderProjectID = field.NewInt64(tableName, "tender_project_id")
	_bidGenProject.BlueprintGenerationID = field.NewInt64(tableName, "blueprint_generation_id")
	_bidGenProject.TemplateMaterialID = field.NewInt64(tableName, "template_material_id")
	_bidGenProject.Status = field.NewString(tableName, "status")
	_bidGenProject.SourceFileBucket = field.NewString(tableName, "source_file_bucket")
	_bidGenProject.SourceFileName = field.NewString(tableName, "source_file_name")
	_bidGenProject.SourceFileObject = field.NewString(tableName, "source_file_object")
	_bidGenProject.SourceFileURL = field.NewString(tableName, "source_file_url")
	_bidGenProject.ReviewProjectID = field.NewInt64(tableName, "review_project_id")
	_bidGenProject.UserID = field.NewInt64(tableName, "user_id")
	_bidGenProject.UserTeamID = field.NewInt32(tableName, "user_team_id")
	_bidGenProject.UserCompanyID = field.NewInt32(tableName, "user_company_id")
	_bidGenProject.CreatedAt = field.NewTime(tableName, "created_at")
	_bidGenProject.UpdatedAt = field.NewTime(tableName, "updated_at")
	_bidGenProject.DeletedAt = field.NewField(tableName, "deleted_at")
	_bidGenProject.Progress = field.NewInt32(tableName, "progress")
	_bidGenProject.Stage = field.NewString(tableName, "stage")
	_bidGenProject.StageStatus = field.NewString(tableName, "stage_status")
	_bidGenProject.LastError = field.NewString(tableName, "last_error")

	_bidGenProject.fillFieldMap()

	return _bidGenProject
}

type bidGenProject struct {
	bidGenProjectDo bidGenProjectDo

	ALL                   field.Asterisk
	ID                    field.Int64
	Name                  field.String // 项目名称
	CreateType            field.String // 创建模式：tender_file-从招标文件创建，template-从模板创建，blank-空白标书
	TenderProjectID       field.Int64  // 招标解析 V3 项目 ID
	BlueprintGenerationID field.Int64  // 来源标书蓝图生成ID
	TemplateMaterialID    field.Int64  // 关联素材模板ID（material_template.id），create_type=template时使用
	Status                field.String // 项目状态：parsing-解析中，draft-草稿，generating-生成中，succeeded-已完成，failed-失败
	SourceFileBucket      field.String // 源文件存储桶名（从招标文件/模板创建时）
	SourceFileName        field.String // 源文件原始文件名
	SourceFileObject      field.String // 源文件对象键（OSS）
	SourceFileURL         field.String // 源文件访问URL
	ReviewProjectID       field.Int64  // 已生成的审核项目ID（0=未生成）
	UserID                field.Int64  // 创建用户ID
	UserTeamID            field.Int32  // 团队ID
	UserCompanyID         field.Int32  // 公司ID
	CreatedAt             field.Time   // 创建时间
	UpdatedAt             field.Time   // 更新时间
	DeletedAt             field.Field  // 软删除时间
	Progress              field.Int32  // 解析进度 0-100
	Stage                 field.String // 当前执行阶段
	StageStatus           field.String // 阶段状态JSON
	LastError             field.String // 最近一次错误信息

	fieldMap map[string]field.Expr
}

func (b bidGenProject) Table(newTableName string) *bidGenProject {
	b.bidGenProjectDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidGenProject) As(alias string) *bidGenProject {
	b.bidGenProjectDo.DO = *(b.bidGenProjectDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidGenProject) updateTableName(table string) *bidGenProject {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Name = field.NewString(table, "name")
	b.CreateType = field.NewString(table, "create_type")
	b.TenderProjectID = field.NewInt64(table, "tender_project_id")
	b.BlueprintGenerationID = field.NewInt64(table, "blueprint_generation_id")
	b.TemplateMaterialID = field.NewInt64(table, "template_material_id")
	b.Status = field.NewString(table, "status")
	b.SourceFileBucket = field.NewString(table, "source_file_bucket")
	b.SourceFileName = field.NewString(table, "source_file_name")
	b.SourceFileObject = field.NewString(table, "source_file_object")
	b.SourceFileURL = field.NewString(table, "source_file_url")
	b.ReviewProjectID = field.NewInt64(table, "review_project_id")
	b.UserID = field.NewInt64(table, "user_id")
	b.UserTeamID = field.NewInt32(table, "user_team_id")
	b.UserCompanyID = field.NewInt32(table, "user_company_id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.DeletedAt = field.NewField(table, "deleted_at")
	b.Progress = field.NewInt32(table, "progress")
	b.Stage = field.NewString(table, "stage")
	b.StageStatus = field.NewString(table, "stage_status")
	b.LastError = field.NewString(table, "last_error")

	b.fillFieldMap()

	return b
}

func (b *bidGenProject) WithContext(ctx context.Context) *bidGenProjectDo {
	return b.bidGenProjectDo.WithContext(ctx)
}

func (b bidGenProject) TableName() string { return b.bidGenProjectDo.TableName() }

func (b bidGenProject) Alias() string { return b.bidGenProjectDo.Alias() }

func (b *bidGenProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidGenProject) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 22)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["create_type"] = b.CreateType
	b.fieldMap["tender_project_id"] = b.TenderProjectID
	b.fieldMap["blueprint_generation_id"] = b.BlueprintGenerationID
	b.fieldMap["template_material_id"] = b.TemplateMaterialID
	b.fieldMap["status"] = b.Status
	b.fieldMap["source_file_bucket"] = b.SourceFileBucket
	b.fieldMap["source_file_name"] = b.SourceFileName
	b.fieldMap["source_file_object"] = b.SourceFileObject
	b.fieldMap["source_file_url"] = b.SourceFileURL
	b.fieldMap["review_project_id"] = b.ReviewProjectID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["user_team_id"] = b.UserTeamID
	b.fieldMap["user_company_id"] = b.UserCompanyID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["deleted_at"] = b.DeletedAt
	b.fieldMap["progress"] = b.Progress
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["stage_status"] = b.StageStatus
	b.fieldMap["last_error"] = b.LastError
}

func (b bidGenProject) clone(db *gorm.DB) bidGenProject {
	b.bidGenProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidGenProject) replaceDB(db *gorm.DB) bidGenProject {
	b.bidGenProjectDo.ReplaceDB(db)
	return b
}

type bidGenProjectDo struct{ gen.DO }

func (b bidGenProjectDo) Debug() *bidGenProjectDo {
	return b.withDO(b.DO.Debug())
}

func (b bidGenProjectDo) WithContext(ctx context.Context) *bidGenProjectDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidGenProjectDo) ReadDB() *bidGenProjectDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidGenProjectDo) WriteDB() *bidGenProjectDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidGenProjectDo) Session(config *gorm.Session) *bidGenProjectDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidGenProjectDo) Clauses(conds ...clause.Expression) *bidGenProjectDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidGenProjectDo) Returning(value interface{}, columns ...string) *bidGenProjectDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidGenProjectDo) Not(conds ...gen.Condition) *bidGenProjectDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidGenProjectDo) Or(conds ...gen.Condition) *bidGenProjectDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidGenProjectDo) Select(conds ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidGenProjectDo) Where(conds ...gen.Condition) *bidGenProjectDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidGenProjectDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidGenProjectDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidGenProjectDo) Order(conds ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidGenProjectDo) Distinct(cols ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidGenProjectDo) Omit(cols ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidGenProjectDo) Join(table schema.Tabler, on ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidGenProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidGenProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidGenProjectDo) Group(cols ...field.Expr) *bidGenProjectDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidGenProjectDo) Having(conds ...gen.Condition) *bidGenProjectDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidGenProjectDo) Limit(limit int) *bidGenProjectDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidGenProjectDo) Offset(offset int) *bidGenProjectDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidGenProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidGenProjectDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidGenProjectDo) Unscoped() *bidGenProjectDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidGenProjectDo) Create(values ...*model.BidGenProject) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidGenProjectDo) CreateInBatches(values []*model.BidGenProject, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidGenProjectDo) Save(values ...*model.BidGenProject) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidGenProjectDo) First() (*model.BidGenProject, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenProject), nil
	}
}

func (b bidGenProjectDo) Take() (*model.BidGenProject, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenProject), nil
	}
}

func (b bidGenProjectDo) Last() (*model.BidGenProject, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenProject), nil
	}
}

func (b bidGenProjectDo) Find() ([]*model.BidGenProject, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidGenProject), err
}

func (b bidGenProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidGenProject, err error) {
	buf := make([]*model.BidGenProject, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidGenProjectDo) FindInBatches(result *[]*model.BidGenProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidGenProjectDo) Attrs(attrs ...field.AssignExpr) *bidGenProjectDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidGenProjectDo) Assign(attrs ...field.AssignExpr) *bidGenProjectDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidGenProjectDo) Joins(fields ...field.RelationField) *bidGenProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidGenProjectDo) Preload(fields ...field.RelationField) *bidGenProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidGenProjectDo) FirstOrInit() (*model.BidGenProject, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenProject), nil
	}
}

func (b bidGenProjectDo) FirstOrCreate() (*model.BidGenProject, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenProject), nil
	}
}

func (b bidGenProjectDo) FindByPage(offset int, limit int) (result []*model.BidGenProject, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidGenProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidGenProjectDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidGenProjectDo) Delete(models ...*model.BidGenProject) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidGenProjectDo) withDO(do gen.Dao) *bidGenProjectDo {
	b.DO = *do.(*gen.DO)
	return b
}
