// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidGenOutline(db *gorm.DB, opts ...gen.DOOption) bidGenOutline {
	_bidGenOutline := bidGenOutline{}

	_bidGenOutline.bidGenOutlineDo.UseDB(db, opts...)
	_bidGenOutline.bidGenOutlineDo.UseModel(&model.BidGenOutline{})

	tableName := _bidGenOutline.bidGenOutlineDo.TableName()
	_bidGenOutline.ALL = field.NewAsterisk(tableName)
	_bidGenOutline.ID = field.NewInt64(tableName, "id")
	_bidGenOutline.ProjectID = field.NewInt64(tableName, "project_id")
	_bidGenOutline.ParentID = field.NewInt64(tableName, "parent_id")
	_bidGenOutline.Level = field.NewInt32(tableName, "level")
	_bidGenOutline.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidGenOutline.Title = field.NewString(tableName, "title")
	_bidGenOutline.ClauseIds = field.NewString(tableName, "clause_ids")
	_bidGenOutline.MaterialIds = field.NewString(tableName, "material_ids")
	_bidGenOutline.GenStatus = field.NewString(tableName, "gen_status")
	_bidGenOutline.Source = field.NewString(tableName, "source")
	_bidGenOutline.IsRequiredFile = field.NewBool(tableName, "is_required_file")
	_bidGenOutline.IsAiSuggested = field.NewBool(tableName, "is_ai_suggested")
	_bidGenOutline.CreatedAt = field.NewTime(tableName, "created_at")
	_bidGenOutline.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidGenOutline.fillFieldMap()

	return _bidGenOutline
}

type bidGenOutline struct {
	bidGenOutlineDo bidGenOutlineDo

	ALL            field.Asterisk
	ID             field.Int64
	ProjectID      field.Int64  // 所属项目ID（bid_gen_project.id）
	ParentID       field.Int64  // 父节点ID（自关联bid_gen_outline.id）；0表示顶层
	Level          field.Int32  // 标题层级：1-4
	SortOrder      field.Int32  // 同级内排序号，数值越小越靠前
	Title          field.String // 标题名称
	ClauseIds      field.String // 关联条款ID列表（JSON array，来自招标解析的条款）
	MaterialIds    field.String // 推荐素材ID列表（JSON array，来自蓝图的素材推荐）
	GenStatus      field.String // 生成状态：pending-待生成，generating-生成中，succeeded-已完成，failed-失败
	Source         field.String // 数据来源：ai-AI提取/建议，user-用户手动添加，system_root-系统文档根
	IsRequiredFile field.Bool   // 是否必须包含的文件节点：1是，0否
	IsAiSuggested  field.Bool   // 是否AI建议补充节点（基于行业最佳实践）：1是，0否
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidGenOutline) Table(newTableName string) *bidGenOutline {
	b.bidGenOutlineDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidGenOutline) As(alias string) *bidGenOutline {
	b.bidGenOutlineDo.DO = *(b.bidGenOutlineDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidGenOutline) updateTableName(table string) *bidGenOutline {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.ParentID = field.NewInt64(table, "parent_id")
	b.Level = field.NewInt32(table, "level")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.Title = field.NewString(table, "title")
	b.ClauseIds = field.NewString(table, "clause_ids")
	b.MaterialIds = field.NewString(table, "material_ids")
	b.GenStatus = field.NewString(table, "gen_status")
	b.Source = field.NewString(table, "source")
	b.IsRequiredFile = field.NewBool(table, "is_required_file")
	b.IsAiSuggested = field.NewBool(table, "is_ai_suggested")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidGenOutline) WithContext(ctx context.Context) *bidGenOutlineDo {
	return b.bidGenOutlineDo.WithContext(ctx)
}

func (b bidGenOutline) TableName() string { return b.bidGenOutlineDo.TableName() }

func (b bidGenOutline) Alias() string { return b.bidGenOutlineDo.Alias() }

func (b *bidGenOutline) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidGenOutline) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 14)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["parent_id"] = b.ParentID
	b.fieldMap["level"] = b.Level
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["title"] = b.Title
	b.fieldMap["clause_ids"] = b.ClauseIds
	b.fieldMap["material_ids"] = b.MaterialIds
	b.fieldMap["gen_status"] = b.GenStatus
	b.fieldMap["source"] = b.Source
	b.fieldMap["is_required_file"] = b.IsRequiredFile
	b.fieldMap["is_ai_suggested"] = b.IsAiSuggested
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidGenOutline) clone(db *gorm.DB) bidGenOutline {
	b.bidGenOutlineDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidGenOutline) replaceDB(db *gorm.DB) bidGenOutline {
	b.bidGenOutlineDo.ReplaceDB(db)
	return b
}

type bidGenOutlineDo struct{ gen.DO }

func (b bidGenOutlineDo) Debug() *bidGenOutlineDo {
	return b.withDO(b.DO.Debug())
}

func (b bidGenOutlineDo) WithContext(ctx context.Context) *bidGenOutlineDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidGenOutlineDo) ReadDB() *bidGenOutlineDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidGenOutlineDo) WriteDB() *bidGenOutlineDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidGenOutlineDo) Session(config *gorm.Session) *bidGenOutlineDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidGenOutlineDo) Clauses(conds ...clause.Expression) *bidGenOutlineDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidGenOutlineDo) Returning(value interface{}, columns ...string) *bidGenOutlineDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidGenOutlineDo) Not(conds ...gen.Condition) *bidGenOutlineDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidGenOutlineDo) Or(conds ...gen.Condition) *bidGenOutlineDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidGenOutlineDo) Select(conds ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidGenOutlineDo) Where(conds ...gen.Condition) *bidGenOutlineDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidGenOutlineDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidGenOutlineDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidGenOutlineDo) Order(conds ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidGenOutlineDo) Distinct(cols ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidGenOutlineDo) Omit(cols ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidGenOutlineDo) Join(table schema.Tabler, on ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidGenOutlineDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidGenOutlineDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidGenOutlineDo) Group(cols ...field.Expr) *bidGenOutlineDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidGenOutlineDo) Having(conds ...gen.Condition) *bidGenOutlineDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidGenOutlineDo) Limit(limit int) *bidGenOutlineDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidGenOutlineDo) Offset(offset int) *bidGenOutlineDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidGenOutlineDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidGenOutlineDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidGenOutlineDo) Unscoped() *bidGenOutlineDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidGenOutlineDo) Create(values ...*model.BidGenOutline) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidGenOutlineDo) CreateInBatches(values []*model.BidGenOutline, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidGenOutlineDo) Save(values ...*model.BidGenOutline) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidGenOutlineDo) First() (*model.BidGenOutline, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenOutline), nil
	}
}

func (b bidGenOutlineDo) Take() (*model.BidGenOutline, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenOutline), nil
	}
}

func (b bidGenOutlineDo) Last() (*model.BidGenOutline, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenOutline), nil
	}
}

func (b bidGenOutlineDo) Find() ([]*model.BidGenOutline, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidGenOutline), err
}

func (b bidGenOutlineDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidGenOutline, err error) {
	buf := make([]*model.BidGenOutline, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidGenOutlineDo) FindInBatches(result *[]*model.BidGenOutline, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidGenOutlineDo) Attrs(attrs ...field.AssignExpr) *bidGenOutlineDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidGenOutlineDo) Assign(attrs ...field.AssignExpr) *bidGenOutlineDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidGenOutlineDo) Joins(fields ...field.RelationField) *bidGenOutlineDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidGenOutlineDo) Preload(fields ...field.RelationField) *bidGenOutlineDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidGenOutlineDo) FirstOrInit() (*model.BidGenOutline, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenOutline), nil
	}
}

func (b bidGenOutlineDo) FirstOrCreate() (*model.BidGenOutline, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenOutline), nil
	}
}

func (b bidGenOutlineDo) FindByPage(offset int, limit int) (result []*model.BidGenOutline, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidGenOutlineDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidGenOutlineDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidGenOutlineDo) Delete(models ...*model.BidGenOutline) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidGenOutlineDo) withDO(do gen.Dao) *bidGenOutlineDo {
	b.DO = *do.(*gen.DO)
	return b
}
