// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidGenTask(db *gorm.DB, opts ...gen.DOOption) bidGenTask {
	_bidGenTask := bidGenTask{}

	_bidGenTask.bidGenTaskDo.UseDB(db, opts...)
	_bidGenTask.bidGenTaskDo.UseModel(&model.BidGenTask{})

	tableName := _bidGenTask.bidGenTaskDo.TableName()
	_bidGenTask.ALL = field.NewAsterisk(tableName)
	_bidGenTask.ID = field.NewInt64(tableName, "id")
	_bidGenTask.QueueTaskID = field.NewString(tableName, "queue_task_id")
	_bidGenTask.ProjectID = field.NewInt64(tableName, "project_id")
	_bidGenTask.TaskType = field.NewString(tableName, "task_type")
	_bidGenTask.OutlineIds = field.NewString(tableName, "outline_ids")
	_bidGenTask.LengthTier = field.NewString(tableName, "length_tier")
	_bidGenTask.GenMode = field.NewString(tableName, "gen_mode")
	_bidGenTask.Instruction = field.NewString(tableName, "instruction")
	_bidGenTask.Status = field.NewString(tableName, "status")
	_bidGenTask.Progress = field.NewInt32(tableName, "progress")
	_bidGenTask.CurrentOutlineID = field.NewInt64(tableName, "current_outline_id")
	_bidGenTask.CompletedCount = field.NewInt32(tableName, "completed_count")
	_bidGenTask.TotalCount = field.NewInt32(tableName, "total_count")
	_bidGenTask.ErrorMsg = field.NewString(tableName, "error_msg")
	_bidGenTask.AttemptCount = field.NewInt32(tableName, "attempt_count")
	_bidGenTask.UserID = field.NewInt64(tableName, "user_id")
	_bidGenTask.StartedAt = field.NewTime(tableName, "started_at")
	_bidGenTask.HeartbeatAt = field.NewTime(tableName, "heartbeat_at")
	_bidGenTask.CancelRequestedAt = field.NewTime(tableName, "cancel_requested_at")
	_bidGenTask.FinishedAt = field.NewTime(tableName, "finished_at")
	_bidGenTask.CreatedAt = field.NewTime(tableName, "created_at")
	_bidGenTask.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidGenTask.fillFieldMap()

	return _bidGenTask
}

type bidGenTask struct {
	bidGenTaskDo bidGenTaskDo

	ALL               field.Asterisk
	ID                field.Int64
	QueueTaskID       field.String // Redis队列任务ID
	ProjectID         field.Int64  // 所属项目ID（bid_gen_project.id）
	TaskType          field.String // 任务类型：full-整篇生成，chapter-指定章节生成，parse-解析招标文件/模板
	OutlineIds        field.String // 目标大纲节点ID列表（JSON array，task_type=chapter时）
	LengthTier        field.String // 篇幅档位
	GenMode           field.String // 生成模式
	Instruction       field.String // 补充生成要求
	Status            field.String // 任务状态：pending-排队，running-执行中，cancelling-停止中，succeeded-完成，failed-失败，cancelled-已取消
	Progress          field.Int32  // 生成进度：0-100
	CurrentOutlineID  field.Int64  // 当前正在生成的大纲节点ID
	CompletedCount    field.Int32  // 已完成章节数
	TotalCount        field.Int32  // 目标总章节数
	ErrorMsg          field.String // 错误信息
	AttemptCount      field.Int32  // 实际执行次数
	UserID            field.Int64  // 触发用户ID
	StartedAt         field.Time   // 开始时间
	HeartbeatAt       field.Time   // 业务任务心跳时间
	CancelRequestedAt field.Time   // 取消请求时间
	FinishedAt        field.Time   // 完成时间
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidGenTask) Table(newTableName string) *bidGenTask {
	b.bidGenTaskDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidGenTask) As(alias string) *bidGenTask {
	b.bidGenTaskDo.DO = *(b.bidGenTaskDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidGenTask) updateTableName(table string) *bidGenTask {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.QueueTaskID = field.NewString(table, "queue_task_id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.TaskType = field.NewString(table, "task_type")
	b.OutlineIds = field.NewString(table, "outline_ids")
	b.LengthTier = field.NewString(table, "length_tier")
	b.GenMode = field.NewString(table, "gen_mode")
	b.Instruction = field.NewString(table, "instruction")
	b.Status = field.NewString(table, "status")
	b.Progress = field.NewInt32(table, "progress")
	b.CurrentOutlineID = field.NewInt64(table, "current_outline_id")
	b.CompletedCount = field.NewInt32(table, "completed_count")
	b.TotalCount = field.NewInt32(table, "total_count")
	b.ErrorMsg = field.NewString(table, "error_msg")
	b.AttemptCount = field.NewInt32(table, "attempt_count")
	b.UserID = field.NewInt64(table, "user_id")
	b.StartedAt = field.NewTime(table, "started_at")
	b.HeartbeatAt = field.NewTime(table, "heartbeat_at")
	b.CancelRequestedAt = field.NewTime(table, "cancel_requested_at")
	b.FinishedAt = field.NewTime(table, "finished_at")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidGenTask) WithContext(ctx context.Context) *bidGenTaskDo {
	return b.bidGenTaskDo.WithContext(ctx)
}

func (b bidGenTask) TableName() string { return b.bidGenTaskDo.TableName() }

func (b bidGenTask) Alias() string { return b.bidGenTaskDo.Alias() }

func (b *bidGenTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidGenTask) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 22)
	b.fieldMap["id"] = b.ID
	b.fieldMap["queue_task_id"] = b.QueueTaskID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["task_type"] = b.TaskType
	b.fieldMap["outline_ids"] = b.OutlineIds
	b.fieldMap["length_tier"] = b.LengthTier
	b.fieldMap["gen_mode"] = b.GenMode
	b.fieldMap["instruction"] = b.Instruction
	b.fieldMap["status"] = b.Status
	b.fieldMap["progress"] = b.Progress
	b.fieldMap["current_outline_id"] = b.CurrentOutlineID
	b.fieldMap["completed_count"] = b.CompletedCount
	b.fieldMap["total_count"] = b.TotalCount
	b.fieldMap["error_msg"] = b.ErrorMsg
	b.fieldMap["attempt_count"] = b.AttemptCount
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["started_at"] = b.StartedAt
	b.fieldMap["heartbeat_at"] = b.HeartbeatAt
	b.fieldMap["cancel_requested_at"] = b.CancelRequestedAt
	b.fieldMap["finished_at"] = b.FinishedAt
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidGenTask) clone(db *gorm.DB) bidGenTask {
	b.bidGenTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidGenTask) replaceDB(db *gorm.DB) bidGenTask {
	b.bidGenTaskDo.ReplaceDB(db)
	return b
}

type bidGenTaskDo struct{ gen.DO }

func (b bidGenTaskDo) Debug() *bidGenTaskDo {
	return b.withDO(b.DO.Debug())
}

func (b bidGenTaskDo) WithContext(ctx context.Context) *bidGenTaskDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidGenTaskDo) ReadDB() *bidGenTaskDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidGenTaskDo) WriteDB() *bidGenTaskDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidGenTaskDo) Session(config *gorm.Session) *bidGenTaskDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidGenTaskDo) Clauses(conds ...clause.Expression) *bidGenTaskDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidGenTaskDo) Returning(value interface{}, columns ...string) *bidGenTaskDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidGenTaskDo) Not(conds ...gen.Condition) *bidGenTaskDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidGenTaskDo) Or(conds ...gen.Condition) *bidGenTaskDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidGenTaskDo) Select(conds ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidGenTaskDo) Where(conds ...gen.Condition) *bidGenTaskDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidGenTaskDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidGenTaskDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidGenTaskDo) Order(conds ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidGenTaskDo) Distinct(cols ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidGenTaskDo) Omit(cols ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidGenTaskDo) Join(table schema.Tabler, on ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidGenTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidGenTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidGenTaskDo) Group(cols ...field.Expr) *bidGenTaskDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidGenTaskDo) Having(conds ...gen.Condition) *bidGenTaskDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidGenTaskDo) Limit(limit int) *bidGenTaskDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidGenTaskDo) Offset(offset int) *bidGenTaskDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidGenTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidGenTaskDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidGenTaskDo) Unscoped() *bidGenTaskDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidGenTaskDo) Create(values ...*model.BidGenTask) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidGenTaskDo) CreateInBatches(values []*model.BidGenTask, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidGenTaskDo) Save(values ...*model.BidGenTask) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidGenTaskDo) First() (*model.BidGenTask, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenTask), nil
	}
}

func (b bidGenTaskDo) Take() (*model.BidGenTask, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenTask), nil
	}
}

func (b bidGenTaskDo) Last() (*model.BidGenTask, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenTask), nil
	}
}

func (b bidGenTaskDo) Find() ([]*model.BidGenTask, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidGenTask), err
}

func (b bidGenTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidGenTask, err error) {
	buf := make([]*model.BidGenTask, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidGenTaskDo) FindInBatches(result *[]*model.BidGenTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidGenTaskDo) Attrs(attrs ...field.AssignExpr) *bidGenTaskDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidGenTaskDo) Assign(attrs ...field.AssignExpr) *bidGenTaskDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidGenTaskDo) Joins(fields ...field.RelationField) *bidGenTaskDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidGenTaskDo) Preload(fields ...field.RelationField) *bidGenTaskDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidGenTaskDo) FirstOrInit() (*model.BidGenTask, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenTask), nil
	}
}

func (b bidGenTaskDo) FirstOrCreate() (*model.BidGenTask, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenTask), nil
	}
}

func (b bidGenTaskDo) FindByPage(offset int, limit int) (result []*model.BidGenTask, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidGenTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidGenTaskDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidGenTaskDo) Delete(models ...*model.BidGenTask) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidGenTaskDo) withDO(do gen.Dao) *bidGenTaskDo {
	b.DO = *do.(*gen.DO)
	return b
}
