// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3DocumentAsset(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3DocumentAsset {
	_bidAnalysisV3DocumentAsset := bidAnalysisV3DocumentAsset{}

	_bidAnalysisV3DocumentAsset.bidAnalysisV3DocumentAssetDo.UseDB(db, opts...)
	_bidAnalysisV3DocumentAsset.bidAnalysisV3DocumentAssetDo.UseModel(&model.BidAnalysisV3DocumentAsset{})

	tableName := _bidAnalysisV3DocumentAsset.bidAnalysisV3DocumentAssetDo.TableName()
	_bidAnalysisV3DocumentAsset.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3DocumentAsset.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3DocumentAsset.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3DocumentAsset.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3DocumentAsset.AssetType = field.NewString(tableName, "asset_type")
	_bidAnalysisV3DocumentAsset.Bucket = field.NewString(tableName, "bucket")
	_bidAnalysisV3DocumentAsset.ObjectKey = field.NewString(tableName, "object_key")
	_bidAnalysisV3DocumentAsset.FileName = field.NewString(tableName, "file_name")
	_bidAnalysisV3DocumentAsset.MimeType = field.NewString(tableName, "mime_type")
	_bidAnalysisV3DocumentAsset.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_bidAnalysisV3DocumentAsset.Sha256 = field.NewString(tableName, "sha256")
	_bidAnalysisV3DocumentAsset.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3DocumentAsset.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3DocumentAsset.fillFieldMap()

	return _bidAnalysisV3DocumentAsset
}

type bidAnalysisV3DocumentAsset struct {
	bidAnalysisV3DocumentAssetDo bidAnalysisV3DocumentAssetDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	ProjectID field.Int64  // 招标解析项目ID
	RunID     field.Int64  // 解析运行ID
	AssetType field.String // source/normalized_pdf/chunk_pdf/docling_json/export
	Bucket    field.String // 对象存储桶名
	ObjectKey field.String // 对象存储键
	FileName  field.String // 文件名
	MimeType  field.String // 文件MIME类型
	SizeBytes field.Int64  // 文件大小（字节）
	Sha256    field.String // 文件SHA256
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3DocumentAsset) Table(newTableName string) *bidAnalysisV3DocumentAsset {
	b.bidAnalysisV3DocumentAssetDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3DocumentAsset) As(alias string) *bidAnalysisV3DocumentAsset {
	b.bidAnalysisV3DocumentAssetDo.DO = *(b.bidAnalysisV3DocumentAssetDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3DocumentAsset) updateTableName(table string) *bidAnalysisV3DocumentAsset {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.AssetType = field.NewString(table, "asset_type")
	b.Bucket = field.NewString(table, "bucket")
	b.ObjectKey = field.NewString(table, "object_key")
	b.FileName = field.NewString(table, "file_name")
	b.MimeType = field.NewString(table, "mime_type")
	b.SizeBytes = field.NewInt64(table, "size_bytes")
	b.Sha256 = field.NewString(table, "sha256")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3DocumentAsset) WithContext(ctx context.Context) *bidAnalysisV3DocumentAssetDo {
	return b.bidAnalysisV3DocumentAssetDo.WithContext(ctx)
}

func (b bidAnalysisV3DocumentAsset) TableName() string {
	return b.bidAnalysisV3DocumentAssetDo.TableName()
}

func (b bidAnalysisV3DocumentAsset) Alias() string { return b.bidAnalysisV3DocumentAssetDo.Alias() }

func (b *bidAnalysisV3DocumentAsset) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3DocumentAsset) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 12)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["asset_type"] = b.AssetType
	b.fieldMap["bucket"] = b.Bucket
	b.fieldMap["object_key"] = b.ObjectKey
	b.fieldMap["file_name"] = b.FileName
	b.fieldMap["mime_type"] = b.MimeType
	b.fieldMap["size_bytes"] = b.SizeBytes
	b.fieldMap["sha256"] = b.Sha256
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3DocumentAsset) clone(db *gorm.DB) bidAnalysisV3DocumentAsset {
	b.bidAnalysisV3DocumentAssetDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3DocumentAsset) replaceDB(db *gorm.DB) bidAnalysisV3DocumentAsset {
	b.bidAnalysisV3DocumentAssetDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3DocumentAssetDo struct{ gen.DO }

func (b bidAnalysisV3DocumentAssetDo) Debug() *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3DocumentAssetDo) WithContext(ctx context.Context) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3DocumentAssetDo) ReadDB() *bidAnalysisV3DocumentAssetDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3DocumentAssetDo) WriteDB() *bidAnalysisV3DocumentAssetDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3DocumentAssetDo) Session(config *gorm.Session) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3DocumentAssetDo) Clauses(conds ...clause.Expression) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Returning(value interface{}, columns ...string) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3DocumentAssetDo) Not(conds ...gen.Condition) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Or(conds ...gen.Condition) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Select(conds ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Where(conds ...gen.Condition) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3DocumentAssetDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3DocumentAssetDo) Order(conds ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Distinct(cols ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3DocumentAssetDo) Omit(cols ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3DocumentAssetDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3DocumentAssetDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3DocumentAssetDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3DocumentAssetDo) Group(cols ...field.Expr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3DocumentAssetDo) Having(conds ...gen.Condition) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3DocumentAssetDo) Limit(limit int) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3DocumentAssetDo) Offset(offset int) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3DocumentAssetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3DocumentAssetDo) Unscoped() *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3DocumentAssetDo) Create(values ...*model.BidAnalysisV3DocumentAsset) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3DocumentAssetDo) CreateInBatches(values []*model.BidAnalysisV3DocumentAsset, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3DocumentAssetDo) Save(values ...*model.BidAnalysisV3DocumentAsset) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3DocumentAssetDo) First() (*model.BidAnalysisV3DocumentAsset, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DocumentAsset), nil
	}
}

func (b bidAnalysisV3DocumentAssetDo) Take() (*model.BidAnalysisV3DocumentAsset, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DocumentAsset), nil
	}
}

func (b bidAnalysisV3DocumentAssetDo) Last() (*model.BidAnalysisV3DocumentAsset, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DocumentAsset), nil
	}
}

func (b bidAnalysisV3DocumentAssetDo) Find() ([]*model.BidAnalysisV3DocumentAsset, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3DocumentAsset), err
}

func (b bidAnalysisV3DocumentAssetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3DocumentAsset, err error) {
	buf := make([]*model.BidAnalysisV3DocumentAsset, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3DocumentAssetDo) FindInBatches(result *[]*model.BidAnalysisV3DocumentAsset, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3DocumentAssetDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3DocumentAssetDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3DocumentAssetDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3DocumentAssetDo) Joins(fields ...field.RelationField) *bidAnalysisV3DocumentAssetDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3DocumentAssetDo) Preload(fields ...field.RelationField) *bidAnalysisV3DocumentAssetDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3DocumentAssetDo) FirstOrInit() (*model.BidAnalysisV3DocumentAsset, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DocumentAsset), nil
	}
}

func (b bidAnalysisV3DocumentAssetDo) FirstOrCreate() (*model.BidAnalysisV3DocumentAsset, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3DocumentAsset), nil
	}
}

func (b bidAnalysisV3DocumentAssetDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3DocumentAsset, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3DocumentAssetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3DocumentAssetDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3DocumentAssetDo) Delete(models ...*model.BidAnalysisV3DocumentAsset) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3DocumentAssetDo) withDO(do gen.Dao) *bidAnalysisV3DocumentAssetDo {
	b.DO = *do.(*gen.DO)
	return b
}
