// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidGenChapterSpec(db *gorm.DB, opts ...gen.DOOption) bidGenChapterSpec {
	_bidGenChapterSpec := bidGenChapterSpec{}

	_bidGenChapterSpec.bidGenChapterSpecDo.UseDB(db, opts...)
	_bidGenChapterSpec.bidGenChapterSpecDo.UseModel(&model.BidGenChapterSpec{})

	tableName := _bidGenChapterSpec.bidGenChapterSpecDo.TableName()
	_bidGenChapterSpec.ALL = field.NewAsterisk(tableName)
	_bidGenChapterSpec.ID = field.NewInt64(tableName, "id")
	_bidGenChapterSpec.ProjectID = field.NewInt64(tableName, "project_id")
	_bidGenChapterSpec.OutlineID = field.NewInt64(tableName, "outline_id")
	_bidGenChapterSpec.GenTaskID = field.NewInt64(tableName, "gen_task_id")
	_bidGenChapterSpec.TargetWords = field.NewInt32(tableName, "target_words")
	_bidGenChapterSpec.PointsJSON = field.NewString(tableName, "points_json")
	_bidGenChapterSpec.EvidenceJSON = field.NewString(tableName, "evidence_json")
	_bidGenChapterSpec.TablesJSON = field.NewString(tableName, "tables_json")
	_bidGenChapterSpec.FiguresJSON = field.NewString(tableName, "figures_json")
	_bidGenChapterSpec.ScoringJSON = field.NewString(tableName, "scoring_json")
	_bidGenChapterSpec.CoverageJSON = field.NewString(tableName, "coverage_json")
	_bidGenChapterSpec.Model = field.NewString(tableName, "model")
	_bidGenChapterSpec.CreatedAt = field.NewTime(tableName, "created_at")
	_bidGenChapterSpec.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidGenChapterSpec.fillFieldMap()

	return _bidGenChapterSpec
}

type bidGenChapterSpec struct {
	bidGenChapterSpecDo bidGenChapterSpecDo

	ALL          field.Asterisk
	ID           field.Int64
	ProjectID    field.Int64
	OutlineID    field.Int64
	GenTaskID    field.Int64
	TargetWords  field.Int32
	PointsJSON   field.String
	EvidenceJSON field.String
	TablesJSON   field.String
	FiguresJSON  field.String
	ScoringJSON  field.String
	CoverageJSON field.String
	Model        field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (b bidGenChapterSpec) Table(newTableName string) *bidGenChapterSpec {
	b.bidGenChapterSpecDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidGenChapterSpec) As(alias string) *bidGenChapterSpec {
	b.bidGenChapterSpecDo.DO = *(b.bidGenChapterSpecDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidGenChapterSpec) updateTableName(table string) *bidGenChapterSpec {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.OutlineID = field.NewInt64(table, "outline_id")
	b.GenTaskID = field.NewInt64(table, "gen_task_id")
	b.TargetWords = field.NewInt32(table, "target_words")
	b.PointsJSON = field.NewString(table, "points_json")
	b.EvidenceJSON = field.NewString(table, "evidence_json")
	b.TablesJSON = field.NewString(table, "tables_json")
	b.FiguresJSON = field.NewString(table, "figures_json")
	b.ScoringJSON = field.NewString(table, "scoring_json")
	b.CoverageJSON = field.NewString(table, "coverage_json")
	b.Model = field.NewString(table, "model")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidGenChapterSpec) WithContext(ctx context.Context) *bidGenChapterSpecDo {
	return b.bidGenChapterSpecDo.WithContext(ctx)
}

func (b bidGenChapterSpec) TableName() string { return b.bidGenChapterSpecDo.TableName() }

func (b bidGenChapterSpec) Alias() string { return b.bidGenChapterSpecDo.Alias() }

func (b *bidGenChapterSpec) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidGenChapterSpec) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 14)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["outline_id"] = b.OutlineID
	b.fieldMap["gen_task_id"] = b.GenTaskID
	b.fieldMap["target_words"] = b.TargetWords
	b.fieldMap["points_json"] = b.PointsJSON
	b.fieldMap["evidence_json"] = b.EvidenceJSON
	b.fieldMap["tables_json"] = b.TablesJSON
	b.fieldMap["figures_json"] = b.FiguresJSON
	b.fieldMap["scoring_json"] = b.ScoringJSON
	b.fieldMap["coverage_json"] = b.CoverageJSON
	b.fieldMap["model"] = b.Model
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidGenChapterSpec) clone(db *gorm.DB) bidGenChapterSpec {
	b.bidGenChapterSpecDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidGenChapterSpec) replaceDB(db *gorm.DB) bidGenChapterSpec {
	b.bidGenChapterSpecDo.ReplaceDB(db)
	return b
}

type bidGenChapterSpecDo struct{ gen.DO }

func (b bidGenChapterSpecDo) Debug() *bidGenChapterSpecDo {
	return b.withDO(b.DO.Debug())
}

func (b bidGenChapterSpecDo) WithContext(ctx context.Context) *bidGenChapterSpecDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidGenChapterSpecDo) ReadDB() *bidGenChapterSpecDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidGenChapterSpecDo) WriteDB() *bidGenChapterSpecDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidGenChapterSpecDo) Session(config *gorm.Session) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidGenChapterSpecDo) Clauses(conds ...clause.Expression) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidGenChapterSpecDo) Returning(value interface{}, columns ...string) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidGenChapterSpecDo) Not(conds ...gen.Condition) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidGenChapterSpecDo) Or(conds ...gen.Condition) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidGenChapterSpecDo) Select(conds ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidGenChapterSpecDo) Where(conds ...gen.Condition) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidGenChapterSpecDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidGenChapterSpecDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidGenChapterSpecDo) Order(conds ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidGenChapterSpecDo) Distinct(cols ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidGenChapterSpecDo) Omit(cols ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidGenChapterSpecDo) Join(table schema.Tabler, on ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidGenChapterSpecDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidGenChapterSpecDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidGenChapterSpecDo) Group(cols ...field.Expr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidGenChapterSpecDo) Having(conds ...gen.Condition) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidGenChapterSpecDo) Limit(limit int) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidGenChapterSpecDo) Offset(offset int) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidGenChapterSpecDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidGenChapterSpecDo) Unscoped() *bidGenChapterSpecDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidGenChapterSpecDo) Create(values ...*model.BidGenChapterSpec) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidGenChapterSpecDo) CreateInBatches(values []*model.BidGenChapterSpec, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidGenChapterSpecDo) Save(values ...*model.BidGenChapterSpec) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidGenChapterSpecDo) First() (*model.BidGenChapterSpec, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenChapterSpec), nil
	}
}

func (b bidGenChapterSpecDo) Take() (*model.BidGenChapterSpec, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenChapterSpec), nil
	}
}

func (b bidGenChapterSpecDo) Last() (*model.BidGenChapterSpec, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenChapterSpec), nil
	}
}

func (b bidGenChapterSpecDo) Find() ([]*model.BidGenChapterSpec, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidGenChapterSpec), err
}

func (b bidGenChapterSpecDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidGenChapterSpec, err error) {
	buf := make([]*model.BidGenChapterSpec, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidGenChapterSpecDo) FindInBatches(result *[]*model.BidGenChapterSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidGenChapterSpecDo) Attrs(attrs ...field.AssignExpr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidGenChapterSpecDo) Assign(attrs ...field.AssignExpr) *bidGenChapterSpecDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidGenChapterSpecDo) Joins(fields ...field.RelationField) *bidGenChapterSpecDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidGenChapterSpecDo) Preload(fields ...field.RelationField) *bidGenChapterSpecDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidGenChapterSpecDo) FirstOrInit() (*model.BidGenChapterSpec, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenChapterSpec), nil
	}
}

func (b bidGenChapterSpecDo) FirstOrCreate() (*model.BidGenChapterSpec, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidGenChapterSpec), nil
	}
}

func (b bidGenChapterSpecDo) FindByPage(offset int, limit int) (result []*model.BidGenChapterSpec, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidGenChapterSpecDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidGenChapterSpecDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidGenChapterSpecDo) Delete(models ...*model.BidGenChapterSpec) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidGenChapterSpecDo) withDO(do gen.Dao) *bidGenChapterSpecDo {
	b.DO = *do.(*gen.DO)
	return b
}
