// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3StageRun(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3StageRun {
	_bidAnalysisV3StageRun := bidAnalysisV3StageRun{}

	_bidAnalysisV3StageRun.bidAnalysisV3StageRunDo.UseDB(db, opts...)
	_bidAnalysisV3StageRun.bidAnalysisV3StageRunDo.UseModel(&model.BidAnalysisV3StageRun{})

	tableName := _bidAnalysisV3StageRun.bidAnalysisV3StageRunDo.TableName()
	_bidAnalysisV3StageRun.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3StageRun.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3StageRun.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3StageRun.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3StageRun.Stage = field.NewString(tableName, "stage")
	_bidAnalysisV3StageRun.Status = field.NewString(tableName, "status")
	_bidAnalysisV3StageRun.Weight = field.NewInt32(tableName, "weight")
	_bidAnalysisV3StageRun.TotalUnits = field.NewInt32(tableName, "total_units")
	_bidAnalysisV3StageRun.CompletedUnits = field.NewInt32(tableName, "completed_units")
	_bidAnalysisV3StageRun.FailedUnits = field.NewInt32(tableName, "failed_units")
	_bidAnalysisV3StageRun.WarningCount = field.NewInt32(tableName, "warning_count")
	_bidAnalysisV3StageRun.Attempts = field.NewInt32(tableName, "attempts")
	_bidAnalysisV3StageRun.LastError = field.NewString(tableName, "last_error")
	_bidAnalysisV3StageRun.StartedAt = field.NewTime(tableName, "started_at")
	_bidAnalysisV3StageRun.CompletedAt = field.NewTime(tableName, "completed_at")
	_bidAnalysisV3StageRun.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3StageRun.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3StageRun.fillFieldMap()

	return _bidAnalysisV3StageRun
}

type bidAnalysisV3StageRun struct {
	bidAnalysisV3StageRunDo bidAnalysisV3StageRunDo

	ALL            field.Asterisk
	ID             field.Int64  // 主键
	ProjectID      field.Int64  // 招标解析项目ID
	RunID          field.Int64  // 解析运行ID
	Stage          field.String // 当前处理阶段
	Status         field.String // pending/running/succeeded/partial/failed/skipped
	Weight         field.Int32  // 阶段进度权重
	TotalUnits     field.Int32  // 任务单元总数
	CompletedUnits field.Int32  // 成功任务单元数
	FailedUnits    field.Int32  // 失败任务单元数
	WarningCount   field.Int32  // 告警数量
	Attempts       field.Int32  // 已尝试次数
	LastError      field.String // 最近一次错误信息
	StartedAt      field.Time   // 开始时间
	CompletedAt    field.Time   // 完成时间
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3StageRun) Table(newTableName string) *bidAnalysisV3StageRun {
	b.bidAnalysisV3StageRunDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3StageRun) As(alias string) *bidAnalysisV3StageRun {
	b.bidAnalysisV3StageRunDo.DO = *(b.bidAnalysisV3StageRunDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3StageRun) updateTableName(table string) *bidAnalysisV3StageRun {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.Stage = field.NewString(table, "stage")
	b.Status = field.NewString(table, "status")
	b.Weight = field.NewInt32(table, "weight")
	b.TotalUnits = field.NewInt32(table, "total_units")
	b.CompletedUnits = field.NewInt32(table, "completed_units")
	b.FailedUnits = field.NewInt32(table, "failed_units")
	b.WarningCount = field.NewInt32(table, "warning_count")
	b.Attempts = field.NewInt32(table, "attempts")
	b.LastError = field.NewString(table, "last_error")
	b.StartedAt = field.NewTime(table, "started_at")
	b.CompletedAt = field.NewTime(table, "completed_at")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3StageRun) WithContext(ctx context.Context) *bidAnalysisV3StageRunDo {
	return b.bidAnalysisV3StageRunDo.WithContext(ctx)
}

func (b bidAnalysisV3StageRun) TableName() string { return b.bidAnalysisV3StageRunDo.TableName() }

func (b bidAnalysisV3StageRun) Alias() string { return b.bidAnalysisV3StageRunDo.Alias() }

func (b *bidAnalysisV3StageRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3StageRun) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 16)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["status"] = b.Status
	b.fieldMap["weight"] = b.Weight
	b.fieldMap["total_units"] = b.TotalUnits
	b.fieldMap["completed_units"] = b.CompletedUnits
	b.fieldMap["failed_units"] = b.FailedUnits
	b.fieldMap["warning_count"] = b.WarningCount
	b.fieldMap["attempts"] = b.Attempts
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["started_at"] = b.StartedAt
	b.fieldMap["completed_at"] = b.CompletedAt
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3StageRun) clone(db *gorm.DB) bidAnalysisV3StageRun {
	b.bidAnalysisV3StageRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3StageRun) replaceDB(db *gorm.DB) bidAnalysisV3StageRun {
	b.bidAnalysisV3StageRunDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3StageRunDo struct{ gen.DO }

func (b bidAnalysisV3StageRunDo) Debug() *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3StageRunDo) WithContext(ctx context.Context) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3StageRunDo) ReadDB() *bidAnalysisV3StageRunDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3StageRunDo) WriteDB() *bidAnalysisV3StageRunDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3StageRunDo) Session(config *gorm.Session) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3StageRunDo) Clauses(conds ...clause.Expression) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3StageRunDo) Returning(value interface{}, columns ...string) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3StageRunDo) Not(conds ...gen.Condition) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3StageRunDo) Or(conds ...gen.Condition) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3StageRunDo) Select(conds ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3StageRunDo) Where(conds ...gen.Condition) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3StageRunDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3StageRunDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3StageRunDo) Order(conds ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3StageRunDo) Distinct(cols ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3StageRunDo) Omit(cols ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3StageRunDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3StageRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3StageRunDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3StageRunDo) Group(cols ...field.Expr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3StageRunDo) Having(conds ...gen.Condition) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3StageRunDo) Limit(limit int) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3StageRunDo) Offset(offset int) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3StageRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3StageRunDo) Unscoped() *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3StageRunDo) Create(values ...*model.BidAnalysisV3StageRun) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3StageRunDo) CreateInBatches(values []*model.BidAnalysisV3StageRun, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3StageRunDo) Save(values ...*model.BidAnalysisV3StageRun) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3StageRunDo) First() (*model.BidAnalysisV3StageRun, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageRun), nil
	}
}

func (b bidAnalysisV3StageRunDo) Take() (*model.BidAnalysisV3StageRun, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageRun), nil
	}
}

func (b bidAnalysisV3StageRunDo) Last() (*model.BidAnalysisV3StageRun, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageRun), nil
	}
}

func (b bidAnalysisV3StageRunDo) Find() ([]*model.BidAnalysisV3StageRun, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3StageRun), err
}

func (b bidAnalysisV3StageRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3StageRun, err error) {
	buf := make([]*model.BidAnalysisV3StageRun, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3StageRunDo) FindInBatches(result *[]*model.BidAnalysisV3StageRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3StageRunDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3StageRunDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3StageRunDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3StageRunDo) Joins(fields ...field.RelationField) *bidAnalysisV3StageRunDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3StageRunDo) Preload(fields ...field.RelationField) *bidAnalysisV3StageRunDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3StageRunDo) FirstOrInit() (*model.BidAnalysisV3StageRun, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageRun), nil
	}
}

func (b bidAnalysisV3StageRunDo) FirstOrCreate() (*model.BidAnalysisV3StageRun, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3StageRun), nil
	}
}

func (b bidAnalysisV3StageRunDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3StageRun, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3StageRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3StageRunDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3StageRunDo) Delete(models ...*model.BidAnalysisV3StageRun) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3StageRunDo) withDO(do gen.Dao) *bidAnalysisV3StageRunDo {
	b.DO = *do.(*gen.DO)
	return b
}
