// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidReviewProject(db *gorm.DB, opts ...gen.DOOption) bidReviewProject {
	_bidReviewProject := bidReviewProject{}

	_bidReviewProject.bidReviewProjectDo.UseDB(db, opts...)
	_bidReviewProject.bidReviewProjectDo.UseModel(&model.BidReviewProject{})

	tableName := _bidReviewProject.bidReviewProjectDo.TableName()
	_bidReviewProject.ALL = field.NewAsterisk(tableName)
	_bidReviewProject.ID = field.NewInt64(tableName, "id")
	_bidReviewProject.Name = field.NewString(tableName, "name")
	_bidReviewProject.CreateType = field.NewString(tableName, "create_type")
	_bidReviewProject.Status = field.NewString(tableName, "status")
	_bidReviewProject.Stage = field.NewString(tableName, "stage")
	_bidReviewProject.Progress = field.NewInt32(tableName, "progress")
	_bidReviewProject.StageStatus = field.NewString(tableName, "stage_status")
	_bidReviewProject.LastError = field.NewString(tableName, "last_error")
	_bidReviewProject.SourceBidGenProjectID = field.NewInt64(tableName, "source_bid_gen_project_id")
	_bidReviewProject.TenderFileCount = field.NewInt32(tableName, "tender_file_count")
	_bidReviewProject.BidFileCount = field.NewInt32(tableName, "bid_file_count")
	_bidReviewProject.TotalItems = field.NewInt32(tableName, "total_items")
	_bidReviewProject.WarningItems = field.NewInt32(tableName, "warning_items")
	_bidReviewProject.ErrorItems = field.NewInt32(tableName, "error_items")
	_bidReviewProject.PassedItems = field.NewInt32(tableName, "passed_items")
	_bidReviewProject.UserID = field.NewInt64(tableName, "user_id")
	_bidReviewProject.UserTeamID = field.NewInt32(tableName, "user_team_id")
	_bidReviewProject.UserCompanyID = field.NewInt32(tableName, "user_company_id")
	_bidReviewProject.CreatedAt = field.NewTime(tableName, "created_at")
	_bidReviewProject.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidReviewProject.fillFieldMap()

	return _bidReviewProject
}

type bidReviewProject struct {
	bidReviewProjectDo bidReviewProjectDo

	ALL                   field.Asterisk
	ID                    field.Int64
	Name                  field.String // 项目名称
	CreateType            field.String // 创建方式: manual-上传创建, gen-从标书生成
	Status                field.String // 状态: running/succeed/failed
	Stage                 field.String // 当前执行阶段
	Progress              field.Int32  // 进度 0-100
	StageStatus           field.String // 阶段状态JSON
	LastError             field.String // 最近一次错误信息
	SourceBidGenProjectID field.Int64  // 来源标书生成项目ID（create_type=gen时）
	TenderFileCount       field.Int32  // 招标文件数
	BidFileCount          field.Int32  // 投标文件数
	TotalItems            field.Int32  // 检查项总数
	WarningItems          field.Int32  // 告警项数
	ErrorItems            field.Int32  // 高风险项数
	PassedItems           field.Int32  // 通过项数
	UserID                field.Int64  // 创建用户ID
	UserTeamID            field.Int32  // 所属团队ID
	UserCompanyID         field.Int32  // 所属公司ID
	CreatedAt             field.Time   // 创建时间
	UpdatedAt             field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidReviewProject) Table(newTableName string) *bidReviewProject {
	b.bidReviewProjectDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidReviewProject) As(alias string) *bidReviewProject {
	b.bidReviewProjectDo.DO = *(b.bidReviewProjectDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidReviewProject) updateTableName(table string) *bidReviewProject {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.Name = field.NewString(table, "name")
	b.CreateType = field.NewString(table, "create_type")
	b.Status = field.NewString(table, "status")
	b.Stage = field.NewString(table, "stage")
	b.Progress = field.NewInt32(table, "progress")
	b.StageStatus = field.NewString(table, "stage_status")
	b.LastError = field.NewString(table, "last_error")
	b.SourceBidGenProjectID = field.NewInt64(table, "source_bid_gen_project_id")
	b.TenderFileCount = field.NewInt32(table, "tender_file_count")
	b.BidFileCount = field.NewInt32(table, "bid_file_count")
	b.TotalItems = field.NewInt32(table, "total_items")
	b.WarningItems = field.NewInt32(table, "warning_items")
	b.ErrorItems = field.NewInt32(table, "error_items")
	b.PassedItems = field.NewInt32(table, "passed_items")
	b.UserID = field.NewInt64(table, "user_id")
	b.UserTeamID = field.NewInt32(table, "user_team_id")
	b.UserCompanyID = field.NewInt32(table, "user_company_id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidReviewProject) WithContext(ctx context.Context) *bidReviewProjectDo {
	return b.bidReviewProjectDo.WithContext(ctx)
}

func (b bidReviewProject) TableName() string { return b.bidReviewProjectDo.TableName() }

func (b bidReviewProject) Alias() string { return b.bidReviewProjectDo.Alias() }

func (b *bidReviewProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidReviewProject) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 20)
	b.fieldMap["id"] = b.ID
	b.fieldMap["name"] = b.Name
	b.fieldMap["create_type"] = b.CreateType
	b.fieldMap["status"] = b.Status
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["progress"] = b.Progress
	b.fieldMap["stage_status"] = b.StageStatus
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["source_bid_gen_project_id"] = b.SourceBidGenProjectID
	b.fieldMap["tender_file_count"] = b.TenderFileCount
	b.fieldMap["bid_file_count"] = b.BidFileCount
	b.fieldMap["total_items"] = b.TotalItems
	b.fieldMap["warning_items"] = b.WarningItems
	b.fieldMap["error_items"] = b.ErrorItems
	b.fieldMap["passed_items"] = b.PassedItems
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["user_team_id"] = b.UserTeamID
	b.fieldMap["user_company_id"] = b.UserCompanyID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidReviewProject) clone(db *gorm.DB) bidReviewProject {
	b.bidReviewProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidReviewProject) replaceDB(db *gorm.DB) bidReviewProject {
	b.bidReviewProjectDo.ReplaceDB(db)
	return b
}

type bidReviewProjectDo struct{ gen.DO }

func (b bidReviewProjectDo) Debug() *bidReviewProjectDo {
	return b.withDO(b.DO.Debug())
}

func (b bidReviewProjectDo) WithContext(ctx context.Context) *bidReviewProjectDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidReviewProjectDo) ReadDB() *bidReviewProjectDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidReviewProjectDo) WriteDB() *bidReviewProjectDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidReviewProjectDo) Session(config *gorm.Session) *bidReviewProjectDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidReviewProjectDo) Clauses(conds ...clause.Expression) *bidReviewProjectDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidReviewProjectDo) Returning(value interface{}, columns ...string) *bidReviewProjectDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidReviewProjectDo) Not(conds ...gen.Condition) *bidReviewProjectDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidReviewProjectDo) Or(conds ...gen.Condition) *bidReviewProjectDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidReviewProjectDo) Select(conds ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidReviewProjectDo) Where(conds ...gen.Condition) *bidReviewProjectDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidReviewProjectDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidReviewProjectDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidReviewProjectDo) Order(conds ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidReviewProjectDo) Distinct(cols ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidReviewProjectDo) Omit(cols ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidReviewProjectDo) Join(table schema.Tabler, on ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidReviewProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidReviewProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidReviewProjectDo) Group(cols ...field.Expr) *bidReviewProjectDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidReviewProjectDo) Having(conds ...gen.Condition) *bidReviewProjectDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidReviewProjectDo) Limit(limit int) *bidReviewProjectDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidReviewProjectDo) Offset(offset int) *bidReviewProjectDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidReviewProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidReviewProjectDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidReviewProjectDo) Unscoped() *bidReviewProjectDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidReviewProjectDo) Create(values ...*model.BidReviewProject) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidReviewProjectDo) CreateInBatches(values []*model.BidReviewProject, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidReviewProjectDo) Save(values ...*model.BidReviewProject) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidReviewProjectDo) First() (*model.BidReviewProject, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewProject), nil
	}
}

func (b bidReviewProjectDo) Take() (*model.BidReviewProject, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewProject), nil
	}
}

func (b bidReviewProjectDo) Last() (*model.BidReviewProject, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewProject), nil
	}
}

func (b bidReviewProjectDo) Find() ([]*model.BidReviewProject, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidReviewProject), err
}

func (b bidReviewProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidReviewProject, err error) {
	buf := make([]*model.BidReviewProject, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidReviewProjectDo) FindInBatches(result *[]*model.BidReviewProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidReviewProjectDo) Attrs(attrs ...field.AssignExpr) *bidReviewProjectDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidReviewProjectDo) Assign(attrs ...field.AssignExpr) *bidReviewProjectDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidReviewProjectDo) Joins(fields ...field.RelationField) *bidReviewProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidReviewProjectDo) Preload(fields ...field.RelationField) *bidReviewProjectDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidReviewProjectDo) FirstOrInit() (*model.BidReviewProject, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewProject), nil
	}
}

func (b bidReviewProjectDo) FirstOrCreate() (*model.BidReviewProject, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewProject), nil
	}
}

func (b bidReviewProjectDo) FindByPage(offset int, limit int) (result []*model.BidReviewProject, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidReviewProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidReviewProjectDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidReviewProjectDo) Delete(models ...*model.BidReviewProject) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidReviewProjectDo) withDO(do gen.Dao) *bidReviewProjectDo {
	b.DO = *do.(*gen.DO)
	return b
}
