// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3ParseRun(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3ParseRun {
	_bidAnalysisV3ParseRun := bidAnalysisV3ParseRun{}

	_bidAnalysisV3ParseRun.bidAnalysisV3ParseRunDo.UseDB(db, opts...)
	_bidAnalysisV3ParseRun.bidAnalysisV3ParseRunDo.UseModel(&model.BidAnalysisV3ParseRun{})

	tableName := _bidAnalysisV3ParseRun.bidAnalysisV3ParseRunDo.TableName()
	_bidAnalysisV3ParseRun.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3ParseRun.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3ParseRun.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3ParseRun.RunNo = field.NewInt32(tableName, "run_no")
	_bidAnalysisV3ParseRun.TriggerType = field.NewString(tableName, "trigger_type")
	_bidAnalysisV3ParseRun.Status = field.NewString(tableName, "status")
	_bidAnalysisV3ParseRun.Stage = field.NewString(tableName, "stage")
	_bidAnalysisV3ParseRun.Progress = field.NewInt32(tableName, "progress")
	_bidAnalysisV3ParseRun.TotalPages = field.NewInt32(tableName, "total_pages")
	_bidAnalysisV3ParseRun.ParsedPages = field.NewInt32(tableName, "parsed_pages")
	_bidAnalysisV3ParseRun.TotalChunks = field.NewInt32(tableName, "total_chunks")
	_bidAnalysisV3ParseRun.ParsedChunks = field.NewInt32(tableName, "parsed_chunks")
	_bidAnalysisV3ParseRun.TotalChapters = field.NewInt32(tableName, "total_chapters")
	_bidAnalysisV3ParseRun.ExtractedChapters = field.NewInt32(tableName, "extracted_chapters")
	_bidAnalysisV3ParseRun.WarningCount = field.NewInt32(tableName, "warning_count")
	_bidAnalysisV3ParseRun.ModelConfigJSON = field.NewString(tableName, "model_config_json")
	_bidAnalysisV3ParseRun.LastError = field.NewString(tableName, "last_error")
	_bidAnalysisV3ParseRun.StartedAt = field.NewTime(tableName, "started_at")
	_bidAnalysisV3ParseRun.CompletedAt = field.NewTime(tableName, "completed_at")
	_bidAnalysisV3ParseRun.ActivatedAt = field.NewTime(tableName, "activated_at")
	_bidAnalysisV3ParseRun.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3ParseRun.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3ParseRun.fillFieldMap()

	return _bidAnalysisV3ParseRun
}

type bidAnalysisV3ParseRun struct {
	bidAnalysisV3ParseRunDo bidAnalysisV3ParseRunDo

	ALL               field.Asterisk
	ID                field.Int64  // 主键
	ProjectID         field.Int64  // 招标解析项目ID
	RunNo             field.Int32  // 项目内运行序号
	TriggerType       field.String // create/reparse/retry
	Status            field.String // running/paused/succeeded/succeeded_with_warnings/failed
	Stage             field.String // 当前处理阶段
	Progress          field.Int32  // 处理进度百分比
	TotalPages        field.Int32  // 总页数
	ParsedPages       field.Int32  // 已解析页数
	TotalChunks       field.Int32  // 总页块数
	ParsedChunks      field.Int32  // 已解析页块数
	TotalChapters     field.Int32  // 总章节数
	ExtractedChapters field.Int32  // 已提取章节数
	WarningCount      field.Int32  // 告警数量
	ModelConfigJSON   field.String // 模型配置快照JSON
	LastError         field.String // 最近一次错误信息
	StartedAt         field.Time   // 开始时间
	CompletedAt       field.Time   // 完成时间
	ActivatedAt       field.Time   // 结果激活时间
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3ParseRun) Table(newTableName string) *bidAnalysisV3ParseRun {
	b.bidAnalysisV3ParseRunDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3ParseRun) As(alias string) *bidAnalysisV3ParseRun {
	b.bidAnalysisV3ParseRunDo.DO = *(b.bidAnalysisV3ParseRunDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3ParseRun) updateTableName(table string) *bidAnalysisV3ParseRun {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunNo = field.NewInt32(table, "run_no")
	b.TriggerType = field.NewString(table, "trigger_type")
	b.Status = field.NewString(table, "status")
	b.Stage = field.NewString(table, "stage")
	b.Progress = field.NewInt32(table, "progress")
	b.TotalPages = field.NewInt32(table, "total_pages")
	b.ParsedPages = field.NewInt32(table, "parsed_pages")
	b.TotalChunks = field.NewInt32(table, "total_chunks")
	b.ParsedChunks = field.NewInt32(table, "parsed_chunks")
	b.TotalChapters = field.NewInt32(table, "total_chapters")
	b.ExtractedChapters = field.NewInt32(table, "extracted_chapters")
	b.WarningCount = field.NewInt32(table, "warning_count")
	b.ModelConfigJSON = field.NewString(table, "model_config_json")
	b.LastError = field.NewString(table, "last_error")
	b.StartedAt = field.NewTime(table, "started_at")
	b.CompletedAt = field.NewTime(table, "completed_at")
	b.ActivatedAt = field.NewTime(table, "activated_at")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3ParseRun) WithContext(ctx context.Context) *bidAnalysisV3ParseRunDo {
	return b.bidAnalysisV3ParseRunDo.WithContext(ctx)
}

func (b bidAnalysisV3ParseRun) TableName() string { return b.bidAnalysisV3ParseRunDo.TableName() }

func (b bidAnalysisV3ParseRun) Alias() string { return b.bidAnalysisV3ParseRunDo.Alias() }

func (b *bidAnalysisV3ParseRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3ParseRun) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 21)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_no"] = b.RunNo
	b.fieldMap["trigger_type"] = b.TriggerType
	b.fieldMap["status"] = b.Status
	b.fieldMap["stage"] = b.Stage
	b.fieldMap["progress"] = b.Progress
	b.fieldMap["total_pages"] = b.TotalPages
	b.fieldMap["parsed_pages"] = b.ParsedPages
	b.fieldMap["total_chunks"] = b.TotalChunks
	b.fieldMap["parsed_chunks"] = b.ParsedChunks
	b.fieldMap["total_chapters"] = b.TotalChapters
	b.fieldMap["extracted_chapters"] = b.ExtractedChapters
	b.fieldMap["warning_count"] = b.WarningCount
	b.fieldMap["model_config_json"] = b.ModelConfigJSON
	b.fieldMap["last_error"] = b.LastError
	b.fieldMap["started_at"] = b.StartedAt
	b.fieldMap["completed_at"] = b.CompletedAt
	b.fieldMap["activated_at"] = b.ActivatedAt
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3ParseRun) clone(db *gorm.DB) bidAnalysisV3ParseRun {
	b.bidAnalysisV3ParseRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3ParseRun) replaceDB(db *gorm.DB) bidAnalysisV3ParseRun {
	b.bidAnalysisV3ParseRunDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3ParseRunDo struct{ gen.DO }

func (b bidAnalysisV3ParseRunDo) Debug() *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3ParseRunDo) WithContext(ctx context.Context) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3ParseRunDo) ReadDB() *bidAnalysisV3ParseRunDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3ParseRunDo) WriteDB() *bidAnalysisV3ParseRunDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3ParseRunDo) Session(config *gorm.Session) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3ParseRunDo) Clauses(conds ...clause.Expression) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3ParseRunDo) Returning(value interface{}, columns ...string) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3ParseRunDo) Not(conds ...gen.Condition) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3ParseRunDo) Or(conds ...gen.Condition) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3ParseRunDo) Select(conds ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3ParseRunDo) Where(conds ...gen.Condition) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3ParseRunDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3ParseRunDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3ParseRunDo) Order(conds ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3ParseRunDo) Distinct(cols ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3ParseRunDo) Omit(cols ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3ParseRunDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3ParseRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3ParseRunDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3ParseRunDo) Group(cols ...field.Expr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3ParseRunDo) Having(conds ...gen.Condition) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3ParseRunDo) Limit(limit int) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3ParseRunDo) Offset(offset int) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3ParseRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3ParseRunDo) Unscoped() *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3ParseRunDo) Create(values ...*model.BidAnalysisV3ParseRun) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3ParseRunDo) CreateInBatches(values []*model.BidAnalysisV3ParseRun, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3ParseRunDo) Save(values ...*model.BidAnalysisV3ParseRun) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3ParseRunDo) First() (*model.BidAnalysisV3ParseRun, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ParseRun), nil
	}
}

func (b bidAnalysisV3ParseRunDo) Take() (*model.BidAnalysisV3ParseRun, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ParseRun), nil
	}
}

func (b bidAnalysisV3ParseRunDo) Last() (*model.BidAnalysisV3ParseRun, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ParseRun), nil
	}
}

func (b bidAnalysisV3ParseRunDo) Find() ([]*model.BidAnalysisV3ParseRun, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3ParseRun), err
}

func (b bidAnalysisV3ParseRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3ParseRun, err error) {
	buf := make([]*model.BidAnalysisV3ParseRun, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3ParseRunDo) FindInBatches(result *[]*model.BidAnalysisV3ParseRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3ParseRunDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3ParseRunDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3ParseRunDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3ParseRunDo) Joins(fields ...field.RelationField) *bidAnalysisV3ParseRunDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3ParseRunDo) Preload(fields ...field.RelationField) *bidAnalysisV3ParseRunDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3ParseRunDo) FirstOrInit() (*model.BidAnalysisV3ParseRun, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ParseRun), nil
	}
}

func (b bidAnalysisV3ParseRunDo) FirstOrCreate() (*model.BidAnalysisV3ParseRun, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ParseRun), nil
	}
}

func (b bidAnalysisV3ParseRunDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3ParseRun, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3ParseRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3ParseRunDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3ParseRunDo) Delete(models ...*model.BidAnalysisV3ParseRun) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3ParseRunDo) withDO(do gen.Dao) *bidAnalysisV3ParseRunDo {
	b.DO = *do.(*gen.DO)
	return b
}
