// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3ClauseEvidence(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3ClauseEvidence {
	_bidAnalysisV3ClauseEvidence := bidAnalysisV3ClauseEvidence{}

	_bidAnalysisV3ClauseEvidence.bidAnalysisV3ClauseEvidenceDo.UseDB(db, opts...)
	_bidAnalysisV3ClauseEvidence.bidAnalysisV3ClauseEvidenceDo.UseModel(&model.BidAnalysisV3ClauseEvidence{})

	tableName := _bidAnalysisV3ClauseEvidence.bidAnalysisV3ClauseEvidenceDo.TableName()
	_bidAnalysisV3ClauseEvidence.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3ClauseEvidence.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3ClauseEvidence.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3ClauseEvidence.RunID = field.NewInt64(tableName, "run_id")
	_bidAnalysisV3ClauseEvidence.ClauseID = field.NewInt64(tableName, "clause_id")
	_bidAnalysisV3ClauseEvidence.SourceKind = field.NewString(tableName, "source_kind")
	_bidAnalysisV3ClauseEvidence.BlockID = field.NewInt64(tableName, "block_id")
	_bidAnalysisV3ClauseEvidence.SourceTableID = field.NewInt64(tableName, "source_table_id")
	_bidAnalysisV3ClauseEvidence.PageNo = field.NewInt32(tableName, "page_no")
	_bidAnalysisV3ClauseEvidence.Quote = field.NewString(tableName, "quote")
	_bidAnalysisV3ClauseEvidence.BboxLeft = field.NewFloat64(tableName, "bbox_left")
	_bidAnalysisV3ClauseEvidence.BboxTop = field.NewFloat64(tableName, "bbox_top")
	_bidAnalysisV3ClauseEvidence.BboxWidth = field.NewFloat64(tableName, "bbox_width")
	_bidAnalysisV3ClauseEvidence.BboxHeight = field.NewFloat64(tableName, "bbox_height")
	_bidAnalysisV3ClauseEvidence.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidAnalysisV3ClauseEvidence.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3ClauseEvidence.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3ClauseEvidence.fillFieldMap()

	return _bidAnalysisV3ClauseEvidence
}

type bidAnalysisV3ClauseEvidence struct {
	bidAnalysisV3ClauseEvidenceDo bidAnalysisV3ClauseEvidenceDo

	ALL           field.Asterisk
	ID            field.Int64   // 主键
	ProjectID     field.Int64   // 招标解析项目ID
	RunID         field.Int64   // 解析运行ID
	ClauseID      field.Int64   // 条款ID
	SourceKind    field.String  // 证据来源类型
	BlockID       field.Int64   // 文档文本块ID
	SourceTableID field.Int64   // 原文表格ID
	PageNo        field.Int32   // 全局页码
	Quote         field.String  // 证据原文摘要
	BboxLeft      field.Float64 // 归一化左侧坐标
	BboxTop       field.Float64 // 归一化顶部坐标
	BboxWidth     field.Float64 // 归一化区域宽度
	BboxHeight    field.Float64 // 归一化区域高度
	SortOrder     field.Int32   // 排序序号
	CreatedAt     field.Time    // 创建时间
	UpdatedAt     field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3ClauseEvidence) Table(newTableName string) *bidAnalysisV3ClauseEvidence {
	b.bidAnalysisV3ClauseEvidenceDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3ClauseEvidence) As(alias string) *bidAnalysisV3ClauseEvidence {
	b.bidAnalysisV3ClauseEvidenceDo.DO = *(b.bidAnalysisV3ClauseEvidenceDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3ClauseEvidence) updateTableName(table string) *bidAnalysisV3ClauseEvidence {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.RunID = field.NewInt64(table, "run_id")
	b.ClauseID = field.NewInt64(table, "clause_id")
	b.SourceKind = field.NewString(table, "source_kind")
	b.BlockID = field.NewInt64(table, "block_id")
	b.SourceTableID = field.NewInt64(table, "source_table_id")
	b.PageNo = field.NewInt32(table, "page_no")
	b.Quote = field.NewString(table, "quote")
	b.BboxLeft = field.NewFloat64(table, "bbox_left")
	b.BboxTop = field.NewFloat64(table, "bbox_top")
	b.BboxWidth = field.NewFloat64(table, "bbox_width")
	b.BboxHeight = field.NewFloat64(table, "bbox_height")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3ClauseEvidence) WithContext(ctx context.Context) *bidAnalysisV3ClauseEvidenceDo {
	return b.bidAnalysisV3ClauseEvidenceDo.WithContext(ctx)
}

func (b bidAnalysisV3ClauseEvidence) TableName() string {
	return b.bidAnalysisV3ClauseEvidenceDo.TableName()
}

func (b bidAnalysisV3ClauseEvidence) Alias() string { return b.bidAnalysisV3ClauseEvidenceDo.Alias() }

func (b *bidAnalysisV3ClauseEvidence) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3ClauseEvidence) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 16)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["run_id"] = b.RunID
	b.fieldMap["clause_id"] = b.ClauseID
	b.fieldMap["source_kind"] = b.SourceKind
	b.fieldMap["block_id"] = b.BlockID
	b.fieldMap["source_table_id"] = b.SourceTableID
	b.fieldMap["page_no"] = b.PageNo
	b.fieldMap["quote"] = b.Quote
	b.fieldMap["bbox_left"] = b.BboxLeft
	b.fieldMap["bbox_top"] = b.BboxTop
	b.fieldMap["bbox_width"] = b.BboxWidth
	b.fieldMap["bbox_height"] = b.BboxHeight
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3ClauseEvidence) clone(db *gorm.DB) bidAnalysisV3ClauseEvidence {
	b.bidAnalysisV3ClauseEvidenceDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3ClauseEvidence) replaceDB(db *gorm.DB) bidAnalysisV3ClauseEvidence {
	b.bidAnalysisV3ClauseEvidenceDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3ClauseEvidenceDo struct{ gen.DO }

func (b bidAnalysisV3ClauseEvidenceDo) Debug() *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3ClauseEvidenceDo) WithContext(ctx context.Context) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3ClauseEvidenceDo) ReadDB() *bidAnalysisV3ClauseEvidenceDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3ClauseEvidenceDo) WriteDB() *bidAnalysisV3ClauseEvidenceDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3ClauseEvidenceDo) Session(config *gorm.Session) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3ClauseEvidenceDo) Clauses(conds ...clause.Expression) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Returning(value interface{}, columns ...string) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Not(conds ...gen.Condition) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Or(conds ...gen.Condition) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Select(conds ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Where(conds ...gen.Condition) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3ClauseEvidenceDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3ClauseEvidenceDo) Order(conds ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Distinct(cols ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Omit(cols ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3ClauseEvidenceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3ClauseEvidenceDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Group(cols ...field.Expr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Having(conds ...gen.Condition) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Limit(limit int) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3ClauseEvidenceDo) Offset(offset int) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3ClauseEvidenceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Unscoped() *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3ClauseEvidenceDo) Create(values ...*model.BidAnalysisV3ClauseEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3ClauseEvidenceDo) CreateInBatches(values []*model.BidAnalysisV3ClauseEvidence, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3ClauseEvidenceDo) Save(values ...*model.BidAnalysisV3ClauseEvidence) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3ClauseEvidenceDo) First() (*model.BidAnalysisV3ClauseEvidence, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ClauseEvidence), nil
	}
}

func (b bidAnalysisV3ClauseEvidenceDo) Take() (*model.BidAnalysisV3ClauseEvidence, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ClauseEvidence), nil
	}
}

func (b bidAnalysisV3ClauseEvidenceDo) Last() (*model.BidAnalysisV3ClauseEvidence, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ClauseEvidence), nil
	}
}

func (b bidAnalysisV3ClauseEvidenceDo) Find() ([]*model.BidAnalysisV3ClauseEvidence, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3ClauseEvidence), err
}

func (b bidAnalysisV3ClauseEvidenceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3ClauseEvidence, err error) {
	buf := make([]*model.BidAnalysisV3ClauseEvidence, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3ClauseEvidenceDo) FindInBatches(result *[]*model.BidAnalysisV3ClauseEvidence, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3ClauseEvidenceDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3ClauseEvidenceDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3ClauseEvidenceDo) Joins(fields ...field.RelationField) *bidAnalysisV3ClauseEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3ClauseEvidenceDo) Preload(fields ...field.RelationField) *bidAnalysisV3ClauseEvidenceDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3ClauseEvidenceDo) FirstOrInit() (*model.BidAnalysisV3ClauseEvidence, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ClauseEvidence), nil
	}
}

func (b bidAnalysisV3ClauseEvidenceDo) FirstOrCreate() (*model.BidAnalysisV3ClauseEvidence, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3ClauseEvidence), nil
	}
}

func (b bidAnalysisV3ClauseEvidenceDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3ClauseEvidence, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3ClauseEvidenceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3ClauseEvidenceDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3ClauseEvidenceDo) Delete(models ...*model.BidAnalysisV3ClauseEvidence) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3ClauseEvidenceDo) withDO(do gen.Dao) *bidAnalysisV3ClauseEvidenceDo {
	b.DO = *do.(*gen.DO)
	return b
}
