// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidAnalysisV3Follow(db *gorm.DB, opts ...gen.DOOption) bidAnalysisV3Follow {
	_bidAnalysisV3Follow := bidAnalysisV3Follow{}

	_bidAnalysisV3Follow.bidAnalysisV3FollowDo.UseDB(db, opts...)
	_bidAnalysisV3Follow.bidAnalysisV3FollowDo.UseModel(&model.BidAnalysisV3Follow{})

	tableName := _bidAnalysisV3Follow.bidAnalysisV3FollowDo.TableName()
	_bidAnalysisV3Follow.ALL = field.NewAsterisk(tableName)
	_bidAnalysisV3Follow.ID = field.NewInt64(tableName, "id")
	_bidAnalysisV3Follow.ProjectID = field.NewInt64(tableName, "project_id")
	_bidAnalysisV3Follow.UserID = field.NewInt64(tableName, "user_id")
	_bidAnalysisV3Follow.TargetType = field.NewString(tableName, "target_type")
	_bidAnalysisV3Follow.TargetID = field.NewInt64(tableName, "target_id")
	_bidAnalysisV3Follow.Title = field.NewString(tableName, "title")
	_bidAnalysisV3Follow.Content = field.NewString(tableName, "content")
	_bidAnalysisV3Follow.Remark = field.NewString(tableName, "remark")
	_bidAnalysisV3Follow.CreatedAt = field.NewTime(tableName, "created_at")
	_bidAnalysisV3Follow.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidAnalysisV3Follow.fillFieldMap()

	return _bidAnalysisV3Follow
}

type bidAnalysisV3Follow struct {
	bidAnalysisV3FollowDo bidAnalysisV3FollowDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	ProjectID  field.Int64  // 招标解析项目ID
	UserID     field.Int64  // 用户ID
	TargetType field.String // 关注对象类型: field/clause
	TargetID   field.Int64  // 关注对象ID（字段或条款ID）
	Title      field.String // 关注项标题快照
	Content    field.String // 关注项内容/取值快照
	Remark     field.String // 用户备注
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidAnalysisV3Follow) Table(newTableName string) *bidAnalysisV3Follow {
	b.bidAnalysisV3FollowDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidAnalysisV3Follow) As(alias string) *bidAnalysisV3Follow {
	b.bidAnalysisV3FollowDo.DO = *(b.bidAnalysisV3FollowDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidAnalysisV3Follow) updateTableName(table string) *bidAnalysisV3Follow {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.UserID = field.NewInt64(table, "user_id")
	b.TargetType = field.NewString(table, "target_type")
	b.TargetID = field.NewInt64(table, "target_id")
	b.Title = field.NewString(table, "title")
	b.Content = field.NewString(table, "content")
	b.Remark = field.NewString(table, "remark")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidAnalysisV3Follow) WithContext(ctx context.Context) *bidAnalysisV3FollowDo {
	return b.bidAnalysisV3FollowDo.WithContext(ctx)
}

func (b bidAnalysisV3Follow) TableName() string { return b.bidAnalysisV3FollowDo.TableName() }

func (b bidAnalysisV3Follow) Alias() string { return b.bidAnalysisV3FollowDo.Alias() }

func (b *bidAnalysisV3Follow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidAnalysisV3Follow) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 10)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["target_type"] = b.TargetType
	b.fieldMap["target_id"] = b.TargetID
	b.fieldMap["title"] = b.Title
	b.fieldMap["content"] = b.Content
	b.fieldMap["remark"] = b.Remark
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidAnalysisV3Follow) clone(db *gorm.DB) bidAnalysisV3Follow {
	b.bidAnalysisV3FollowDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidAnalysisV3Follow) replaceDB(db *gorm.DB) bidAnalysisV3Follow {
	b.bidAnalysisV3FollowDo.ReplaceDB(db)
	return b
}

type bidAnalysisV3FollowDo struct{ gen.DO }

func (b bidAnalysisV3FollowDo) Debug() *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Debug())
}

func (b bidAnalysisV3FollowDo) WithContext(ctx context.Context) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidAnalysisV3FollowDo) ReadDB() *bidAnalysisV3FollowDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidAnalysisV3FollowDo) WriteDB() *bidAnalysisV3FollowDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidAnalysisV3FollowDo) Session(config *gorm.Session) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidAnalysisV3FollowDo) Clauses(conds ...clause.Expression) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidAnalysisV3FollowDo) Returning(value interface{}, columns ...string) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidAnalysisV3FollowDo) Not(conds ...gen.Condition) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidAnalysisV3FollowDo) Or(conds ...gen.Condition) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidAnalysisV3FollowDo) Select(conds ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidAnalysisV3FollowDo) Where(conds ...gen.Condition) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidAnalysisV3FollowDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidAnalysisV3FollowDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidAnalysisV3FollowDo) Order(conds ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidAnalysisV3FollowDo) Distinct(cols ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidAnalysisV3FollowDo) Omit(cols ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidAnalysisV3FollowDo) Join(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidAnalysisV3FollowDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidAnalysisV3FollowDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidAnalysisV3FollowDo) Group(cols ...field.Expr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidAnalysisV3FollowDo) Having(conds ...gen.Condition) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidAnalysisV3FollowDo) Limit(limit int) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidAnalysisV3FollowDo) Offset(offset int) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidAnalysisV3FollowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidAnalysisV3FollowDo) Unscoped() *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidAnalysisV3FollowDo) Create(values ...*model.BidAnalysisV3Follow) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidAnalysisV3FollowDo) CreateInBatches(values []*model.BidAnalysisV3Follow, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidAnalysisV3FollowDo) Save(values ...*model.BidAnalysisV3Follow) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidAnalysisV3FollowDo) First() (*model.BidAnalysisV3Follow, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Follow), nil
	}
}

func (b bidAnalysisV3FollowDo) Take() (*model.BidAnalysisV3Follow, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Follow), nil
	}
}

func (b bidAnalysisV3FollowDo) Last() (*model.BidAnalysisV3Follow, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Follow), nil
	}
}

func (b bidAnalysisV3FollowDo) Find() ([]*model.BidAnalysisV3Follow, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidAnalysisV3Follow), err
}

func (b bidAnalysisV3FollowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidAnalysisV3Follow, err error) {
	buf := make([]*model.BidAnalysisV3Follow, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidAnalysisV3FollowDo) FindInBatches(result *[]*model.BidAnalysisV3Follow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidAnalysisV3FollowDo) Attrs(attrs ...field.AssignExpr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidAnalysisV3FollowDo) Assign(attrs ...field.AssignExpr) *bidAnalysisV3FollowDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidAnalysisV3FollowDo) Joins(fields ...field.RelationField) *bidAnalysisV3FollowDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidAnalysisV3FollowDo) Preload(fields ...field.RelationField) *bidAnalysisV3FollowDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidAnalysisV3FollowDo) FirstOrInit() (*model.BidAnalysisV3Follow, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Follow), nil
	}
}

func (b bidAnalysisV3FollowDo) FirstOrCreate() (*model.BidAnalysisV3Follow, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidAnalysisV3Follow), nil
	}
}

func (b bidAnalysisV3FollowDo) FindByPage(offset int, limit int) (result []*model.BidAnalysisV3Follow, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidAnalysisV3FollowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidAnalysisV3FollowDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidAnalysisV3FollowDo) Delete(models ...*model.BidAnalysisV3Follow) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidAnalysisV3FollowDo) withDO(do gen.Dao) *bidAnalysisV3FollowDo {
	b.DO = *do.(*gen.DO)
	return b
}
