// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidReviewFile(db *gorm.DB, opts ...gen.DOOption) bidReviewFile {
	_bidReviewFile := bidReviewFile{}

	_bidReviewFile.bidReviewFileDo.UseDB(db, opts...)
	_bidReviewFile.bidReviewFileDo.UseModel(&model.BidReviewFile{})

	tableName := _bidReviewFile.bidReviewFileDo.TableName()
	_bidReviewFile.ALL = field.NewAsterisk(tableName)
	_bidReviewFile.ID = field.NewInt64(tableName, "id")
	_bidReviewFile.ProjectID = field.NewInt64(tableName, "project_id")
	_bidReviewFile.FileType = field.NewString(tableName, "file_type")
	_bidReviewFile.FileName = field.NewString(tableName, "file_name")
	_bidReviewFile.FileBucket = field.NewString(tableName, "file_bucket")
	_bidReviewFile.FileObject = field.NewString(tableName, "file_object")
	_bidReviewFile.FileURL = field.NewString(tableName, "file_url")
	_bidReviewFile.PdfObject = field.NewString(tableName, "pdf_object")
	_bidReviewFile.PdfURL = field.NewString(tableName, "pdf_url")
	_bidReviewFile.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidReviewFile.ParseStatus = field.NewString(tableName, "parse_status")
	_bidReviewFile.CreatedAt = field.NewTime(tableName, "created_at")
	_bidReviewFile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidReviewFile.fillFieldMap()

	return _bidReviewFile
}

type bidReviewFile struct {
	bidReviewFileDo bidReviewFileDo

	ALL         field.Asterisk
	ID          field.Int64
	ProjectID   field.Int64  // 审核项目ID
	FileType    field.String // tender-招标文件, bid-投标文件
	FileName    field.String // 原始文件名
	FileBucket  field.String // 存储桶
	FileObject  field.String // 对象键
	FileURL     field.String // 访问URL
	PdfObject   field.String // 转PDF后的对象键
	PdfURL      field.String // 转PDF后的访问URL
	SortOrder   field.Int32  // 展示排序（从1开始）
	ParseStatus field.String // 解析状态: pending/parsed/failed
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidReviewFile) Table(newTableName string) *bidReviewFile {
	b.bidReviewFileDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidReviewFile) As(alias string) *bidReviewFile {
	b.bidReviewFileDo.DO = *(b.bidReviewFileDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidReviewFile) updateTableName(table string) *bidReviewFile {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.FileType = field.NewString(table, "file_type")
	b.FileName = field.NewString(table, "file_name")
	b.FileBucket = field.NewString(table, "file_bucket")
	b.FileObject = field.NewString(table, "file_object")
	b.FileURL = field.NewString(table, "file_url")
	b.PdfObject = field.NewString(table, "pdf_object")
	b.PdfURL = field.NewString(table, "pdf_url")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.ParseStatus = field.NewString(table, "parse_status")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidReviewFile) WithContext(ctx context.Context) *bidReviewFileDo {
	return b.bidReviewFileDo.WithContext(ctx)
}

func (b bidReviewFile) TableName() string { return b.bidReviewFileDo.TableName() }

func (b bidReviewFile) Alias() string { return b.bidReviewFileDo.Alias() }

func (b *bidReviewFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidReviewFile) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 13)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["file_type"] = b.FileType
	b.fieldMap["file_name"] = b.FileName
	b.fieldMap["file_bucket"] = b.FileBucket
	b.fieldMap["file_object"] = b.FileObject
	b.fieldMap["file_url"] = b.FileURL
	b.fieldMap["pdf_object"] = b.PdfObject
	b.fieldMap["pdf_url"] = b.PdfURL
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["parse_status"] = b.ParseStatus
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidReviewFile) clone(db *gorm.DB) bidReviewFile {
	b.bidReviewFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidReviewFile) replaceDB(db *gorm.DB) bidReviewFile {
	b.bidReviewFileDo.ReplaceDB(db)
	return b
}

type bidReviewFileDo struct{ gen.DO }

func (b bidReviewFileDo) Debug() *bidReviewFileDo {
	return b.withDO(b.DO.Debug())
}

func (b bidReviewFileDo) WithContext(ctx context.Context) *bidReviewFileDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidReviewFileDo) ReadDB() *bidReviewFileDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidReviewFileDo) WriteDB() *bidReviewFileDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidReviewFileDo) Session(config *gorm.Session) *bidReviewFileDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidReviewFileDo) Clauses(conds ...clause.Expression) *bidReviewFileDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidReviewFileDo) Returning(value interface{}, columns ...string) *bidReviewFileDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidReviewFileDo) Not(conds ...gen.Condition) *bidReviewFileDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidReviewFileDo) Or(conds ...gen.Condition) *bidReviewFileDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidReviewFileDo) Select(conds ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidReviewFileDo) Where(conds ...gen.Condition) *bidReviewFileDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidReviewFileDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidReviewFileDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidReviewFileDo) Order(conds ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidReviewFileDo) Distinct(cols ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidReviewFileDo) Omit(cols ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidReviewFileDo) Join(table schema.Tabler, on ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidReviewFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidReviewFileDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidReviewFileDo) Group(cols ...field.Expr) *bidReviewFileDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidReviewFileDo) Having(conds ...gen.Condition) *bidReviewFileDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidReviewFileDo) Limit(limit int) *bidReviewFileDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidReviewFileDo) Offset(offset int) *bidReviewFileDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidReviewFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidReviewFileDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidReviewFileDo) Unscoped() *bidReviewFileDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidReviewFileDo) Create(values ...*model.BidReviewFile) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidReviewFileDo) CreateInBatches(values []*model.BidReviewFile, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidReviewFileDo) Save(values ...*model.BidReviewFile) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidReviewFileDo) First() (*model.BidReviewFile, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewFile), nil
	}
}

func (b bidReviewFileDo) Take() (*model.BidReviewFile, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewFile), nil
	}
}

func (b bidReviewFileDo) Last() (*model.BidReviewFile, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewFile), nil
	}
}

func (b bidReviewFileDo) Find() ([]*model.BidReviewFile, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidReviewFile), err
}

func (b bidReviewFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidReviewFile, err error) {
	buf := make([]*model.BidReviewFile, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidReviewFileDo) FindInBatches(result *[]*model.BidReviewFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidReviewFileDo) Attrs(attrs ...field.AssignExpr) *bidReviewFileDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidReviewFileDo) Assign(attrs ...field.AssignExpr) *bidReviewFileDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidReviewFileDo) Joins(fields ...field.RelationField) *bidReviewFileDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidReviewFileDo) Preload(fields ...field.RelationField) *bidReviewFileDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidReviewFileDo) FirstOrInit() (*model.BidReviewFile, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewFile), nil
	}
}

func (b bidReviewFileDo) FirstOrCreate() (*model.BidReviewFile, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewFile), nil
	}
}

func (b bidReviewFileDo) FindByPage(offset int, limit int) (result []*model.BidReviewFile, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidReviewFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidReviewFileDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidReviewFileDo) Delete(models ...*model.BidReviewFile) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidReviewFileDo) withDO(do gen.Dao) *bidReviewFileDo {
	b.DO = *do.(*gen.DO)
	return b
}
