// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newBidReviewCheckItem(db *gorm.DB, opts ...gen.DOOption) bidReviewCheckItem {
	_bidReviewCheckItem := bidReviewCheckItem{}

	_bidReviewCheckItem.bidReviewCheckItemDo.UseDB(db, opts...)
	_bidReviewCheckItem.bidReviewCheckItemDo.UseModel(&model.BidReviewCheckItem{})

	tableName := _bidReviewCheckItem.bidReviewCheckItemDo.TableName()
	_bidReviewCheckItem.ALL = field.NewAsterisk(tableName)
	_bidReviewCheckItem.ID = field.NewInt64(tableName, "id")
	_bidReviewCheckItem.ProjectID = field.NewInt64(tableName, "project_id")
	_bidReviewCheckItem.Category = field.NewString(tableName, "category")
	_bidReviewCheckItem.Name = field.NewString(tableName, "name")
	_bidReviewCheckItem.Source = field.NewString(tableName, "source")
	_bidReviewCheckItem.Severity = field.NewString(tableName, "severity")
	_bidReviewCheckItem.AiStatus = field.NewString(tableName, "ai_status")
	_bidReviewCheckItem.TenderRequirement = field.NewString(tableName, "tender_requirement")
	_bidReviewCheckItem.BidContent = field.NewString(tableName, "bid_content")
	_bidReviewCheckItem.Suggestion = field.NewString(tableName, "suggestion")
	_bidReviewCheckItem.TenderTrace = field.NewString(tableName, "tender_trace")
	_bidReviewCheckItem.BidTrace = field.NewString(tableName, "bid_trace")
	_bidReviewCheckItem.ReviewStatus = field.NewString(tableName, "review_status")
	_bidReviewCheckItem.Note = field.NewString(tableName, "note")
	_bidReviewCheckItem.ReviewedBy = field.NewInt64(tableName, "reviewed_by")
	_bidReviewCheckItem.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_bidReviewCheckItem.SortOrder = field.NewInt32(tableName, "sort_order")
	_bidReviewCheckItem.CreatedAt = field.NewTime(tableName, "created_at")
	_bidReviewCheckItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_bidReviewCheckItem.fillFieldMap()

	return _bidReviewCheckItem
}

type bidReviewCheckItem struct {
	bidReviewCheckItemDo bidReviewCheckItemDo

	ALL               field.Asterisk
	ID                field.Int64
	ProjectID         field.Int64  // 审核项目ID
	Category          field.String // 分类: compliance-符合性, completeness-完整性, error-错误排查, anonymous-暗标
	Name              field.String // 检查项名称
	Source            field.String // 来源: preset-预置, ai-AI生成, user-用户自定义
	Severity          field.String // 级别: high/medium/low
	AiStatus          field.String // AI/系统结论: pass/warning/error
	TenderRequirement field.String // 招标要求（招标侧值）
	BidContent        field.String // 投标内容（投标侧值）
	Suggestion        field.String // 整改建议
	TenderTrace       field.String // 招标溯源JSON: [{fileId,fileName,page,quote}]
	BidTrace          field.String // 投标溯源JSON: [{fileId,fileName,page,quote}]
	ReviewStatus      field.String // 人工确认状态: pending/confirmed/needs_fix/na
	Note              field.String // 审核备注
	ReviewedBy        field.Int64  // 确认人ID
	ReviewedAt        field.Time   // 确认时间
	SortOrder         field.Int32  // 展示排序
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (b bidReviewCheckItem) Table(newTableName string) *bidReviewCheckItem {
	b.bidReviewCheckItemDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bidReviewCheckItem) As(alias string) *bidReviewCheckItem {
	b.bidReviewCheckItemDo.DO = *(b.bidReviewCheckItemDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bidReviewCheckItem) updateTableName(table string) *bidReviewCheckItem {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.ProjectID = field.NewInt64(table, "project_id")
	b.Category = field.NewString(table, "category")
	b.Name = field.NewString(table, "name")
	b.Source = field.NewString(table, "source")
	b.Severity = field.NewString(table, "severity")
	b.AiStatus = field.NewString(table, "ai_status")
	b.TenderRequirement = field.NewString(table, "tender_requirement")
	b.BidContent = field.NewString(table, "bid_content")
	b.Suggestion = field.NewString(table, "suggestion")
	b.TenderTrace = field.NewString(table, "tender_trace")
	b.BidTrace = field.NewString(table, "bid_trace")
	b.ReviewStatus = field.NewString(table, "review_status")
	b.Note = field.NewString(table, "note")
	b.ReviewedBy = field.NewInt64(table, "reviewed_by")
	b.ReviewedAt = field.NewTime(table, "reviewed_at")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *bidReviewCheckItem) WithContext(ctx context.Context) *bidReviewCheckItemDo {
	return b.bidReviewCheckItemDo.WithContext(ctx)
}

func (b bidReviewCheckItem) TableName() string { return b.bidReviewCheckItemDo.TableName() }

func (b bidReviewCheckItem) Alias() string { return b.bidReviewCheckItemDo.Alias() }

func (b *bidReviewCheckItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bidReviewCheckItem) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 19)
	b.fieldMap["id"] = b.ID
	b.fieldMap["project_id"] = b.ProjectID
	b.fieldMap["category"] = b.Category
	b.fieldMap["name"] = b.Name
	b.fieldMap["source"] = b.Source
	b.fieldMap["severity"] = b.Severity
	b.fieldMap["ai_status"] = b.AiStatus
	b.fieldMap["tender_requirement"] = b.TenderRequirement
	b.fieldMap["bid_content"] = b.BidContent
	b.fieldMap["suggestion"] = b.Suggestion
	b.fieldMap["tender_trace"] = b.TenderTrace
	b.fieldMap["bid_trace"] = b.BidTrace
	b.fieldMap["review_status"] = b.ReviewStatus
	b.fieldMap["note"] = b.Note
	b.fieldMap["reviewed_by"] = b.ReviewedBy
	b.fieldMap["reviewed_at"] = b.ReviewedAt
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b bidReviewCheckItem) clone(db *gorm.DB) bidReviewCheckItem {
	b.bidReviewCheckItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bidReviewCheckItem) replaceDB(db *gorm.DB) bidReviewCheckItem {
	b.bidReviewCheckItemDo.ReplaceDB(db)
	return b
}

type bidReviewCheckItemDo struct{ gen.DO }

func (b bidReviewCheckItemDo) Debug() *bidReviewCheckItemDo {
	return b.withDO(b.DO.Debug())
}

func (b bidReviewCheckItemDo) WithContext(ctx context.Context) *bidReviewCheckItemDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bidReviewCheckItemDo) ReadDB() *bidReviewCheckItemDo {
	return b.Clauses(dbresolver.Read)
}

func (b bidReviewCheckItemDo) WriteDB() *bidReviewCheckItemDo {
	return b.Clauses(dbresolver.Write)
}

func (b bidReviewCheckItemDo) Session(config *gorm.Session) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Session(config))
}

func (b bidReviewCheckItemDo) Clauses(conds ...clause.Expression) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bidReviewCheckItemDo) Returning(value interface{}, columns ...string) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bidReviewCheckItemDo) Not(conds ...gen.Condition) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bidReviewCheckItemDo) Or(conds ...gen.Condition) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bidReviewCheckItemDo) Select(conds ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bidReviewCheckItemDo) Where(conds ...gen.Condition) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bidReviewCheckItemDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *bidReviewCheckItemDo {
	return b.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (b bidReviewCheckItemDo) Order(conds ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bidReviewCheckItemDo) Distinct(cols ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bidReviewCheckItemDo) Omit(cols ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bidReviewCheckItemDo) Join(table schema.Tabler, on ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bidReviewCheckItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bidReviewCheckItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bidReviewCheckItemDo) Group(cols ...field.Expr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bidReviewCheckItemDo) Having(conds ...gen.Condition) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bidReviewCheckItemDo) Limit(limit int) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bidReviewCheckItemDo) Offset(offset int) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bidReviewCheckItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bidReviewCheckItemDo) Unscoped() *bidReviewCheckItemDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bidReviewCheckItemDo) Create(values ...*model.BidReviewCheckItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bidReviewCheckItemDo) CreateInBatches(values []*model.BidReviewCheckItem, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bidReviewCheckItemDo) Save(values ...*model.BidReviewCheckItem) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bidReviewCheckItemDo) First() (*model.BidReviewCheckItem, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewCheckItem), nil
	}
}

func (b bidReviewCheckItemDo) Take() (*model.BidReviewCheckItem, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewCheckItem), nil
	}
}

func (b bidReviewCheckItemDo) Last() (*model.BidReviewCheckItem, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewCheckItem), nil
	}
}

func (b bidReviewCheckItemDo) Find() ([]*model.BidReviewCheckItem, error) {
	result, err := b.DO.Find()
	return result.([]*model.BidReviewCheckItem), err
}

func (b bidReviewCheckItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BidReviewCheckItem, err error) {
	buf := make([]*model.BidReviewCheckItem, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bidReviewCheckItemDo) FindInBatches(result *[]*model.BidReviewCheckItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bidReviewCheckItemDo) Attrs(attrs ...field.AssignExpr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bidReviewCheckItemDo) Assign(attrs ...field.AssignExpr) *bidReviewCheckItemDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bidReviewCheckItemDo) Joins(fields ...field.RelationField) *bidReviewCheckItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bidReviewCheckItemDo) Preload(fields ...field.RelationField) *bidReviewCheckItemDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bidReviewCheckItemDo) FirstOrInit() (*model.BidReviewCheckItem, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewCheckItem), nil
	}
}

func (b bidReviewCheckItemDo) FirstOrCreate() (*model.BidReviewCheckItem, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BidReviewCheckItem), nil
	}
}

func (b bidReviewCheckItemDo) FindByPage(offset int, limit int) (result []*model.BidReviewCheckItem, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bidReviewCheckItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bidReviewCheckItemDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bidReviewCheckItemDo) Delete(models ...*model.BidReviewCheckItem) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bidReviewCheckItemDo) withDO(do gen.Dao) *bidReviewCheckItemDo {
	b.DO = *do.(*gen.DO)
	return b
}
