// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newEnterpriseTemplate(db *gorm.DB, opts ...gen.DOOption) enterpriseTemplate {
	_enterpriseTemplate := enterpriseTemplate{}

	_enterpriseTemplate.enterpriseTemplateDo.UseDB(db, opts...)
	_enterpriseTemplate.enterpriseTemplateDo.UseModel(&model.EnterpriseTemplate{})

	tableName := _enterpriseTemplate.enterpriseTemplateDo.TableName()
	_enterpriseTemplate.ALL = field.NewAsterisk(tableName)
	_enterpriseTemplate.ID = field.NewString(tableName, "id")
	_enterpriseTemplate.TemplateName = field.NewString(tableName, "template_name")
	_enterpriseTemplate.TemplateDescription = field.NewString(tableName, "template_description")
	_enterpriseTemplate.DocumentPermission = field.NewString(tableName, "document_permission")
	_enterpriseTemplate.AttachmentPath = field.NewString(tableName, "attachment_path")
	_enterpriseTemplate.AttachmentName = field.NewString(tableName, "attachment_name")
	_enterpriseTemplate.CompanyID = field.NewInt32(tableName, "company_id")
	_enterpriseTemplate.TeamID = field.NewInt32(tableName, "team_id")
	_enterpriseTemplate.CreatedBy = field.NewInt32(tableName, "created_by")
	_enterpriseTemplate.CreatedAt = field.NewInt64(tableName, "created_at")
	_enterpriseTemplate.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_enterpriseTemplate.fillFieldMap()

	return _enterpriseTemplate
}

type enterpriseTemplate struct {
	enterpriseTemplateDo enterpriseTemplateDo

	ALL                 field.Asterisk
	ID                  field.String
	TemplateName        field.String // 模板名称
	TemplateDescription field.String // 模板描述
	DocumentPermission  field.String // 文档权限
	AttachmentPath      field.String // 附件
	AttachmentName      field.String // 附件名称
	CompanyID           field.Int32  // 所属公司ID
	TeamID              field.Int32  // 所属团队Id
	CreatedBy           field.Int32  // 创建人
	CreatedAt           field.Int64  // 创建时间
	UpdatedAt           field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (e enterpriseTemplate) Table(newTableName string) *enterpriseTemplate {
	e.enterpriseTemplateDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e enterpriseTemplate) As(alias string) *enterpriseTemplate {
	e.enterpriseTemplateDo.DO = *(e.enterpriseTemplateDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *enterpriseTemplate) updateTableName(table string) *enterpriseTemplate {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.TemplateName = field.NewString(table, "template_name")
	e.TemplateDescription = field.NewString(table, "template_description")
	e.DocumentPermission = field.NewString(table, "document_permission")
	e.AttachmentPath = field.NewString(table, "attachment_path")
	e.AttachmentName = field.NewString(table, "attachment_name")
	e.CompanyID = field.NewInt32(table, "company_id")
	e.TeamID = field.NewInt32(table, "team_id")
	e.CreatedBy = field.NewInt32(table, "created_by")
	e.CreatedAt = field.NewInt64(table, "created_at")
	e.UpdatedAt = field.NewInt64(table, "updated_at")

	e.fillFieldMap()

	return e
}

func (e *enterpriseTemplate) WithContext(ctx context.Context) *enterpriseTemplateDo {
	return e.enterpriseTemplateDo.WithContext(ctx)
}

func (e enterpriseTemplate) TableName() string { return e.enterpriseTemplateDo.TableName() }

func (e enterpriseTemplate) Alias() string { return e.enterpriseTemplateDo.Alias() }

func (e *enterpriseTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *enterpriseTemplate) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["template_name"] = e.TemplateName
	e.fieldMap["template_description"] = e.TemplateDescription
	e.fieldMap["document_permission"] = e.DocumentPermission
	e.fieldMap["attachment_path"] = e.AttachmentPath
	e.fieldMap["attachment_name"] = e.AttachmentName
	e.fieldMap["company_id"] = e.CompanyID
	e.fieldMap["team_id"] = e.TeamID
	e.fieldMap["created_by"] = e.CreatedBy
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["updated_at"] = e.UpdatedAt
}

func (e enterpriseTemplate) clone(db *gorm.DB) enterpriseTemplate {
	e.enterpriseTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e enterpriseTemplate) replaceDB(db *gorm.DB) enterpriseTemplate {
	e.enterpriseTemplateDo.ReplaceDB(db)
	return e
}

type enterpriseTemplateDo struct{ gen.DO }

func (e enterpriseTemplateDo) Debug() *enterpriseTemplateDo {
	return e.withDO(e.DO.Debug())
}

func (e enterpriseTemplateDo) WithContext(ctx context.Context) *enterpriseTemplateDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e enterpriseTemplateDo) ReadDB() *enterpriseTemplateDo {
	return e.Clauses(dbresolver.Read)
}

func (e enterpriseTemplateDo) WriteDB() *enterpriseTemplateDo {
	return e.Clauses(dbresolver.Write)
}

func (e enterpriseTemplateDo) Session(config *gorm.Session) *enterpriseTemplateDo {
	return e.withDO(e.DO.Session(config))
}

func (e enterpriseTemplateDo) Clauses(conds ...clause.Expression) *enterpriseTemplateDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e enterpriseTemplateDo) Returning(value interface{}, columns ...string) *enterpriseTemplateDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e enterpriseTemplateDo) Not(conds ...gen.Condition) *enterpriseTemplateDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e enterpriseTemplateDo) Or(conds ...gen.Condition) *enterpriseTemplateDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e enterpriseTemplateDo) Select(conds ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e enterpriseTemplateDo) Where(conds ...gen.Condition) *enterpriseTemplateDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e enterpriseTemplateDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *enterpriseTemplateDo {
	return e.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (e enterpriseTemplateDo) Order(conds ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e enterpriseTemplateDo) Distinct(cols ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e enterpriseTemplateDo) Omit(cols ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e enterpriseTemplateDo) Join(table schema.Tabler, on ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e enterpriseTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e enterpriseTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e enterpriseTemplateDo) Group(cols ...field.Expr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e enterpriseTemplateDo) Having(conds ...gen.Condition) *enterpriseTemplateDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e enterpriseTemplateDo) Limit(limit int) *enterpriseTemplateDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e enterpriseTemplateDo) Offset(offset int) *enterpriseTemplateDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e enterpriseTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *enterpriseTemplateDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e enterpriseTemplateDo) Unscoped() *enterpriseTemplateDo {
	return e.withDO(e.DO.Unscoped())
}

func (e enterpriseTemplateDo) Create(values ...*model.EnterpriseTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e enterpriseTemplateDo) CreateInBatches(values []*model.EnterpriseTemplate, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e enterpriseTemplateDo) Save(values ...*model.EnterpriseTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e enterpriseTemplateDo) First() (*model.EnterpriseTemplate, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EnterpriseTemplate), nil
	}
}

func (e enterpriseTemplateDo) Take() (*model.EnterpriseTemplate, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EnterpriseTemplate), nil
	}
}

func (e enterpriseTemplateDo) Last() (*model.EnterpriseTemplate, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EnterpriseTemplate), nil
	}
}

func (e enterpriseTemplateDo) Find() ([]*model.EnterpriseTemplate, error) {
	result, err := e.DO.Find()
	return result.([]*model.EnterpriseTemplate), err
}

func (e enterpriseTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EnterpriseTemplate, err error) {
	buf := make([]*model.EnterpriseTemplate, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e enterpriseTemplateDo) FindInBatches(result *[]*model.EnterpriseTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e enterpriseTemplateDo) Attrs(attrs ...field.AssignExpr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e enterpriseTemplateDo) Assign(attrs ...field.AssignExpr) *enterpriseTemplateDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e enterpriseTemplateDo) Joins(fields ...field.RelationField) *enterpriseTemplateDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e enterpriseTemplateDo) Preload(fields ...field.RelationField) *enterpriseTemplateDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e enterpriseTemplateDo) FirstOrInit() (*model.EnterpriseTemplate, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EnterpriseTemplate), nil
	}
}

func (e enterpriseTemplateDo) FirstOrCreate() (*model.EnterpriseTemplate, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EnterpriseTemplate), nil
	}
}

func (e enterpriseTemplateDo) FindByPage(offset int, limit int) (result []*model.EnterpriseTemplate, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e enterpriseTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e enterpriseTemplateDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e enterpriseTemplateDo) Delete(models ...*model.EnterpriseTemplate) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *enterpriseTemplateDo) withDO(do gen.Dao) *enterpriseTemplateDo {
	e.DO = *do.(*gen.DO)
	return e
}
