// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newKv(db *gorm.DB, opts ...gen.DOOption) kv {
	_kv := kv{}

	_kv.kvDo.UseDB(db, opts...)
	_kv.kvDo.UseModel(&model.Kv{})

	tableName := _kv.kvDo.TableName()
	_kv.ALL = field.NewAsterisk(tableName)
	_kv.Key = field.NewString(tableName, "key")
	_kv.Value = field.NewString(tableName, "value")

	_kv.fillFieldMap()

	return _kv
}

type kv struct {
	kvDo kvDo

	ALL   field.Asterisk
	Key   field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (k kv) Table(newTableName string) *kv {
	k.kvDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kv) As(alias string) *kv {
	k.kvDo.DO = *(k.kvDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kv) updateTableName(table string) *kv {
	k.ALL = field.NewAsterisk(table)
	k.Key = field.NewString(table, "key")
	k.Value = field.NewString(table, "value")

	k.fillFieldMap()

	return k
}

func (k *kv) WithContext(ctx context.Context) *kvDo { return k.kvDo.WithContext(ctx) }

func (k kv) TableName() string { return k.kvDo.TableName() }

func (k kv) Alias() string { return k.kvDo.Alias() }

func (k *kv) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kv) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 2)
	k.fieldMap["key"] = k.Key
	k.fieldMap["value"] = k.Value
}

func (k kv) clone(db *gorm.DB) kv {
	k.kvDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kv) replaceDB(db *gorm.DB) kv {
	k.kvDo.ReplaceDB(db)
	return k
}

type kvDo struct{ gen.DO }

func (k kvDo) Debug() *kvDo {
	return k.withDO(k.DO.Debug())
}

func (k kvDo) WithContext(ctx context.Context) *kvDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kvDo) ReadDB() *kvDo {
	return k.Clauses(dbresolver.Read)
}

func (k kvDo) WriteDB() *kvDo {
	return k.Clauses(dbresolver.Write)
}

func (k kvDo) Session(config *gorm.Session) *kvDo {
	return k.withDO(k.DO.Session(config))
}

func (k kvDo) Clauses(conds ...clause.Expression) *kvDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kvDo) Returning(value interface{}, columns ...string) *kvDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kvDo) Not(conds ...gen.Condition) *kvDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kvDo) Or(conds ...gen.Condition) *kvDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kvDo) Select(conds ...field.Expr) *kvDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kvDo) Where(conds ...gen.Condition) *kvDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kvDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *kvDo {
	return k.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (k kvDo) Order(conds ...field.Expr) *kvDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kvDo) Distinct(cols ...field.Expr) *kvDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kvDo) Omit(cols ...field.Expr) *kvDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kvDo) Join(table schema.Tabler, on ...field.Expr) *kvDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kvDo) LeftJoin(table schema.Tabler, on ...field.Expr) *kvDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kvDo) RightJoin(table schema.Tabler, on ...field.Expr) *kvDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kvDo) Group(cols ...field.Expr) *kvDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kvDo) Having(conds ...gen.Condition) *kvDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kvDo) Limit(limit int) *kvDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kvDo) Offset(offset int) *kvDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kvDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *kvDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kvDo) Unscoped() *kvDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kvDo) Create(values ...*model.Kv) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kvDo) CreateInBatches(values []*model.Kv, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kvDo) Save(values ...*model.Kv) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kvDo) First() (*model.Kv, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kv), nil
	}
}

func (k kvDo) Take() (*model.Kv, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kv), nil
	}
}

func (k kvDo) Last() (*model.Kv, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kv), nil
	}
}

func (k kvDo) Find() ([]*model.Kv, error) {
	result, err := k.DO.Find()
	return result.([]*model.Kv), err
}

func (k kvDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Kv, err error) {
	buf := make([]*model.Kv, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kvDo) FindInBatches(result *[]*model.Kv, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kvDo) Attrs(attrs ...field.AssignExpr) *kvDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kvDo) Assign(attrs ...field.AssignExpr) *kvDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kvDo) Joins(fields ...field.RelationField) *kvDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kvDo) Preload(fields ...field.RelationField) *kvDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kvDo) FirstOrInit() (*model.Kv, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kv), nil
	}
}

func (k kvDo) FirstOrCreate() (*model.Kv, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Kv), nil
	}
}

func (k kvDo) FindByPage(offset int, limit int) (result []*model.Kv, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kvDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kvDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kvDo) Delete(models ...*model.Kv) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kvDo) withDO(do gen.Dao) *kvDo {
	k.DO = *do.(*gen.DO)
	return k
}
