// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newMaterialFileInfo(db *gorm.DB, opts ...gen.DOOption) materialFileInfo {
	_materialFileInfo := materialFileInfo{}

	_materialFileInfo.materialFileInfoDo.UseDB(db, opts...)
	_materialFileInfo.materialFileInfoDo.UseModel(&model.MaterialFileInfo{})

	tableName := _materialFileInfo.materialFileInfoDo.TableName()
	_materialFileInfo.ALL = field.NewAsterisk(tableName)
	_materialFileInfo.ID = field.NewInt64(tableName, "id")
	_materialFileInfo.MaterialID = field.NewInt64(tableName, "material_id")
	_materialFileInfo.Name = field.NewString(tableName, "name")
	_materialFileInfo.Description = field.NewString(tableName, "description")
	_materialFileInfo.Size = field.NewInt64(tableName, "size")
	_materialFileInfo.ObjectKey = field.NewString(tableName, "object_key")
	_materialFileInfo.SortOrder = field.NewInt32(tableName, "sort_order")
	_materialFileInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_materialFileInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_materialFileInfo.fillFieldMap()

	return _materialFileInfo
}

type materialFileInfo struct {
	materialFileInfoDo materialFileInfoDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键ID
	MaterialID  field.Int64  // 素材ID，关联material_info表主键ID
	Name        field.String // 文档名称
	Description field.String // 文档描述
	Size        field.Int64  // 文档大小，单位bytes
	ObjectKey   field.String // 对象存储objectKey
	SortOrder   field.Int32  // 页码索引
	CreatedAt   field.Time   // 上传时间
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m materialFileInfo) Table(newTableName string) *materialFileInfo {
	m.materialFileInfoDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m materialFileInfo) As(alias string) *materialFileInfo {
	m.materialFileInfoDo.DO = *(m.materialFileInfoDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *materialFileInfo) updateTableName(table string) *materialFileInfo {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.MaterialID = field.NewInt64(table, "material_id")
	m.Name = field.NewString(table, "name")
	m.Description = field.NewString(table, "description")
	m.Size = field.NewInt64(table, "size")
	m.ObjectKey = field.NewString(table, "object_key")
	m.SortOrder = field.NewInt32(table, "sort_order")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *materialFileInfo) WithContext(ctx context.Context) *materialFileInfoDo {
	return m.materialFileInfoDo.WithContext(ctx)
}

func (m materialFileInfo) TableName() string { return m.materialFileInfoDo.TableName() }

func (m materialFileInfo) Alias() string { return m.materialFileInfoDo.Alias() }

func (m *materialFileInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *materialFileInfo) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["material_id"] = m.MaterialID
	m.fieldMap["name"] = m.Name
	m.fieldMap["description"] = m.Description
	m.fieldMap["size"] = m.Size
	m.fieldMap["object_key"] = m.ObjectKey
	m.fieldMap["sort_order"] = m.SortOrder
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m materialFileInfo) clone(db *gorm.DB) materialFileInfo {
	m.materialFileInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m materialFileInfo) replaceDB(db *gorm.DB) materialFileInfo {
	m.materialFileInfoDo.ReplaceDB(db)
	return m
}

type materialFileInfoDo struct{ gen.DO }

func (m materialFileInfoDo) Debug() *materialFileInfoDo {
	return m.withDO(m.DO.Debug())
}

func (m materialFileInfoDo) WithContext(ctx context.Context) *materialFileInfoDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m materialFileInfoDo) ReadDB() *materialFileInfoDo {
	return m.Clauses(dbresolver.Read)
}

func (m materialFileInfoDo) WriteDB() *materialFileInfoDo {
	return m.Clauses(dbresolver.Write)
}

func (m materialFileInfoDo) Session(config *gorm.Session) *materialFileInfoDo {
	return m.withDO(m.DO.Session(config))
}

func (m materialFileInfoDo) Clauses(conds ...clause.Expression) *materialFileInfoDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m materialFileInfoDo) Returning(value interface{}, columns ...string) *materialFileInfoDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m materialFileInfoDo) Not(conds ...gen.Condition) *materialFileInfoDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m materialFileInfoDo) Or(conds ...gen.Condition) *materialFileInfoDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m materialFileInfoDo) Select(conds ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m materialFileInfoDo) Where(conds ...gen.Condition) *materialFileInfoDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m materialFileInfoDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *materialFileInfoDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m materialFileInfoDo) Order(conds ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m materialFileInfoDo) Distinct(cols ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m materialFileInfoDo) Omit(cols ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m materialFileInfoDo) Join(table schema.Tabler, on ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m materialFileInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m materialFileInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m materialFileInfoDo) Group(cols ...field.Expr) *materialFileInfoDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m materialFileInfoDo) Having(conds ...gen.Condition) *materialFileInfoDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m materialFileInfoDo) Limit(limit int) *materialFileInfoDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m materialFileInfoDo) Offset(offset int) *materialFileInfoDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m materialFileInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *materialFileInfoDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m materialFileInfoDo) Unscoped() *materialFileInfoDo {
	return m.withDO(m.DO.Unscoped())
}

func (m materialFileInfoDo) Create(values ...*model.MaterialFileInfo) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m materialFileInfoDo) CreateInBatches(values []*model.MaterialFileInfo, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m materialFileInfoDo) Save(values ...*model.MaterialFileInfo) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m materialFileInfoDo) First() (*model.MaterialFileInfo, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialFileInfo), nil
	}
}

func (m materialFileInfoDo) Take() (*model.MaterialFileInfo, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialFileInfo), nil
	}
}

func (m materialFileInfoDo) Last() (*model.MaterialFileInfo, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialFileInfo), nil
	}
}

func (m materialFileInfoDo) Find() ([]*model.MaterialFileInfo, error) {
	result, err := m.DO.Find()
	return result.([]*model.MaterialFileInfo), err
}

func (m materialFileInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MaterialFileInfo, err error) {
	buf := make([]*model.MaterialFileInfo, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m materialFileInfoDo) FindInBatches(result *[]*model.MaterialFileInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m materialFileInfoDo) Attrs(attrs ...field.AssignExpr) *materialFileInfoDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m materialFileInfoDo) Assign(attrs ...field.AssignExpr) *materialFileInfoDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m materialFileInfoDo) Joins(fields ...field.RelationField) *materialFileInfoDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m materialFileInfoDo) Preload(fields ...field.RelationField) *materialFileInfoDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m materialFileInfoDo) FirstOrInit() (*model.MaterialFileInfo, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialFileInfo), nil
	}
}

func (m materialFileInfoDo) FirstOrCreate() (*model.MaterialFileInfo, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialFileInfo), nil
	}
}

func (m materialFileInfoDo) FindByPage(offset int, limit int) (result []*model.MaterialFileInfo, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m materialFileInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m materialFileInfoDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m materialFileInfoDo) Delete(models ...*model.MaterialFileInfo) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *materialFileInfoDo) withDO(do gen.Dao) *materialFileInfoDo {
	m.DO = *do.(*gen.DO)
	return m
}
