// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newMaterialPerformance(db *gorm.DB, opts ...gen.DOOption) materialPerformance {
	_materialPerformance := materialPerformance{}

	_materialPerformance.materialPerformanceDo.UseDB(db, opts...)
	_materialPerformance.materialPerformanceDo.UseModel(&model.MaterialPerformance{})

	tableName := _materialPerformance.materialPerformanceDo.TableName()
	_materialPerformance.ALL = field.NewAsterisk(tableName)
	_materialPerformance.ID = field.NewInt64(tableName, "id")
	_materialPerformance.Name = field.NewString(tableName, "name")
	_materialPerformance.Description = field.NewString(tableName, "description")
	_materialPerformance.Stage = field.NewString(tableName, "stage")
	_materialPerformance.LastError = field.NewString(tableName, "last_error")
	_materialPerformance.UserID = field.NewInt64(tableName, "user_id")
	_materialPerformance.CompanyID = field.NewInt32(tableName, "company_id")
	_materialPerformance.CreatedAt = field.NewTime(tableName, "created_at")
	_materialPerformance.UpdatedAt = field.NewTime(tableName, "updated_at")

	_materialPerformance.fillFieldMap()

	return _materialPerformance
}

type materialPerformance struct {
	materialPerformanceDo materialPerformanceDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String
	Description field.String
	Stage       field.String
	LastError   field.String
	UserID      field.Int64
	CompanyID   field.Int32
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m materialPerformance) Table(newTableName string) *materialPerformance {
	m.materialPerformanceDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m materialPerformance) As(alias string) *materialPerformance {
	m.materialPerformanceDo.DO = *(m.materialPerformanceDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *materialPerformance) updateTableName(table string) *materialPerformance {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.Name = field.NewString(table, "name")
	m.Description = field.NewString(table, "description")
	m.Stage = field.NewString(table, "stage")
	m.LastError = field.NewString(table, "last_error")
	m.UserID = field.NewInt64(table, "user_id")
	m.CompanyID = field.NewInt32(table, "company_id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *materialPerformance) WithContext(ctx context.Context) *materialPerformanceDo {
	return m.materialPerformanceDo.WithContext(ctx)
}

func (m materialPerformance) TableName() string { return m.materialPerformanceDo.TableName() }

func (m materialPerformance) Alias() string { return m.materialPerformanceDo.Alias() }

func (m *materialPerformance) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *materialPerformance) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["id"] = m.ID
	m.fieldMap["name"] = m.Name
	m.fieldMap["description"] = m.Description
	m.fieldMap["stage"] = m.Stage
	m.fieldMap["last_error"] = m.LastError
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["company_id"] = m.CompanyID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m materialPerformance) clone(db *gorm.DB) materialPerformance {
	m.materialPerformanceDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m materialPerformance) replaceDB(db *gorm.DB) materialPerformance {
	m.materialPerformanceDo.ReplaceDB(db)
	return m
}

type materialPerformanceDo struct{ gen.DO }

func (m materialPerformanceDo) Debug() *materialPerformanceDo {
	return m.withDO(m.DO.Debug())
}

func (m materialPerformanceDo) WithContext(ctx context.Context) *materialPerformanceDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m materialPerformanceDo) ReadDB() *materialPerformanceDo {
	return m.Clauses(dbresolver.Read)
}

func (m materialPerformanceDo) WriteDB() *materialPerformanceDo {
	return m.Clauses(dbresolver.Write)
}

func (m materialPerformanceDo) Session(config *gorm.Session) *materialPerformanceDo {
	return m.withDO(m.DO.Session(config))
}

func (m materialPerformanceDo) Clauses(conds ...clause.Expression) *materialPerformanceDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m materialPerformanceDo) Returning(value interface{}, columns ...string) *materialPerformanceDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m materialPerformanceDo) Not(conds ...gen.Condition) *materialPerformanceDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m materialPerformanceDo) Or(conds ...gen.Condition) *materialPerformanceDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m materialPerformanceDo) Select(conds ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m materialPerformanceDo) Where(conds ...gen.Condition) *materialPerformanceDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m materialPerformanceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *materialPerformanceDo {
	return m.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (m materialPerformanceDo) Order(conds ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m materialPerformanceDo) Distinct(cols ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m materialPerformanceDo) Omit(cols ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m materialPerformanceDo) Join(table schema.Tabler, on ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m materialPerformanceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m materialPerformanceDo) RightJoin(table schema.Tabler, on ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m materialPerformanceDo) Group(cols ...field.Expr) *materialPerformanceDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m materialPerformanceDo) Having(conds ...gen.Condition) *materialPerformanceDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m materialPerformanceDo) Limit(limit int) *materialPerformanceDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m materialPerformanceDo) Offset(offset int) *materialPerformanceDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m materialPerformanceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *materialPerformanceDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m materialPerformanceDo) Unscoped() *materialPerformanceDo {
	return m.withDO(m.DO.Unscoped())
}

func (m materialPerformanceDo) Create(values ...*model.MaterialPerformance) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m materialPerformanceDo) CreateInBatches(values []*model.MaterialPerformance, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m materialPerformanceDo) Save(values ...*model.MaterialPerformance) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m materialPerformanceDo) First() (*model.MaterialPerformance, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialPerformance), nil
	}
}

func (m materialPerformanceDo) Take() (*model.MaterialPerformance, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialPerformance), nil
	}
}

func (m materialPerformanceDo) Last() (*model.MaterialPerformance, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialPerformance), nil
	}
}

func (m materialPerformanceDo) Find() ([]*model.MaterialPerformance, error) {
	result, err := m.DO.Find()
	return result.([]*model.MaterialPerformance), err
}

func (m materialPerformanceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MaterialPerformance, err error) {
	buf := make([]*model.MaterialPerformance, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m materialPerformanceDo) FindInBatches(result *[]*model.MaterialPerformance, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m materialPerformanceDo) Attrs(attrs ...field.AssignExpr) *materialPerformanceDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m materialPerformanceDo) Assign(attrs ...field.AssignExpr) *materialPerformanceDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m materialPerformanceDo) Joins(fields ...field.RelationField) *materialPerformanceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m materialPerformanceDo) Preload(fields ...field.RelationField) *materialPerformanceDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m materialPerformanceDo) FirstOrInit() (*model.MaterialPerformance, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialPerformance), nil
	}
}

func (m materialPerformanceDo) FirstOrCreate() (*model.MaterialPerformance, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MaterialPerformance), nil
	}
}

func (m materialPerformanceDo) FindByPage(offset int, limit int) (result []*model.MaterialPerformance, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m materialPerformanceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m materialPerformanceDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m materialPerformanceDo) Delete(models ...*model.MaterialPerformance) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *materialPerformanceDo) withDO(do gen.Dao) *materialPerformanceDo {
	m.DO = *do.(*gen.DO)
	return m
}
