// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newTaskQueue(db *gorm.DB, opts ...gen.DOOption) taskQueue {
	_taskQueue := taskQueue{}

	_taskQueue.taskQueueDo.UseDB(db, opts...)
	_taskQueue.taskQueueDo.UseModel(&model.TaskQueue{})

	tableName := _taskQueue.taskQueueDo.TableName()
	_taskQueue.ALL = field.NewAsterisk(tableName)
	_taskQueue.ID = field.NewInt64(tableName, "id")
	_taskQueue.TaskType = field.NewString(tableName, "task_type")
	_taskQueue.Payload = field.NewString(tableName, "payload")
	_taskQueue.Status = field.NewInt32(tableName, "status")
	_taskQueue.Priority = field.NewInt32(tableName, "priority")
	_taskQueue.Attempts = field.NewInt32(tableName, "attempts")
	_taskQueue.MaxAttempts = field.NewInt32(tableName, "max_attempts")
	_taskQueue.ScheduledAt = field.NewTime(tableName, "scheduled_at")
	_taskQueue.ClaimedAt = field.NewTime(tableName, "claimed_at")
	_taskQueue.LeaseUntil = field.NewTime(tableName, "lease_until")
	_taskQueue.VisibilityTimeoutSec = field.NewInt32(tableName, "visibility_timeout_sec")
	_taskQueue.LastError = field.NewString(tableName, "last_error")
	_taskQueue.CreatedAt = field.NewTime(tableName, "created_at")
	_taskQueue.UpdatedAt = field.NewTime(tableName, "updated_at")

	_taskQueue.fillFieldMap()

	return _taskQueue
}

type taskQueue struct {
	taskQueueDo taskQueueDo

	ALL                  field.Asterisk
	ID                   field.Int64  // 主键ID
	TaskType             field.String // 任务类型，例如：tender_parse
	Payload              field.String // 任务负载，JSON格式，包含项目ID、记录ID、COS对象键等
	Status               field.Int32  // 任务状态：0待处理(pending)、1处理中(processing)、2成功(succeeded)、3失败(failed)
	Priority             field.Int32  // 任务优先级，数值越大优先级越高
	Attempts             field.Int32  // 已重试次数
	MaxAttempts          field.Int32  // 最大重试次数，达到后置为失败
	ScheduledAt          field.Time   // 计划执行时间（入队即消费则为当前时间）
	ClaimedAt            field.Time   // 被Worker领取（claim）的时间
	LeaseUntil           field.Time   // 租约到期时间，用于处理中任务的自动恢复
	VisibilityTimeoutSec field.Int32  // 租约可见超时时长（秒），默认3小时10800秒
	LastError            field.String // 最近一次错误信息
	CreatedAt            field.Time   // 创建时间
	UpdatedAt            field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t taskQueue) Table(newTableName string) *taskQueue {
	t.taskQueueDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskQueue) As(alias string) *taskQueue {
	t.taskQueueDo.DO = *(t.taskQueueDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskQueue) updateTableName(table string) *taskQueue {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TaskType = field.NewString(table, "task_type")
	t.Payload = field.NewString(table, "payload")
	t.Status = field.NewInt32(table, "status")
	t.Priority = field.NewInt32(table, "priority")
	t.Attempts = field.NewInt32(table, "attempts")
	t.MaxAttempts = field.NewInt32(table, "max_attempts")
	t.ScheduledAt = field.NewTime(table, "scheduled_at")
	t.ClaimedAt = field.NewTime(table, "claimed_at")
	t.LeaseUntil = field.NewTime(table, "lease_until")
	t.VisibilityTimeoutSec = field.NewInt32(table, "visibility_timeout_sec")
	t.LastError = field.NewString(table, "last_error")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *taskQueue) WithContext(ctx context.Context) *taskQueueDo {
	return t.taskQueueDo.WithContext(ctx)
}

func (t taskQueue) TableName() string { return t.taskQueueDo.TableName() }

func (t taskQueue) Alias() string { return t.taskQueueDo.Alias() }

func (t *taskQueue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskQueue) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["id"] = t.ID
	t.fieldMap["task_type"] = t.TaskType
	t.fieldMap["payload"] = t.Payload
	t.fieldMap["status"] = t.Status
	t.fieldMap["priority"] = t.Priority
	t.fieldMap["attempts"] = t.Attempts
	t.fieldMap["max_attempts"] = t.MaxAttempts
	t.fieldMap["scheduled_at"] = t.ScheduledAt
	t.fieldMap["claimed_at"] = t.ClaimedAt
	t.fieldMap["lease_until"] = t.LeaseUntil
	t.fieldMap["visibility_timeout_sec"] = t.VisibilityTimeoutSec
	t.fieldMap["last_error"] = t.LastError
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t taskQueue) clone(db *gorm.DB) taskQueue {
	t.taskQueueDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskQueue) replaceDB(db *gorm.DB) taskQueue {
	t.taskQueueDo.ReplaceDB(db)
	return t
}

type taskQueueDo struct{ gen.DO }

func (t taskQueueDo) Debug() *taskQueueDo {
	return t.withDO(t.DO.Debug())
}

func (t taskQueueDo) WithContext(ctx context.Context) *taskQueueDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskQueueDo) ReadDB() *taskQueueDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskQueueDo) WriteDB() *taskQueueDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskQueueDo) Session(config *gorm.Session) *taskQueueDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskQueueDo) Clauses(conds ...clause.Expression) *taskQueueDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskQueueDo) Returning(value interface{}, columns ...string) *taskQueueDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskQueueDo) Not(conds ...gen.Condition) *taskQueueDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskQueueDo) Or(conds ...gen.Condition) *taskQueueDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskQueueDo) Select(conds ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskQueueDo) Where(conds ...gen.Condition) *taskQueueDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskQueueDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *taskQueueDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t taskQueueDo) Order(conds ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskQueueDo) Distinct(cols ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskQueueDo) Omit(cols ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskQueueDo) Join(table schema.Tabler, on ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskQueueDo) LeftJoin(table schema.Tabler, on ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskQueueDo) RightJoin(table schema.Tabler, on ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskQueueDo) Group(cols ...field.Expr) *taskQueueDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskQueueDo) Having(conds ...gen.Condition) *taskQueueDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskQueueDo) Limit(limit int) *taskQueueDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskQueueDo) Offset(offset int) *taskQueueDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskQueueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *taskQueueDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskQueueDo) Unscoped() *taskQueueDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskQueueDo) Create(values ...*model.TaskQueue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskQueueDo) CreateInBatches(values []*model.TaskQueue, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskQueueDo) Save(values ...*model.TaskQueue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskQueueDo) First() (*model.TaskQueue, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskQueue), nil
	}
}

func (t taskQueueDo) Take() (*model.TaskQueue, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskQueue), nil
	}
}

func (t taskQueueDo) Last() (*model.TaskQueue, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskQueue), nil
	}
}

func (t taskQueueDo) Find() ([]*model.TaskQueue, error) {
	result, err := t.DO.Find()
	return result.([]*model.TaskQueue), err
}

func (t taskQueueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskQueue, err error) {
	buf := make([]*model.TaskQueue, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskQueueDo) FindInBatches(result *[]*model.TaskQueue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskQueueDo) Attrs(attrs ...field.AssignExpr) *taskQueueDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskQueueDo) Assign(attrs ...field.AssignExpr) *taskQueueDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskQueueDo) Joins(fields ...field.RelationField) *taskQueueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskQueueDo) Preload(fields ...field.RelationField) *taskQueueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskQueueDo) FirstOrInit() (*model.TaskQueue, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskQueue), nil
	}
}

func (t taskQueueDo) FirstOrCreate() (*model.TaskQueue, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskQueue), nil
	}
}

func (t taskQueueDo) FindByPage(offset int, limit int) (result []*model.TaskQueue, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskQueueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskQueueDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskQueueDo) Delete(models ...*model.TaskQueue) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskQueueDo) withDO(do gen.Dao) *taskQueueDo {
	t.DO = *do.(*gen.DO)
	return t
}
