// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newTenderType(db *gorm.DB, opts ...gen.DOOption) tenderType {
	_tenderType := tenderType{}

	_tenderType.tenderTypeDo.UseDB(db, opts...)
	_tenderType.tenderTypeDo.UseModel(&model.TenderType{})

	tableName := _tenderType.tenderTypeDo.TableName()
	_tenderType.ALL = field.NewAsterisk(tableName)
	_tenderType.ID = field.NewInt64(tableName, "id")
	_tenderType.Name = field.NewString(tableName, "name")
	_tenderType.Description = field.NewString(tableName, "description")
	_tenderType.SortOrder = field.NewInt32(tableName, "sort_order")

	_tenderType.fillFieldMap()

	return _tenderType
}

type tenderType struct {
	tenderTypeDo tenderTypeDo

	ALL         field.Asterisk
	ID          field.Int64
	Name        field.String // 招标类型名称，例如半导体招标、仓储招标
	Description field.String // 行业描述
	SortOrder   field.Int32  // 排序序号

	fieldMap map[string]field.Expr
}

func (t tenderType) Table(newTableName string) *tenderType {
	t.tenderTypeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenderType) As(alias string) *tenderType {
	t.tenderTypeDo.DO = *(t.tenderTypeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenderType) updateTableName(table string) *tenderType {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.Name = field.NewString(table, "name")
	t.Description = field.NewString(table, "description")
	t.SortOrder = field.NewInt32(table, "sort_order")

	t.fillFieldMap()

	return t
}

func (t *tenderType) WithContext(ctx context.Context) *tenderTypeDo {
	return t.tenderTypeDo.WithContext(ctx)
}

func (t tenderType) TableName() string { return t.tenderTypeDo.TableName() }

func (t tenderType) Alias() string { return t.tenderTypeDo.Alias() }

func (t *tenderType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenderType) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["name"] = t.Name
	t.fieldMap["description"] = t.Description
	t.fieldMap["sort_order"] = t.SortOrder
}

func (t tenderType) clone(db *gorm.DB) tenderType {
	t.tenderTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenderType) replaceDB(db *gorm.DB) tenderType {
	t.tenderTypeDo.ReplaceDB(db)
	return t
}

type tenderTypeDo struct{ gen.DO }

func (t tenderTypeDo) Debug() *tenderTypeDo {
	return t.withDO(t.DO.Debug())
}

func (t tenderTypeDo) WithContext(ctx context.Context) *tenderTypeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenderTypeDo) ReadDB() *tenderTypeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenderTypeDo) WriteDB() *tenderTypeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenderTypeDo) Session(config *gorm.Session) *tenderTypeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenderTypeDo) Clauses(conds ...clause.Expression) *tenderTypeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenderTypeDo) Returning(value interface{}, columns ...string) *tenderTypeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenderTypeDo) Not(conds ...gen.Condition) *tenderTypeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenderTypeDo) Or(conds ...gen.Condition) *tenderTypeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenderTypeDo) Select(conds ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenderTypeDo) Where(conds ...gen.Condition) *tenderTypeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenderTypeDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *tenderTypeDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tenderTypeDo) Order(conds ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenderTypeDo) Distinct(cols ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenderTypeDo) Omit(cols ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenderTypeDo) Join(table schema.Tabler, on ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenderTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenderTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenderTypeDo) Group(cols ...field.Expr) *tenderTypeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenderTypeDo) Having(conds ...gen.Condition) *tenderTypeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenderTypeDo) Limit(limit int) *tenderTypeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenderTypeDo) Offset(offset int) *tenderTypeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenderTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenderTypeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenderTypeDo) Unscoped() *tenderTypeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenderTypeDo) Create(values ...*model.TenderType) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenderTypeDo) CreateInBatches(values []*model.TenderType, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenderTypeDo) Save(values ...*model.TenderType) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenderTypeDo) First() (*model.TenderType, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderType), nil
	}
}

func (t tenderTypeDo) Take() (*model.TenderType, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderType), nil
	}
}

func (t tenderTypeDo) Last() (*model.TenderType, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderType), nil
	}
}

func (t tenderTypeDo) Find() ([]*model.TenderType, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenderType), err
}

func (t tenderTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenderType, err error) {
	buf := make([]*model.TenderType, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenderTypeDo) FindInBatches(result *[]*model.TenderType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenderTypeDo) Attrs(attrs ...field.AssignExpr) *tenderTypeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenderTypeDo) Assign(attrs ...field.AssignExpr) *tenderTypeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenderTypeDo) Joins(fields ...field.RelationField) *tenderTypeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenderTypeDo) Preload(fields ...field.RelationField) *tenderTypeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenderTypeDo) FirstOrInit() (*model.TenderType, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderType), nil
	}
}

func (t tenderTypeDo) FirstOrCreate() (*model.TenderType, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderType), nil
	}
}

func (t tenderTypeDo) FindByPage(offset int, limit int) (result []*model.TenderType, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenderTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenderTypeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenderTypeDo) Delete(models ...*model.TenderType) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenderTypeDo) withDO(do gen.Dao) *tenderTypeDo {
	t.DO = *do.(*gen.DO)
	return t
}
