// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newTenderFreightResource(db *gorm.DB, opts ...gen.DOOption) tenderFreightResource {
	_tenderFreightResource := tenderFreightResource{}

	_tenderFreightResource.tenderFreightResourceDo.UseDB(db, opts...)
	_tenderFreightResource.tenderFreightResourceDo.UseModel(&model.TenderFreightResource{})

	tableName := _tenderFreightResource.tenderFreightResourceDo.TableName()
	_tenderFreightResource.ALL = field.NewAsterisk(tableName)
	_tenderFreightResource.ID = field.NewInt64(tableName, "id")
	_tenderFreightResource.TenderProjectID = field.NewInt64(tableName, "tender_project_id")
	_tenderFreightResource.OriginCity = field.NewString(tableName, "origin_city")
	_tenderFreightResource.DestCity = field.NewString(tableName, "dest_city")
	_tenderFreightResource.ResourceType = field.NewString(tableName, "resource_type")
	_tenderFreightResource.Content = field.NewString(tableName, "content")
	_tenderFreightResource.CreatedAt = field.NewInt64(tableName, "created_at")
	_tenderFreightResource.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_tenderFreightResource.IsRead = field.NewInt32(tableName, "is_read")
	_tenderFreightResource.Source = field.NewString(tableName, "source")
	_tenderFreightResource.SearchID = field.NewString(tableName, "search_id")

	_tenderFreightResource.fillFieldMap()

	return _tenderFreightResource
}

type tenderFreightResource struct {
	tenderFreightResourceDo tenderFreightResourceDo

	ALL             field.Asterisk
	ID              field.Int64
	TenderProjectID field.Int64  // 关联的投标项目ID（bid_project.id）
	OriginCity      field.String // 起始地
	DestCity        field.String // 目的地
	/*
		资源类型：
		BASE_BARGAIN:驳运资源
		BASE_AUTOMOBILE:汽运资源
		CUSTOMS_DOMESTIC:关务国内资源
		BASE_CUSTOMS_ABROAD:关务国外资源
		RAILWAY_MAINLINE:铁路干线资源
		AIR_CHARTER_FLIGHT:空运包机资源
		AIR_PACKAGING_BOARD:空运包板资源
		CONTAINER_STATION:集装箱场站资源
		BASE_WAREHOUSE:仓储资源
	*/
	ResourceType field.String
	Content      field.String // 资源详情
	CreatedAt    field.Int64  // 记录创建时间
	UpdatedAt    field.Int64  // 记录更新时间
	IsRead       field.Int32  // 是否已读
	Source       field.String // 记录来源：招标文件解析、EXCEL解析、手动输入
	SearchID     field.String // 检索ID，用于对货运资源分组

	fieldMap map[string]field.Expr
}

func (t tenderFreightResource) Table(newTableName string) *tenderFreightResource {
	t.tenderFreightResourceDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenderFreightResource) As(alias string) *tenderFreightResource {
	t.tenderFreightResourceDo.DO = *(t.tenderFreightResourceDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenderFreightResource) updateTableName(table string) *tenderFreightResource {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TenderProjectID = field.NewInt64(table, "tender_project_id")
	t.OriginCity = field.NewString(table, "origin_city")
	t.DestCity = field.NewString(table, "dest_city")
	t.ResourceType = field.NewString(table, "resource_type")
	t.Content = field.NewString(table, "content")
	t.CreatedAt = field.NewInt64(table, "created_at")
	t.UpdatedAt = field.NewInt64(table, "updated_at")
	t.IsRead = field.NewInt32(table, "is_read")
	t.Source = field.NewString(table, "source")
	t.SearchID = field.NewString(table, "search_id")

	t.fillFieldMap()

	return t
}

func (t *tenderFreightResource) WithContext(ctx context.Context) *tenderFreightResourceDo {
	return t.tenderFreightResourceDo.WithContext(ctx)
}

func (t tenderFreightResource) TableName() string { return t.tenderFreightResourceDo.TableName() }

func (t tenderFreightResource) Alias() string { return t.tenderFreightResourceDo.Alias() }

func (t *tenderFreightResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenderFreightResource) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tender_project_id"] = t.TenderProjectID
	t.fieldMap["origin_city"] = t.OriginCity
	t.fieldMap["dest_city"] = t.DestCity
	t.fieldMap["resource_type"] = t.ResourceType
	t.fieldMap["content"] = t.Content
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["is_read"] = t.IsRead
	t.fieldMap["source"] = t.Source
	t.fieldMap["search_id"] = t.SearchID
}

func (t tenderFreightResource) clone(db *gorm.DB) tenderFreightResource {
	t.tenderFreightResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenderFreightResource) replaceDB(db *gorm.DB) tenderFreightResource {
	t.tenderFreightResourceDo.ReplaceDB(db)
	return t
}

type tenderFreightResourceDo struct{ gen.DO }

func (t tenderFreightResourceDo) Debug() *tenderFreightResourceDo {
	return t.withDO(t.DO.Debug())
}

func (t tenderFreightResourceDo) WithContext(ctx context.Context) *tenderFreightResourceDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenderFreightResourceDo) ReadDB() *tenderFreightResourceDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenderFreightResourceDo) WriteDB() *tenderFreightResourceDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenderFreightResourceDo) Session(config *gorm.Session) *tenderFreightResourceDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenderFreightResourceDo) Clauses(conds ...clause.Expression) *tenderFreightResourceDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenderFreightResourceDo) Returning(value interface{}, columns ...string) *tenderFreightResourceDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenderFreightResourceDo) Not(conds ...gen.Condition) *tenderFreightResourceDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenderFreightResourceDo) Or(conds ...gen.Condition) *tenderFreightResourceDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenderFreightResourceDo) Select(conds ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenderFreightResourceDo) Where(conds ...gen.Condition) *tenderFreightResourceDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenderFreightResourceDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *tenderFreightResourceDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tenderFreightResourceDo) Order(conds ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenderFreightResourceDo) Distinct(cols ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenderFreightResourceDo) Omit(cols ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenderFreightResourceDo) Join(table schema.Tabler, on ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenderFreightResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenderFreightResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenderFreightResourceDo) Group(cols ...field.Expr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenderFreightResourceDo) Having(conds ...gen.Condition) *tenderFreightResourceDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenderFreightResourceDo) Limit(limit int) *tenderFreightResourceDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenderFreightResourceDo) Offset(offset int) *tenderFreightResourceDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenderFreightResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenderFreightResourceDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenderFreightResourceDo) Unscoped() *tenderFreightResourceDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenderFreightResourceDo) Create(values ...*model.TenderFreightResource) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenderFreightResourceDo) CreateInBatches(values []*model.TenderFreightResource, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenderFreightResourceDo) Save(values ...*model.TenderFreightResource) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenderFreightResourceDo) First() (*model.TenderFreightResource, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderFreightResource), nil
	}
}

func (t tenderFreightResourceDo) Take() (*model.TenderFreightResource, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderFreightResource), nil
	}
}

func (t tenderFreightResourceDo) Last() (*model.TenderFreightResource, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderFreightResource), nil
	}
}

func (t tenderFreightResourceDo) Find() ([]*model.TenderFreightResource, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenderFreightResource), err
}

func (t tenderFreightResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenderFreightResource, err error) {
	buf := make([]*model.TenderFreightResource, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenderFreightResourceDo) FindInBatches(result *[]*model.TenderFreightResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenderFreightResourceDo) Attrs(attrs ...field.AssignExpr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenderFreightResourceDo) Assign(attrs ...field.AssignExpr) *tenderFreightResourceDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenderFreightResourceDo) Joins(fields ...field.RelationField) *tenderFreightResourceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenderFreightResourceDo) Preload(fields ...field.RelationField) *tenderFreightResourceDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenderFreightResourceDo) FirstOrInit() (*model.TenderFreightResource, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderFreightResource), nil
	}
}

func (t tenderFreightResourceDo) FirstOrCreate() (*model.TenderFreightResource, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderFreightResource), nil
	}
}

func (t tenderFreightResourceDo) FindByPage(offset int, limit int) (result []*model.TenderFreightResource, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenderFreightResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenderFreightResourceDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenderFreightResourceDo) Delete(models ...*model.TenderFreightResource) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenderFreightResourceDo) withDO(do gen.Dao) *tenderFreightResourceDo {
	t.DO = *do.(*gen.DO)
	return t
}
