// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newTenderProjectMember(db *gorm.DB, opts ...gen.DOOption) tenderProjectMember {
	_tenderProjectMember := tenderProjectMember{}

	_tenderProjectMember.tenderProjectMemberDo.UseDB(db, opts...)
	_tenderProjectMember.tenderProjectMemberDo.UseModel(&model.TenderProjectMember{})

	tableName := _tenderProjectMember.tenderProjectMemberDo.TableName()
	_tenderProjectMember.ALL = field.NewAsterisk(tableName)
	_tenderProjectMember.ID = field.NewInt64(tableName, "id")
	_tenderProjectMember.ProjectID = field.NewInt64(tableName, "project_id")
	_tenderProjectMember.UserID = field.NewInt64(tableName, "user_id")
	_tenderProjectMember.Role = field.NewString(tableName, "role")
	_tenderProjectMember.CreatedAt = field.NewTime(tableName, "created_at")
	_tenderProjectMember.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tenderProjectMember.fillFieldMap()

	return _tenderProjectMember
}

type tenderProjectMember struct {
	tenderProjectMemberDo tenderProjectMemberDo

	ALL       field.Asterisk
	ID        field.Int64
	ProjectID field.Int64
	UserID    field.Int64
	Role      field.String // creator/cooperator/final_confirm
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (t tenderProjectMember) Table(newTableName string) *tenderProjectMember {
	t.tenderProjectMemberDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenderProjectMember) As(alias string) *tenderProjectMember {
	t.tenderProjectMemberDo.DO = *(t.tenderProjectMemberDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenderProjectMember) updateTableName(table string) *tenderProjectMember {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.ProjectID = field.NewInt64(table, "project_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.Role = field.NewString(table, "role")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tenderProjectMember) WithContext(ctx context.Context) *tenderProjectMemberDo {
	return t.tenderProjectMemberDo.WithContext(ctx)
}

func (t tenderProjectMember) TableName() string { return t.tenderProjectMemberDo.TableName() }

func (t tenderProjectMember) Alias() string { return t.tenderProjectMemberDo.Alias() }

func (t *tenderProjectMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenderProjectMember) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["id"] = t.ID
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["role"] = t.Role
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tenderProjectMember) clone(db *gorm.DB) tenderProjectMember {
	t.tenderProjectMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenderProjectMember) replaceDB(db *gorm.DB) tenderProjectMember {
	t.tenderProjectMemberDo.ReplaceDB(db)
	return t
}

type tenderProjectMemberDo struct{ gen.DO }

func (t tenderProjectMemberDo) Debug() *tenderProjectMemberDo {
	return t.withDO(t.DO.Debug())
}

func (t tenderProjectMemberDo) WithContext(ctx context.Context) *tenderProjectMemberDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenderProjectMemberDo) ReadDB() *tenderProjectMemberDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenderProjectMemberDo) WriteDB() *tenderProjectMemberDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenderProjectMemberDo) Session(config *gorm.Session) *tenderProjectMemberDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenderProjectMemberDo) Clauses(conds ...clause.Expression) *tenderProjectMemberDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenderProjectMemberDo) Returning(value interface{}, columns ...string) *tenderProjectMemberDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenderProjectMemberDo) Not(conds ...gen.Condition) *tenderProjectMemberDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenderProjectMemberDo) Or(conds ...gen.Condition) *tenderProjectMemberDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenderProjectMemberDo) Select(conds ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenderProjectMemberDo) Where(conds ...gen.Condition) *tenderProjectMemberDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenderProjectMemberDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *tenderProjectMemberDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tenderProjectMemberDo) Order(conds ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenderProjectMemberDo) Distinct(cols ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenderProjectMemberDo) Omit(cols ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenderProjectMemberDo) Join(table schema.Tabler, on ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenderProjectMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenderProjectMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenderProjectMemberDo) Group(cols ...field.Expr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenderProjectMemberDo) Having(conds ...gen.Condition) *tenderProjectMemberDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenderProjectMemberDo) Limit(limit int) *tenderProjectMemberDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenderProjectMemberDo) Offset(offset int) *tenderProjectMemberDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenderProjectMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenderProjectMemberDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenderProjectMemberDo) Unscoped() *tenderProjectMemberDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenderProjectMemberDo) Create(values ...*model.TenderProjectMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenderProjectMemberDo) CreateInBatches(values []*model.TenderProjectMember, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenderProjectMemberDo) Save(values ...*model.TenderProjectMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenderProjectMemberDo) First() (*model.TenderProjectMember, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderProjectMember), nil
	}
}

func (t tenderProjectMemberDo) Take() (*model.TenderProjectMember, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderProjectMember), nil
	}
}

func (t tenderProjectMemberDo) Last() (*model.TenderProjectMember, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderProjectMember), nil
	}
}

func (t tenderProjectMemberDo) Find() ([]*model.TenderProjectMember, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenderProjectMember), err
}

func (t tenderProjectMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenderProjectMember, err error) {
	buf := make([]*model.TenderProjectMember, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenderProjectMemberDo) FindInBatches(result *[]*model.TenderProjectMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenderProjectMemberDo) Attrs(attrs ...field.AssignExpr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenderProjectMemberDo) Assign(attrs ...field.AssignExpr) *tenderProjectMemberDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenderProjectMemberDo) Joins(fields ...field.RelationField) *tenderProjectMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenderProjectMemberDo) Preload(fields ...field.RelationField) *tenderProjectMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenderProjectMemberDo) FirstOrInit() (*model.TenderProjectMember, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderProjectMember), nil
	}
}

func (t tenderProjectMemberDo) FirstOrCreate() (*model.TenderProjectMember, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenderProjectMember), nil
	}
}

func (t tenderProjectMemberDo) FindByPage(offset int, limit int) (result []*model.TenderProjectMember, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenderProjectMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenderProjectMemberDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenderProjectMemberDo) Delete(models ...*model.TenderProjectMember) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenderProjectMemberDo) withDO(do gen.Dao) *tenderProjectMemberDo {
	t.DO = *do.(*gen.DO)
	return t
}
