// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bid-engine/pkg/db/model"
)

func newUserExtraProfile(db *gorm.DB, opts ...gen.DOOption) userExtraProfile {
	_userExtraProfile := userExtraProfile{}

	_userExtraProfile.userExtraProfileDo.UseDB(db, opts...)
	_userExtraProfile.userExtraProfileDo.UseModel(&model.UserExtraProfile{})

	tableName := _userExtraProfile.userExtraProfileDo.TableName()
	_userExtraProfile.ALL = field.NewAsterisk(tableName)
	_userExtraProfile.UserID = field.NewInt64(tableName, "user_id")
	_userExtraProfile.ContactMobile = field.NewString(tableName, "contact_mobile")
	_userExtraProfile.CompanyDisplayName = field.NewString(tableName, "company_display_name")
	_userExtraProfile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userExtraProfile.fillFieldMap()

	return _userExtraProfile
}

type userExtraProfile struct {
	userExtraProfileDo userExtraProfileDo

	ALL                field.Asterisk
	UserID             field.Int64
	ContactMobile      field.String
	CompanyDisplayName field.String
	UpdatedAt          field.Time

	fieldMap map[string]field.Expr
}

func (u userExtraProfile) Table(newTableName string) *userExtraProfile {
	u.userExtraProfileDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userExtraProfile) As(alias string) *userExtraProfile {
	u.userExtraProfileDo.DO = *(u.userExtraProfileDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userExtraProfile) updateTableName(table string) *userExtraProfile {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt64(table, "user_id")
	u.ContactMobile = field.NewString(table, "contact_mobile")
	u.CompanyDisplayName = field.NewString(table, "company_display_name")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userExtraProfile) WithContext(ctx context.Context) *userExtraProfileDo {
	return u.userExtraProfileDo.WithContext(ctx)
}

func (u userExtraProfile) TableName() string { return u.userExtraProfileDo.TableName() }

func (u userExtraProfile) Alias() string { return u.userExtraProfileDo.Alias() }

func (u *userExtraProfile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userExtraProfile) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 4)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["contact_mobile"] = u.ContactMobile
	u.fieldMap["company_display_name"] = u.CompanyDisplayName
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userExtraProfile) clone(db *gorm.DB) userExtraProfile {
	u.userExtraProfileDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userExtraProfile) replaceDB(db *gorm.DB) userExtraProfile {
	u.userExtraProfileDo.ReplaceDB(db)
	return u
}

type userExtraProfileDo struct{ gen.DO }

func (u userExtraProfileDo) Debug() *userExtraProfileDo {
	return u.withDO(u.DO.Debug())
}

func (u userExtraProfileDo) WithContext(ctx context.Context) *userExtraProfileDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userExtraProfileDo) ReadDB() *userExtraProfileDo {
	return u.Clauses(dbresolver.Read)
}

func (u userExtraProfileDo) WriteDB() *userExtraProfileDo {
	return u.Clauses(dbresolver.Write)
}

func (u userExtraProfileDo) Session(config *gorm.Session) *userExtraProfileDo {
	return u.withDO(u.DO.Session(config))
}

func (u userExtraProfileDo) Clauses(conds ...clause.Expression) *userExtraProfileDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userExtraProfileDo) Returning(value interface{}, columns ...string) *userExtraProfileDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userExtraProfileDo) Not(conds ...gen.Condition) *userExtraProfileDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userExtraProfileDo) Or(conds ...gen.Condition) *userExtraProfileDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userExtraProfileDo) Select(conds ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userExtraProfileDo) Where(conds ...gen.Condition) *userExtraProfileDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userExtraProfileDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userExtraProfileDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userExtraProfileDo) Order(conds ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userExtraProfileDo) Distinct(cols ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userExtraProfileDo) Omit(cols ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userExtraProfileDo) Join(table schema.Tabler, on ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userExtraProfileDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userExtraProfileDo) RightJoin(table schema.Tabler, on ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userExtraProfileDo) Group(cols ...field.Expr) *userExtraProfileDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userExtraProfileDo) Having(conds ...gen.Condition) *userExtraProfileDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userExtraProfileDo) Limit(limit int) *userExtraProfileDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userExtraProfileDo) Offset(offset int) *userExtraProfileDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userExtraProfileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userExtraProfileDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userExtraProfileDo) Unscoped() *userExtraProfileDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userExtraProfileDo) Create(values ...*model.UserExtraProfile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userExtraProfileDo) CreateInBatches(values []*model.UserExtraProfile, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userExtraProfileDo) Save(values ...*model.UserExtraProfile) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userExtraProfileDo) First() (*model.UserExtraProfile, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserExtraProfile), nil
	}
}

func (u userExtraProfileDo) Take() (*model.UserExtraProfile, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserExtraProfile), nil
	}
}

func (u userExtraProfileDo) Last() (*model.UserExtraProfile, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserExtraProfile), nil
	}
}

func (u userExtraProfileDo) Find() ([]*model.UserExtraProfile, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserExtraProfile), err
}

func (u userExtraProfileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserExtraProfile, err error) {
	buf := make([]*model.UserExtraProfile, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userExtraProfileDo) FindInBatches(result *[]*model.UserExtraProfile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userExtraProfileDo) Attrs(attrs ...field.AssignExpr) *userExtraProfileDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userExtraProfileDo) Assign(attrs ...field.AssignExpr) *userExtraProfileDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userExtraProfileDo) Joins(fields ...field.RelationField) *userExtraProfileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userExtraProfileDo) Preload(fields ...field.RelationField) *userExtraProfileDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userExtraProfileDo) FirstOrInit() (*model.UserExtraProfile, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserExtraProfile), nil
	}
}

func (u userExtraProfileDo) FirstOrCreate() (*model.UserExtraProfile, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserExtraProfile), nil
	}
}

func (u userExtraProfileDo) FindByPage(offset int, limit int) (result []*model.UserExtraProfile, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userExtraProfileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userExtraProfileDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userExtraProfileDo) Delete(models ...*model.UserExtraProfile) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userExtraProfileDo) withDO(do gen.Dao) *userExtraProfileDo {
	u.DO = *do.(*gen.DO)
	return u
}
