// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentSessionMap = "agent_session_map"

// AgentSessionMap mapped from table <agent_session_map>
type AgentSessionMap struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增主键
	OurConversationID   string    `gorm:"column:our_conversation_id;not null" json:"our_conversation_id"`
	AgentConversationID string    `gorm:"column:agent_conversation_id;not null" json:"agent_conversation_id"`
	AgentID             string    `gorm:"column:agent_id;not null" json:"agent_id"`
	CreatedAt           time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AgentSessionMap's table name
func (*AgentSessionMap) TableName() string {
	return TableNameAgentSessionMap
}
