// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAudit = "audit"

// Audit mapped from table <audit>
type Audit struct {
	AuditID    int64     `gorm:"column:audit_id;primaryKey;autoIncrement:true" json:"audit_id"`      // 事件id
	CompanyID  int32     `gorm:"column:company_id;not null" json:"company_id"`                       // 企业id
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`                             // 用户uid
	Platform   int32     `gorm:"column:platform;not null" json:"platform"`                           // 操作的平台
	Action     int32     `gorm:"column:action;not null" json:"action"`                               // 具体操作
	EntityID   string    `gorm:"column:entity_id;not null" json:"entity_id"`                         // 操作的实体id，包含实体类型，例如 uid:123
	EntityName string    `gorm:"column:entity_name;not null" json:"entity_name"`                     // 实体名
	Old        string    `gorm:"column:old;not null" json:"old"`                                     // 操作前数据
	New        string    `gorm:"column:new;not null" json:"new"`                                     // 操作后数据
	AddTime    time.Time `gorm:"column:add_time;not null;default:CURRENT_TIMESTAMP" json:"add_time"` // 操作时间
}

// TableName Audit's table name
func (*Audit) TableName() string {
	return TableNameAudit
}
