// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3FieldValue = "bid_analysis_v3_field_value"

// BidAnalysisV3FieldValue mapped from table <bid_analysis_v3_field_value>
type BidAnalysisV3FieldValue struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID           int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	FieldID             int64     `gorm:"column:field_id;not null" json:"field_id"`                               // 字段ID
	RunID               int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	Origin              string    `gorm:"column:origin;not null;default:ai" json:"origin"`                        // ai/user
	ValueStatus         string    `gorm:"column:value_status;not null;default:active" json:"value_status"`        // active/suggestion/historical
	DisplayValue        string    `gorm:"column:display_value" json:"display_value"`                              // 字段展示值
	NormalizedValueJSON string    `gorm:"column:normalized_value_json" json:"normalized_value_json"`              // 标准化字段值JSON
	Confidence          string    `gorm:"column:confidence;not null;default:medium" json:"confidence"`            // 置信度
	IsUserEdited        bool      `gorm:"column:is_user_edited;not null" json:"is_user_edited"`                   // 是否用户编辑
	NeedsEvidence       bool      `gorm:"column:needs_evidence;not null" json:"needs_evidence"`                   // 是否待绑定证据
	CreatedBy           int64     `gorm:"column:created_by;not null" json:"created_by"`                           // 创建人ID
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt           time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3FieldValue's table name
func (*BidAnalysisV3FieldValue) TableName() string {
	return TableNameBidAnalysisV3FieldValue
}
