// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBidGenProject = "bid_gen_project"

// BidGenProject mapped from table <bid_gen_project>
type BidGenProject struct {
	ID                    int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name                  string         `gorm:"column:name;not null" json:"name"`                                       // 项目名称
	CreateType            string         `gorm:"column:create_type;not null;default:blank" json:"create_type"`           // 创建模式：tender_file-从招标文件创建，template-从模板创建，blank-空白标书
	TenderProjectID       int64          `gorm:"column:tender_project_id" json:"tender_project_id"`                      // 招标解析 V3 项目 ID
	BlueprintGenerationID *int64         `gorm:"column:blueprint_generation_id" json:"blueprint_generation_id"`          // 来源标书蓝图生成ID
	TemplateMaterialID    int64          `gorm:"column:template_material_id;not null" json:"template_material_id"`       // 关联素材模板ID（material_template.id），create_type=template时使用
	Status                string         `gorm:"column:status;not null;default:draft" json:"status"`                     // 项目状态：parsing-解析中，draft-草稿，generating-生成中，succeeded-已完成，failed-失败
	SourceFileBucket      string         `gorm:"column:source_file_bucket" json:"source_file_bucket"`                    // 源文件存储桶名（从招标文件/模板创建时）
	SourceFileName        string         `gorm:"column:source_file_name" json:"source_file_name"`                        // 源文件原始文件名
	SourceFileObject      string         `gorm:"column:source_file_object" json:"source_file_object"`                    // 源文件对象键（OSS）
	SourceFileURL         string         `gorm:"column:source_file_url" json:"source_file_url"`                          // 源文件访问URL
	ReviewProjectID       int64          `gorm:"column:review_project_id;not null" json:"review_project_id"`             // 已生成的审核项目ID（0=未生成）
	UserID                int64          `gorm:"column:user_id;not null" json:"user_id"`                                 // 创建用户ID
	UserTeamID            int32          `gorm:"column:user_team_id;not null" json:"user_team_id"`                       // 团队ID
	UserCompanyID         int32          `gorm:"column:user_company_id;not null" json:"user_company_id"`                 // 公司ID
	CreatedAt             time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt             time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedAt             gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 软删除时间
	Progress              int32          `gorm:"column:progress;not null" json:"progress"`                               // 解析进度 0-100
	Stage                 string         `gorm:"column:stage;not null" json:"stage"`                                     // 当前执行阶段
	StageStatus           string         `gorm:"column:stage_status" json:"stage_status"`                                // 阶段状态JSON
	LastError             string         `gorm:"column:last_error" json:"last_error"`                                    // 最近一次错误信息
}

// TableName BidGenProject's table name
func (*BidGenProject) TableName() string {
	return TableNameBidGenProject
}
