// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3Blueprint = "bid_analysis_v3_blueprint"

// BidAnalysisV3Blueprint mapped from table <bid_analysis_v3_blueprint>
type BidAnalysisV3Blueprint struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                           // 主键
	ProjectID             int64     `gorm:"column:project_id;not null" json:"project_id"`                                // 招标解析项目ID
	RunID                 int64     `gorm:"column:run_id;not null" json:"run_id"`                                        // 解析运行ID
	BlueprintGenerationID int64     `gorm:"column:blueprint_generation_id;not null" json:"blueprint_generation_id"`      // 蓝图生成ID
	ParentID              int64     `gorm:"column:parent_id;not null" json:"parent_id"`                                  // 父节点ID
	Level                 int32     `gorm:"column:level;not null;default:1" json:"level"`                                // 节点层级
	SortOrder             int32     `gorm:"column:sort_order;not null" json:"sort_order"`                                // 排序序号
	Title                 string    `gorm:"column:title;not null" json:"title"`                                          // 标题
	ClauseIdsJSON         string    `gorm:"column:clause_ids_json" json:"clause_ids_json"`                               // 关联条款ID列表JSON
	MaterialIdsJSON       string    `gorm:"column:material_ids_json" json:"material_ids_json"`                           // 关联素材ID列表JSON
	EvidenceIdsJSON       string    `gorm:"column:evidence_ids_json" json:"evidence_ids_json"`                           // 关联证据ID列表JSON
	NodeSource            string    `gorm:"column:node_source;not null;default:ai_suggested" json:"node_source"`         // system_root/tender_required/tender_outline/ai_suggested/user_added
	SuggestionStatus      string    `gorm:"column:suggestion_status;not null;default:accepted" json:"suggestion_status"` // pending/accepted/removed
	IsRequiredFile        bool      `gorm:"column:is_required_file;not null" json:"is_required_file"`                    // 是否必须提供文件
	IsUserAdded           bool      `gorm:"column:is_user_added;not null" json:"is_user_added"`                          // 是否用户新增
	IsAiSuggested         bool      `gorm:"column:is_ai_suggested;not null" json:"is_ai_suggested"`                      // 是否AI建议
	IsLocked              bool      `gorm:"column:is_locked;not null" json:"is_locked"`                                  // 是否锁定不可删除
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`      // 创建时间
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`      // 更新时间
}

// TableName BidAnalysisV3Blueprint's table name
func (*BidAnalysisV3Blueprint) TableName() string {
	return TableNameBidAnalysisV3Blueprint
}
