// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3StageRun = "bid_analysis_v3_stage_run"

// BidAnalysisV3StageRun mapped from table <bid_analysis_v3_stage_run>
type BidAnalysisV3StageRun struct {
	ID             int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID      int64      `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID          int64      `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	Stage          string     `gorm:"column:stage;not null" json:"stage"`                                     // 当前处理阶段
	Status         string     `gorm:"column:status;not null;default:pending" json:"status"`                   // pending/running/succeeded/partial/failed/skipped
	Weight         int32      `gorm:"column:weight;not null" json:"weight"`                                   // 阶段进度权重
	TotalUnits     int32      `gorm:"column:total_units;not null" json:"total_units"`                         // 任务单元总数
	CompletedUnits int32      `gorm:"column:completed_units;not null" json:"completed_units"`                 // 成功任务单元数
	FailedUnits    int32      `gorm:"column:failed_units;not null" json:"failed_units"`                       // 失败任务单元数
	WarningCount   int32      `gorm:"column:warning_count;not null" json:"warning_count"`                     // 告警数量
	Attempts       int32      `gorm:"column:attempts;not null" json:"attempts"`                               // 已尝试次数
	LastError      string     `gorm:"column:last_error" json:"last_error"`                                    // 最近一次错误信息
	StartedAt      *time.Time `gorm:"column:started_at" json:"started_at"`                                    // 开始时间
	CompletedAt    *time.Time `gorm:"column:completed_at" json:"completed_at"`                                // 完成时间
	CreatedAt      time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt      time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3StageRun's table name
func (*BidAnalysisV3StageRun) TableName() string {
	return TableNameBidAnalysisV3StageRun
}
