// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3DocumentChunk = "bid_analysis_v3_document_chunk"

// BidAnalysisV3DocumentChunk mapped from table <bid_analysis_v3_document_chunk>
type BidAnalysisV3DocumentChunk struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID      int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID          int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	ChunkNo        int32     `gorm:"column:chunk_no;not null" json:"chunk_no"`                               // 页块序号
	PageStart      int32     `gorm:"column:page_start;not null" json:"page_start"`                           // 起始页码
	PageEnd        int32     `gorm:"column:page_end;not null" json:"page_end"`                               // 结束页码
	PdfAssetID     int64     `gorm:"column:pdf_asset_id;not null" json:"pdf_asset_id"`                       // 页块PDF资产ID
	DoclingAssetID int64     `gorm:"column:docling_asset_id;not null" json:"docling_asset_id"`               // Docling结果资产ID
	Status         string    `gorm:"column:status;not null;default:pending" json:"status"`                   // 状态
	Attempts       int32     `gorm:"column:attempts;not null" json:"attempts"`                               // 已尝试次数
	TextChars      int32     `gorm:"column:text_chars;not null" json:"text_chars"`                           // 文本字符数
	BlockCount     int32     `gorm:"column:block_count;not null" json:"block_count"`                         // 文本块数量
	TableCount     int32     `gorm:"column:table_count;not null" json:"table_count"`                         // 表格数量
	Checksum       string    `gorm:"column:checksum;not null" json:"checksum"`                               // 结果校验和
	ProcessingMs   int64     `gorm:"column:processing_ms;not null" json:"processing_ms"`                     // 处理耗时（毫秒）
	LastError      string    `gorm:"column:last_error" json:"last_error"`                                    // 最近一次错误信息
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3DocumentChunk's table name
func (*BidAnalysisV3DocumentChunk) TableName() string {
	return TableNameBidAnalysisV3DocumentChunk
}
