// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidOutline = "bid_outline"

// BidOutline mapped from table <bid_outline>
type BidOutline struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID int64     `gorm:"column:project_id;not null" json:"project_id"`                  // 所属投标生成项目ID（bid_project.id）
	ParentID  int64     `gorm:"column:parent_id;not null" json:"parent_id"`                    // 父标题ID（自关联）；0表示顶层
	Level     int32     `gorm:"column:level;not null;default:1" json:"level"`                  // 标题层级：1-4
	SortOrder int32     `gorm:"column:sort_order;not null" json:"sort_order"`                  // 同级内排序号，数值越小越靠前
	Title     string    `gorm:"column:title;not null" json:"title"`                            // 标题名称
	Source    string    `gorm:"column:source;not null;default:agent" json:"source"`            // 数据来源,枚举：agent/user
	Status    bool      `gorm:"column:status" json:"status"`                                   // 是否已审核确认：1是，0否
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidOutline's table name
func (*BidOutline) TableName() string {
	return TableNameBidOutline
}
