// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3Clause = "bid_analysis_v3_clause"

// BidAnalysisV3Clause mapped from table <bid_analysis_v3_clause>
type BidAnalysisV3Clause struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID        int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID            int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	ChapterID        int64     `gorm:"column:chapter_id;not null" json:"chapter_id"`                           // 章节ID
	Title            string    `gorm:"column:title;not null" json:"title"`                                     // 标题
	Content          string    `gorm:"column:content" json:"content"`                                          // 正文内容
	AiInterpretation string    `gorm:"column:ai_interpretation" json:"ai_interpretation"`                      // 条款AI解读
	Importance       string    `gorm:"column:importance;not null;default:medium" json:"importance"`            // 重要程度
	Status           string    `gorm:"column:status;not null;default:pending" json:"status"`                   // 状态
	SortOrder        int32     `gorm:"column:sort_order;not null" json:"sort_order"`                           // 排序序号
	IsUserAdded      bool      `gorm:"column:is_user_added;not null" json:"is_user_added"`                     // 是否用户新增
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3Clause's table name
func (*BidAnalysisV3Clause) TableName() string {
	return TableNameBidAnalysisV3Clause
}
