// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidProject = "bid_project"

// BidProject mapped from table <bid_project>
type BidProject struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string    `gorm:"column:name;not null" json:"name"`                              // 项目名称
	BidTypeID       int64     `gorm:"column:bid_type_id;not null" json:"bid_type_id"`                // 项目类型（关联tender_type表ID）
	CompanyName     string    `gorm:"column:company_name;not null" json:"company_name"`              // 招标单位名称
	CreateType      string    `gorm:"column:create_type;not null" json:"create_type"`                // 投标文件生成方式，枚举：analysis,history_file,history_template,direct
	TenderProjectID int64     `gorm:"column:tender_project_id;not null" json:"tender_project_id"`    // 关联的招标项目ID，关联tender_project表，create_type=analysis时专用
	TemplateID      string    `gorm:"column:template_id;not null" json:"template_id"`                // 使用的模板ID，create_type=history_template时专用
	FileBucket      string    `gorm:"column:file_bucket;not null" json:"file_bucket"`                // 存放文件的桶名称
	FileName        string    `gorm:"column:file_name;not null" json:"file_name"`                    // 原始文件名
	FileObject      string    `gorm:"column:file_object" json:"file_object"`                         // 文件对象键
	FileURL         string    `gorm:"column:file_url" json:"file_url"`                               // 文件访问URL
	Status          string    `gorm:"column:status;not null;default:pending" json:"status"`          // 生成状态：pending/running/succeeded/failed
	Progress        int32     `gorm:"column:progress;not null" json:"progress"`                      // 生成进度：0-100
	Stage           string    `gorm:"column:stage;not null" json:"stage"`                            // 当前执行阶段
	LastError       string    `gorm:"column:last_error" json:"last_error"`                           // 最近一次错误信息
	IsFinalConfirm  bool      `gorm:"column:is_final_confirm;not null" json:"is_final_confirm"`      // 是否终审确认标识，1-已终审，0-未终审
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`                        // 创建记录的用户ID
	UserTeamID      int32     `gorm:"column:user_team_id" json:"user_team_id"`                       // 项目所属团队ID，即创建人所属团队ID
	UserCompanyID   int32     `gorm:"column:user_company_id" json:"user_company_id"`                 // 项目所属公司ID，即创建人所属公司ID
	Ddl             string    `gorm:"column:ddl;not null" json:"ddl"`                                // 投标截止时间
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 记录创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"` // 记录更新时间
}

// TableName BidProject's table name
func (*BidProject) TableName() string {
	return TableNameBidProject
}
