// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3DocumentPage = "bid_analysis_v3_document_page"

// BidAnalysisV3DocumentPage mapped from table <bid_analysis_v3_document_page>
type BidAnalysisV3DocumentPage struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID     int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	ChunkID   int64     `gorm:"column:chunk_id;not null" json:"chunk_id"`                               // 文档页块ID
	PageNo    int32     `gorm:"column:page_no;not null" json:"page_no"`                                 // 全局页码
	Width     float64   `gorm:"column:width;not null;default:0.0000" json:"width"`                      // 页面宽度
	Height    float64   `gorm:"column:height;not null;default:0.0000" json:"height"`                    // 页面高度
	TextChars int32     `gorm:"column:text_chars;not null" json:"text_chars"`                           // 文本字符数
	OcrUsed   bool      `gorm:"column:ocr_used;not null" json:"ocr_used"`                               // 是否使用OCR
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3DocumentPage's table name
func (*BidAnalysisV3DocumentPage) TableName() string {
	return TableNameBidAnalysisV3DocumentPage
}
