// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3FieldValueEvidence = "bid_analysis_v3_field_value_evidence"

// BidAnalysisV3FieldValueEvidence mapped from table <bid_analysis_v3_field_value_evidence>
type BidAnalysisV3FieldValueEvidence struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID     int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID         int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	FieldValueID  int64     `gorm:"column:field_value_id;not null" json:"field_value_id"`                   // 字段值ID
	SourceKind    string    `gorm:"column:source_kind;not null" json:"source_kind"`                         // text_block/source_table/manual_text/manual_table
	BlockID       int64     `gorm:"column:block_id;not null" json:"block_id"`                               // 文档文本块ID
	SourceTableID int64     `gorm:"column:source_table_id;not null" json:"source_table_id"`                 // 原文表格ID
	PageNo        int32     `gorm:"column:page_no;not null" json:"page_no"`                                 // 全局页码
	Quote         string    `gorm:"column:quote" json:"quote"`                                              // 证据原文摘要
	BboxLeft      float64   `gorm:"column:bbox_left;not null;default:0.00000000" json:"bbox_left"`          // 归一化左侧坐标
	BboxTop       float64   `gorm:"column:bbox_top;not null;default:0.00000000" json:"bbox_top"`            // 归一化顶部坐标
	BboxWidth     float64   `gorm:"column:bbox_width;not null;default:0.00000000" json:"bbox_width"`        // 归一化区域宽度
	BboxHeight    float64   `gorm:"column:bbox_height;not null;default:0.00000000" json:"bbox_height"`      // 归一化区域高度
	SortOrder     int32     `gorm:"column:sort_order;not null" json:"sort_order"`                           // 排序序号
	ContentHash   string    `gorm:"column:content_hash;not null" json:"content_hash"`                       // 内容哈希
	CreatedBy     int64     `gorm:"column:created_by;not null" json:"created_by"`                           // 创建人ID
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3FieldValueEvidence's table name
func (*BidAnalysisV3FieldValueEvidence) TableName() string {
	return TableNameBidAnalysisV3FieldValueEvidence
}
