// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3DeletionJob = "bid_analysis_v3_deletion_job"

// BidAnalysisV3DeletionJob mapped from table <bid_analysis_v3_deletion_job>
type BidAnalysisV3DeletionJob struct {
	ID                int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	DeletedProjectID  int64      `gorm:"column:deleted_project_id;not null" json:"deleted_project_id"`           // 删除墓碑ID
	OriginalProjectID int64      `gorm:"column:original_project_id;not null" json:"original_project_id"`         // 原招标解析项目ID
	Status            string     `gorm:"column:status;not null;default:pending" json:"status"`                   // 状态
	TotalObjects      int32      `gorm:"column:total_objects;not null" json:"total_objects"`                     // 待删除对象总数
	DeletedObjects    int32      `gorm:"column:deleted_objects;not null" json:"deleted_objects"`                 // 已删除对象数
	FailedObjects     int32      `gorm:"column:failed_objects;not null" json:"failed_objects"`                   // 删除失败对象数
	Attempts          int32      `gorm:"column:attempts;not null" json:"attempts"`                               // 已尝试次数
	LastError         string     `gorm:"column:last_error" json:"last_error"`                                    // 最近一次错误信息
	CreatedAt         time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt         time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	CompletedAt       *time.Time `gorm:"column:completed_at" json:"completed_at"`                                // 完成时间
}

// TableName BidAnalysisV3DeletionJob's table name
func (*BidAnalysisV3DeletionJob) TableName() string {
	return TableNameBidAnalysisV3DeletionJob
}
