// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3OperationLog = "bid_analysis_v3_operation_log"

// BidAnalysisV3OperationLog mapped from table <bid_analysis_v3_operation_log>
type BidAnalysisV3OperationLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID  int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID      int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	TargetType string    `gorm:"column:target_type;not null;default:project" json:"target_type"`         // 操作对象类型
	TargetID   int64     `gorm:"column:target_id;not null" json:"target_id"`                             // 操作对象ID
	Action     string    `gorm:"column:action;not null" json:"action"`                                   // 操作类型
	OperatorID int64     `gorm:"column:operator_id;not null" json:"operator_id"`                         // 操作人ID
	DetailJSON string    `gorm:"column:detail_json" json:"detail_json"`                                  // 结构化详情JSON
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3OperationLog's table name
func (*BidAnalysisV3OperationLog) TableName() string {
	return TableNameBidAnalysisV3OperationLog
}
