// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidReviewProject = "bid_review_project"

// BidReviewProject mapped from table <bid_review_project>
type BidReviewProject struct {
	ID                    int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name                  string    `gorm:"column:name;not null" json:"name"`                                           // 项目名称
	CreateType            string    `gorm:"column:create_type;not null;default:manual" json:"create_type"`              // 创建方式: manual-上传创建, gen-从标书生成
	Status                string    `gorm:"column:status;not null;default:running" json:"status"`                       // 状态: running/succeed/failed
	Stage                 string    `gorm:"column:stage;not null" json:"stage"`                                         // 当前执行阶段
	Progress              int32     `gorm:"column:progress;not null" json:"progress"`                                   // 进度 0-100
	StageStatus           string    `gorm:"column:stage_status" json:"stage_status"`                                    // 阶段状态JSON
	LastError             string    `gorm:"column:last_error" json:"last_error"`                                        // 最近一次错误信息
	SourceBidGenProjectID int64     `gorm:"column:source_bid_gen_project_id;not null" json:"source_bid_gen_project_id"` // 来源标书生成项目ID（create_type=gen时）
	TenderFileCount       int32     `gorm:"column:tender_file_count;not null" json:"tender_file_count"`                 // 招标文件数
	BidFileCount          int32     `gorm:"column:bid_file_count;not null" json:"bid_file_count"`                       // 投标文件数
	TotalItems            int32     `gorm:"column:total_items;not null" json:"total_items"`                             // 检查项总数
	WarningItems          int32     `gorm:"column:warning_items;not null" json:"warning_items"`                         // 告警项数
	ErrorItems            int32     `gorm:"column:error_items;not null" json:"error_items"`                             // 高风险项数
	PassedItems           int32     `gorm:"column:passed_items;not null" json:"passed_items"`                           // 通过项数
	UserID                int64     `gorm:"column:user_id;not null" json:"user_id"`                                     // 创建用户ID
	UserTeamID            int32     `gorm:"column:user_team_id;not null" json:"user_team_id"`                           // 所属团队ID
	UserCompanyID         int32     `gorm:"column:user_company_id;not null" json:"user_company_id"`                     // 所属公司ID
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`     // 创建时间
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`     // 更新时间
}

// TableName BidReviewProject's table name
func (*BidReviewProject) TableName() string {
	return TableNameBidReviewProject
}
