// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3Summary = "bid_analysis_v3_summary"

// BidAnalysisV3Summary mapped from table <bid_analysis_v3_summary>
type BidAnalysisV3Summary struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID   int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID       int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	SummaryJSON string    `gorm:"column:summary_json;not null" json:"summary_json"`                       // 摘要内容JSON
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3Summary's table name
func (*BidAnalysisV3Summary) TableName() string {
	return TableNameBidAnalysisV3Summary
}
