// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBidAnalysisV3ProjectDeleted = "bid_analysis_v3_project_deleted"

// BidAnalysisV3ProjectDeleted mapped from table <bid_analysis_v3_project_deleted>
type BidAnalysisV3ProjectDeleted struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	OriginalProjectID int64          `gorm:"column:original_project_id;not null" json:"original_project_id"`         // 原招标解析项目ID
	Name              string         `gorm:"column:name;not null" json:"name"`                                       // 名称
	SourceFileName    string         `gorm:"column:source_file_name;not null" json:"source_file_name"`               // 原始文件名
	SourceSha256      string         `gorm:"column:source_sha256;not null" json:"source_sha256"`                     // 原始文件SHA256
	FinalStatus       string         `gorm:"column:final_status;not null" json:"final_status"`                       // 删除前最终状态
	PageCount         int32          `gorm:"column:page_count;not null" json:"page_count"`                           // 文档总页数
	FieldCount        int32          `gorm:"column:field_count;not null" json:"field_count"`                         // 字段数量
	EvidenceCount     int32          `gorm:"column:evidence_count;not null" json:"evidence_count"`                   // 证据数量
	WarningCount      int32          `gorm:"column:warning_count;not null" json:"warning_count"`                     // 告警数量
	UserID            int64          `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户ID
	UserTeamID        int32          `gorm:"column:user_team_id;not null" json:"user_team_id"`                       // 用户团队ID
	UserCompanyID     int32          `gorm:"column:user_company_id;not null" json:"user_company_id"`                 // 用户公司ID
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	DeletedBy         int64          `gorm:"column:deleted_by;not null" json:"deleted_by"`                           // 删除人ID
	DeleteReason      string         `gorm:"column:delete_reason;not null" json:"delete_reason"`                     // 删除原因
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;not null;default:CURRENT_TIMESTAMP" json:"deleted_at"` // 删除时间
}

// TableName BidAnalysisV3ProjectDeleted's table name
func (*BidAnalysisV3ProjectDeleted) TableName() string {
	return TableNameBidAnalysisV3ProjectDeleted
}
