// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidGenChapterSpec = "bid_gen_chapter_spec"

// BidGenChapterSpec mapped from table <bid_gen_chapter_spec>
type BidGenChapterSpec struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID    int64     `gorm:"column:project_id;not null" json:"project_id"`
	OutlineID    int64     `gorm:"column:outline_id;not null" json:"outline_id"`
	GenTaskID    int64     `gorm:"column:gen_task_id;not null" json:"gen_task_id"`
	TargetWords  int32     `gorm:"column:target_words;not null" json:"target_words"`
	PointsJSON   string    `gorm:"column:points_json" json:"points_json"`
	EvidenceJSON string    `gorm:"column:evidence_json" json:"evidence_json"`
	TablesJSON   string    `gorm:"column:tables_json" json:"tables_json"`
	FiguresJSON  string    `gorm:"column:figures_json" json:"figures_json"`
	ScoringJSON  string    `gorm:"column:scoring_json" json:"scoring_json"`
	CoverageJSON string    `gorm:"column:coverage_json" json:"coverage_json"`
	Model        string    `gorm:"column:model;not null" json:"model"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName BidGenChapterSpec's table name
func (*BidGenChapterSpec) TableName() string {
	return TableNameBidGenChapterSpec
}
