// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidGenOutline = "bid_gen_outline"

// BidGenOutline mapped from table <bid_gen_outline>
type BidGenOutline struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID      int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 所属项目ID（bid_gen_project.id）
	ParentID       int64     `gorm:"column:parent_id;not null" json:"parent_id"`                             // 父节点ID（自关联bid_gen_outline.id）；0表示顶层
	Level          int32     `gorm:"column:level;not null;default:1" json:"level"`                           // 标题层级：1-4
	SortOrder      int32     `gorm:"column:sort_order;not null" json:"sort_order"`                           // 同级内排序号，数值越小越靠前
	Title          string    `gorm:"column:title;not null" json:"title"`                                     // 标题名称
	ClauseIds      string    `gorm:"column:clause_ids" json:"clause_ids"`                                    // 关联条款ID列表（JSON array，来自招标解析的条款）
	MaterialIds    string    `gorm:"column:material_ids" json:"material_ids"`                                // 推荐素材ID列表（JSON array，来自蓝图的素材推荐）
	GenStatus      string    `gorm:"column:gen_status;not null;default:pending" json:"gen_status"`           // 生成状态：pending-待生成，generating-生成中，succeeded-已完成，failed-失败
	Source         string    `gorm:"column:source;not null;default:ai" json:"source"`                        // 数据来源：ai-AI提取/建议，user-用户手动添加，system_root-系统文档根
	IsRequiredFile bool      `gorm:"column:is_required_file;not null" json:"is_required_file"`               // 是否必须包含的文件节点：1是，0否
	IsAiSuggested  bool      `gorm:"column:is_ai_suggested;not null" json:"is_ai_suggested"`                 // 是否AI建议补充节点（基于行业最佳实践）：1是，0否
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidGenOutline's table name
func (*BidGenOutline) TableName() string {
	return TableNameBidGenOutline
}
