// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidReviewExportRecord = "bid_review_export_record"

// BidReviewExportRecord mapped from table <bid_review_export_record>
type BidReviewExportRecord struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID  int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 审核项目ID
	FileName   string    `gorm:"column:file_name;not null" json:"file_name"`                             // 导出文件名
	FileBucket string    `gorm:"column:file_bucket;not null" json:"file_bucket"`                         // 存储桶
	FileObject string    `gorm:"column:file_object;not null" json:"file_object"`                         // 对象键
	FileURL    string    `gorm:"column:file_url;not null" json:"file_url"`                               // 访问URL
	UserID     int64     `gorm:"column:user_id;not null" json:"user_id"`                                 // 导出人ID
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 导出时间
}

// TableName BidReviewExportRecord's table name
func (*BidReviewExportRecord) TableName() string {
	return TableNameBidReviewExportRecord
}
