// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidGenChapterContent = "bid_gen_chapter_content"

// BidGenChapterContent mapped from table <bid_gen_chapter_content>
type BidGenChapterContent struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID   int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 所属项目ID（bid_gen_project.id）
	OutlineID   int64     `gorm:"column:outline_id;not null" json:"outline_id"`                           // 关联大纲节点ID（bid_gen_outline.id）
	ContentJSON string    `gorm:"column:content_json" json:"content_json"`                                // 章节正文内容（ProseMirror JSON片段）
	ContentHTML string    `gorm:"column:content_html" json:"content_html"`                                // 章节正文内容（HTML片段）
	WordCount   int32     `gorm:"column:word_count;not null" json:"word_count"`                           // 字数统计
	Source      string    `gorm:"column:source;not null;default:ai" json:"source"`                        // 内容来源：ai-AI生成，user-用户编辑
	GenTaskID   int64     `gorm:"column:gen_task_id;not null" json:"gen_task_id"`                         // 最近一次生成任务ID（bid_gen_task.id）
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidGenChapterContent's table name
func (*BidGenChapterContent) TableName() string {
	return TableNameBidGenChapterContent
}
