// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidReviewOpLog = "bid_review_op_log"

// BidReviewOpLog mapped from table <bid_review_op_log>
type BidReviewOpLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID  int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 审核项目ID
	ItemID     int64     `gorm:"column:item_id;not null" json:"item_id"`                                 // 检查项ID（0=项目级操作）
	Action     string    `gorm:"column:action;not null" json:"action"`                                   // 动作: confirm/needs_fix/na/retry/add/delete/export
	OperatorID int64     `gorm:"column:operator_id;not null" json:"operator_id"`                         // 操作人ID
	Detail     string    `gorm:"column:detail" json:"detail"`                                            // 操作详情
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 操作时间
}

// TableName BidReviewOpLog's table name
func (*BidReviewOpLog) TableName() string {
	return TableNameBidReviewOpLog
}
