// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBidAnalysisV3Chapter = "bid_analysis_v3_chapter"

// BidAnalysisV3Chapter mapped from table <bid_analysis_v3_chapter>
type BidAnalysisV3Chapter struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	ProjectID      int64     `gorm:"column:project_id;not null" json:"project_id"`                           // 招标解析项目ID
	RunID          int64     `gorm:"column:run_id;not null" json:"run_id"`                                   // 解析运行ID
	ChapterType    string    `gorm:"column:chapter_type;not null;default:other" json:"chapter_type"`         // 章节类型
	ChapterTitle   string    `gorm:"column:chapter_title;not null" json:"chapter_title"`                     // 章节标题
	PageStart      int32     `gorm:"column:page_start;not null" json:"page_start"`                           // 起始页码
	PageEnd        int32     `gorm:"column:page_end;not null" json:"page_end"`                               // 结束页码
	SortOrder      int32     `gorm:"column:sort_order;not null" json:"sort_order"`                           // 排序序号
	Summary        string    `gorm:"column:summary" json:"summary"`                                          // 摘要
	BoundarySource string    `gorm:"column:boundary_source;not null;default:rule" json:"boundary_source"`    // rule/llm/fallback
	Status         string    `gorm:"column:status;not null;default:identified" json:"status"`                // 状态
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName BidAnalysisV3Chapter's table name
func (*BidAnalysisV3Chapter) TableName() string {
	return TableNameBidAnalysisV3Chapter
}
