// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompany = "company"

// Company mapped from table <company>
type Company struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`                         // 公司名称
	ApproveAdminID int64  `gorm:"column:approve_admin_id;not null" json:"approve_admin_id"` // 审核人
	ApplyUserID    int64  `gorm:"column:apply_user_id;not null" json:"apply_user_id"`       // 申请认证的人
	CreateTime     int64  `gorm:"column:create_time;not null" json:"create_time"`           // 创建时间
	UpdateTime     int64  `gorm:"column:update_time;not null" json:"update_time"`           // 更新时间
	Status         int32  `gorm:"column:status;not null" json:"status"`                     // 公司状态: 0, 未认证; 1, 已认证
	DocNum         int32  `gorm:"column:doc_num;not null" json:"doc_num"`
	LimitDocNum    int32  `gorm:"column:limit_doc_num;not null;default:10000" json:"limit_doc_num"`
	OwnerID        int64  `gorm:"column:owner_id;not null" json:"owner_id"` // 公司负责人ID，对应user表主键
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
