// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEnterpriseTemplate = "enterprise_template"

// EnterpriseTemplate mapped from table <enterprise_template>
type EnterpriseTemplate struct {
	ID                  string `gorm:"column:id;primaryKey" json:"id"`
	TemplateName        string `gorm:"column:template_name;not null" json:"template_name"`               // 模板名称
	TemplateDescription string `gorm:"column:template_description;not null" json:"template_description"` // 模板描述
	DocumentPermission  string `gorm:"column:document_permission;not null" json:"document_permission"`   // 文档权限
	AttachmentPath      string `gorm:"column:attachment_path" json:"attachment_path"`                    // 附件
	AttachmentName      string `gorm:"column:attachment_name" json:"attachment_name"`                    // 附件名称
	CompanyID           int32  `gorm:"column:company_id" json:"company_id"`                              // 所属公司ID
	TeamID              int32  `gorm:"column:team_id" json:"team_id"`                                    // 所属团队Id
	CreatedBy           int32  `gorm:"column:created_by" json:"created_by"`                              // 创建人
	CreatedAt           int64  `gorm:"column:created_at" json:"created_at"`                              // 创建时间
	UpdatedAt           int64  `gorm:"column:updated_at" json:"updated_at"`                              // 更新时间
}

// TableName EnterpriseTemplate's table name
func (*EnterpriseTemplate) TableName() string {
	return TableNameEnterpriseTemplate
}
