// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFeedbackRecord = "feedback_record"

// FeedbackRecord mapped from table <feedback_record>
type FeedbackRecord struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键ID
	Type        string    `gorm:"column:type;not null" json:"type"`                  // 反馈类型，枚举：suggest、question、bug、other
	Description string    `gorm:"column:description;not null" json:"description"`    // 反馈描述
	UserID      int64     `gorm:"column:user_id;not null" json:"user_id"`            // 用户ID
	Nickname    string    `gorm:"column:nickname" json:"nickname"`                   // 用户姓名
	CompanyID   int32     `gorm:"column:company_id;not null" json:"company_id"`      // 公司ID
	PhotoKeys   string    `gorm:"column:photo_keys;not null" json:"photo_keys"`      // 截图COS对象键(JSON数组字符串)
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime  time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	Status      int32     `gorm:"column:status;not null;default:1" json:"status"` // 状态：1可用 0不可用
}

// TableName FeedbackRecord's table name
func (*FeedbackRecord) TableName() string {
	return TableNameFeedbackRecord
}
