// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFeishuAccountBinding = "feishu_account_binding"

// FeishuAccountBinding mapped from table <feishu_account_binding>
type FeishuAccountBinding struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID         string    `gorm:"column:app_id;not null" json:"app_id"`
	OpenID        string    `gorm:"column:open_id;not null" json:"open_id"`
	TenantKey     string    `gorm:"column:tenant_key;not null" json:"tenant_key"`
	UserID        int64     `gorm:"column:user_id;not null" json:"user_id"`
	NotifyEnabled int32     `gorm:"column:notify_enabled;not null;default:1" json:"notify_enabled"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"`
}

// TableName FeishuAccountBinding's table name
func (*FeishuAccountBinding) TableName() string {
	return TableNameFeishuAccountBinding
}
