// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaterialTemplate = "material_template"

// MaterialTemplate mapped from table <material_template>
type MaterialTemplate struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Stage       string    `gorm:"column:stage;not null" json:"stage"`
	LastError   string    `gorm:"column:last_error" json:"last_error"`
	UserID      int64     `gorm:"column:user_id" json:"user_id"`
	CompanyID   int32     `gorm:"column:company_id" json:"company_id"`
	CreatedAt   time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MaterialTemplate's table name
func (*MaterialTemplate) TableName() string {
	return TableNameMaterialTemplate
}
