// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMaterialImageInfo = "material_image_info"

// MaterialImageInfo mapped from table <material_image_info>
type MaterialImageInfo struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`             // 主键ID
	MaterialID      int64     `gorm:"column:material_id;not null" json:"material_id"`                // 素材ID，关联material_info表主键ID
	MaterialFileID  int64     `gorm:"column:material_file_id;not null" json:"material_file_id"`      // 素材文件ID，关联material_file_info表主键ID
	Name            string    `gorm:"column:name;not null" json:"name"`                              // 图片名称
	Description     string    `gorm:"column:description" json:"description"`                         // 图片描述
	Size            int64     `gorm:"column:size;not null" json:"size"`                              // 文档大小，单位bytes
	OriginObjectKey string    `gorm:"column:origin_object_key;not null" json:"origin_object_key"`    // 原始图片的对象存储objectKey
	ObjectKey       string    `gorm:"column:object_key;not null" json:"object_key"`                  // 最新版图片的对象存储objectKey
	SortOrder       int32     `gorm:"column:sort_order;not null" json:"sort_order"`                  // 页码索引
	EditFlow        string    `gorm:"column:edit_flow" json:"edit_flow"`                             // 图片编辑流json
	UserID          int64     `gorm:"column:user_id;not null" json:"user_id"`                        // 上传用户ID，对应user表主键
	CompanyID       int32     `gorm:"column:company_id" json:"company_id"`                           // 用户所属公司ID，对应company表的主键ID
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 上传时间
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName MaterialImageInfo's table name
func (*MaterialImageInfo) TableName() string {
	return TableNameMaterialImageInfo
}
