// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelAlert = "tender_intel_alert"

// TenderIntelAlert mapped from table <tender_intel_alert>
type TenderIntelAlert struct {
	ID                  int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	UserID              int64      `gorm:"column:user_id;not null" json:"user_id"`                                 // 接收用户 ID
	SubscriptionID      int64      `gorm:"column:subscription_id;not null" json:"subscription_id"`                 // 订阅规则 ID
	NoticeID            int64      `gorm:"column:notice_id;not null" json:"notice_id"`                             // 公告 ID
	SubscriptionName    string     `gorm:"column:subscription_name;not null" json:"subscription_name"`             // 订阅名称快照
	NoticeTitle         string     `gorm:"column:notice_title;not null" json:"notice_title"`                       // 公告标题快照
	MatchedKeywords     string     `gorm:"column:matched_keywords;not null" json:"matched_keywords"`               // 命中的关键词（JSON 数组）
	MatchedReason       string     `gorm:"column:matched_reason;not null" json:"matched_reason"`                   // 命中原因说明
	MatchSource         string     `gorm:"column:match_source;not null;default:collect" json:"match_source"`       // 提醒来源：collect采集命中/backfill历史回溯命中
	IsRead              int32      `gorm:"column:is_read;not null" json:"is_read"`                                 // 是否已读：1=已读
	ReadAt              *time.Time `gorm:"column:read_at" json:"read_at"`                                          // 读取时间
	CreatedAt           time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt           time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	FeishuPushStatus    string     `gorm:"column:feishu_push_status;not null;default:legacy" json:"feishu_push_status"`
	FeishuPushAttempts  int32      `gorm:"column:feishu_push_attempts;not null" json:"feishu_push_attempts"`
	FeishuPushNextAt    *time.Time `gorm:"column:feishu_push_next_at" json:"feishu_push_next_at"`
	FeishuPushMessageID string     `gorm:"column:feishu_push_message_id;not null" json:"feishu_push_message_id"`
	FeishuPushLastError string     `gorm:"column:feishu_push_last_error;not null" json:"feishu_push_last_error"`
	FeishuPushSentAt    *time.Time `gorm:"column:feishu_push_sent_at" json:"feishu_push_sent_at"`
}

// TableName TenderIntelAlert's table name
func (*TenderIntelAlert) TableName() string {
	return TableNameTenderIntelAlert
}
