// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelNotice = "tender_intel_notice"

// TenderIntelNotice mapped from table <tender_intel_notice>
type TenderIntelNotice struct {
	ID                int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                            // 主键
	SourceKey         string     `gorm:"column:source_key;not null" json:"source_key"`                                 // 来源源标识
	SourceName        string     `gorm:"column:source_name;not null" json:"source_name"`                               // 来源名称
	SourceCategory    string     `gorm:"column:source_category;not null" json:"source_category"`                       // 来源网站性质
	Origin            string     `gorm:"column:origin;not null;default:collect" json:"origin"`                         // 入库来源：collect=自动采集，manual=系统录入
	ImportBatch       string     `gorm:"column:import_batch;not null" json:"import_batch"`                             // 手工录入/批量导入的批次号（自动采集为空）
	CollectRunID      string     `gorm:"column:collect_run_id;not null" json:"collect_run_id"`                         // 首次入库的采集批次 ID
	URL               string     `gorm:"column:url;not null" json:"url"`                                               // 原始链接
	CanonicalURL      string     `gorm:"column:canonical_url;not null" json:"canonical_url"`                           // 规范化链接
	URLHash           string     `gorm:"column:url_hash;not null" json:"url_hash"`                                     // 规范化链接 SHA-256，唯一键
	ExternalID        string     `gorm:"column:external_id;not null" json:"external_id"`                               // 来源站公告 ID
	Title             string     `gorm:"column:title;not null" json:"title"`                                           // 公告标题
	Publisher         string     `gorm:"column:publisher;not null" json:"publisher"`                                   // 采购人
	Agency            string     `gorm:"column:agency;not null" json:"agency"`                                         // 代理机构
	ProjectCode       string     `gorm:"column:project_code;not null" json:"project_code"`                             // 项目编号
	BudgetText        string     `gorm:"column:budget_text;not null" json:"budget_text"`                               // 预算原文
	BudgetAmount      *float64   `gorm:"column:budget_amount" json:"budget_amount"`                                    // 预算金额（元）
	RegionProvince    string     `gorm:"column:region_province;not null" json:"region_province"`                       // 省级地区
	RegionCity        string     `gorm:"column:region_city;not null" json:"region_city"`                               // 市级地区
	RegionText        string     `gorm:"column:region_text;not null" json:"region_text"`                               // 地区原文
	NoticeType        string     `gorm:"column:notice_type;not null;default:other" json:"notice_type"`                 // 公告类型：open_tender公开招标/invite_tender邀请招标/negotiation竞争性磋商/tender_negotiation竞争性谈判/inquiry询价/prequalification资格预审/single_source单一来源/change变更澄清/terminate终止/other其他
	NoticeStage       string     `gorm:"column:notice_stage;not null;default:procurement" json:"notice_stage"`         // 公告阶段：procurement采购公告/prequalification预审/change变更澄清/other其他
	PublishDate       *time.Time `gorm:"column:publish_date" json:"publish_date"`                                      // 发布日期
	PublishAt         *time.Time `gorm:"column:publish_at" json:"publish_at"`                                          // 发布精确时间
	DeadlineAt        *time.Time `gorm:"column:deadline_at" json:"deadline_at"`                                        // 投标/响应截止时间
	BodyHTML          string     `gorm:"column:body_html" json:"body_html"`                                            // 清洗后的正文语义 HTML
	BodyMarkdown      string     `gorm:"column:body_markdown" json:"body_markdown"`                                    // 正文 Markdown
	BodyText          string     `gorm:"column:body_text" json:"body_text"`                                            // 正文纯文本
	ContentHash       string     `gorm:"column:content_hash;not null" json:"content_hash"`                             // 正文内容哈希
	Attachments       string     `gorm:"column:attachments" json:"attachments"`                                        // 附件链接（JSON 数组）
	FetchStrategy     string     `gorm:"column:fetch_strategy;not null" json:"fetch_strategy"`                         // 抽取策略
	ExtractConfidence float64    `gorm:"column:extract_confidence;not null;default:0.0000" json:"extract_confidence"`  // 抽取置信度 0-1
	ExtractWarnings   string     `gorm:"column:extract_warnings" json:"extract_warnings"`                              // 抽取告警（JSON 数组）
	TagStatus         string     `gorm:"column:tag_status;not null;default:pending" json:"tag_status"`                 // 打标状态：pending/done/failed
	Status            string     `gorm:"column:status;not null;default:normal" json:"status"`                          // 公告状态：normal/duplicate/invalid/archived
	Pinned            int32      `gorm:"column:pinned;not null" json:"pinned"`                                         // 置顶：1=置顶，0=普通
	PinnedAt          *time.Time `gorm:"column:pinned_at" json:"pinned_at"`                                            // 置顶时间（取消置顶后清空）
	AdminNote         string     `gorm:"column:admin_note;not null" json:"admin_note"`                                 // 管理备注（隐藏/下架原因等）
	FirstSeenAt       time.Time  `gorm:"column:first_seen_at;not null;default:CURRENT_TIMESTAMP" json:"first_seen_at"` // 首次发现时间
	LastSeenAt        time.Time  `gorm:"column:last_seen_at;not null;default:CURRENT_TIMESTAMP" json:"last_seen_at"`   // 最近发现时间
	CreatedAt         time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`       // 创建时间
	UpdatedAt         time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`       // 更新时间
}

// TableName TenderIntelNotice's table name
func (*TenderIntelNotice) TableName() string {
	return TableNameTenderIntelNotice
}
