// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelRunSource = "tender_intel_run_source"

// TenderIntelRunSource mapped from table <tender_intel_run_source>
type TenderIntelRunSource struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	RunID        string    `gorm:"column:run_id;not null" json:"run_id"`                                   // 批次 ID
	SourceKey    string    `gorm:"column:source_key;not null" json:"source_key"`                           // 源标识
	SourceName   string    `gorm:"column:source_name;not null" json:"source_name"`                         // 源名称快照
	Status       string    `gorm:"column:status;not null;default:running" json:"status"`                   // 状态：running/success/failed
	CursorBefore string    `gorm:"column:cursor_before;not null" json:"cursor_before"`                     // 执行前游标
	CursorAfter  string    `gorm:"column:cursor_after;not null" json:"cursor_after"`                       // 执行后游标
	Discovered   int32     `gorm:"column:discovered;not null" json:"discovered"`                           // 发现数
	Extracted    int32     `gorm:"column:extracted;not null" json:"extracted"`                             // 抽取数
	Inserted     int32     `gorm:"column:inserted;not null" json:"inserted"`                               // 入库数
	Skipped      int32     `gorm:"column:skipped;not null" json:"skipped"`                                 // 跳过数
	DurationMs   int32     `gorm:"column:duration_ms;not null" json:"duration_ms"`                         // 耗时（毫秒）
	Error        string    `gorm:"column:error" json:"error"`                                              // 错误信息
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TenderIntelRunSource's table name
func (*TenderIntelRunSource) TableName() string {
	return TableNameTenderIntelRunSource
}
