// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderRecord = "tender_record"

// TenderRecord mapped from table <tender_record>
type TenderRecord struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProjectID    int64     `gorm:"column:project_id;not null" json:"project_id"`         // 解析项目ID
	TenderTypeID int64     `gorm:"column:tender_type_id;not null" json:"tender_type_id"` // 招标类型
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TenderRecord's table name
func (*TenderRecord) TableName() string {
	return TableNameTenderRecord
}
