// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelCollectSchedule = "tender_intel_collect_schedule"

// TenderIntelCollectSchedule mapped from table <tender_intel_collect_schedule>
type TenderIntelCollectSchedule struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键，固定使用 id=1 的单行配置
	CronExpr  string    `gorm:"column:cron_expr;not null;default:0 0 6 * * *" json:"cron_expr"`         // 秒级 cron 表达式（秒 分 时 日 月 周）
	Enabled   int32     `gorm:"column:enabled;not null;default:1" json:"enabled"`                       // 是否启用自动采集：1=启用 0=停用
	UpdatedBy int64     `gorm:"column:updated_by;not null" json:"updated_by"`                           // 最近一次修改人（系统超管）
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TenderIntelCollectSchedule's table name
func (*TenderIntelCollectSchedule) TableName() string {
	return TableNameTenderIntelCollectSchedule
}
