// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderProject = "tender_project"

// TenderProject mapped from table <tender_project>
type TenderProject struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`                              // 项目名称（通常取文件名称或业务名称）
	TenderTypeID   int64     `gorm:"column:tender_type_id;not null" json:"tender_type_id"`          // 项目类型（关联招标类型ID）
	Status         string    `gorm:"column:status;not null;default:running" json:"status"`          // 解析状态：running/succeed/failed
	Progress       int32     `gorm:"column:progress;not null" json:"progress"`                      // 解析进度：0-100
	Stage          string    `gorm:"column:stage;not null" json:"stage"`                            // 当前执行阶段
	LastError      string    `gorm:"column:last_error" json:"last_error"`                           // 最近一次错误信息
	FileName       string    `gorm:"column:file_name" json:"file_name"`                             // 原始文件名
	FileBucket     string    `gorm:"column:file_bucket" json:"file_bucket"`                         // 文件存储桶
	FileObject     string    `gorm:"column:file_object" json:"file_object"`                         // 文件对象键
	SummaryJSON    string    `gorm:"column:summary_json" json:"summary_json"`                       // 智能摘要JSON结果
	FileURL        string    `gorm:"column:file_url" json:"file_url"`                               // 文件访问URL
	UserID         int64     `gorm:"column:user_id" json:"user_id"`                                 // 上传用户ID
	UserTeamID     int32     `gorm:"column:user_team_id" json:"user_team_id"`                       // 项目所属团队ID，即创建人所属团队ID
	UserCompanyID  int32     `gorm:"column:user_company_id" json:"user_company_id"`                 // 项目所属公司ID，即创建人所属公司ID
	IsFinalConfirm bool      `gorm:"column:is_final_confirm;not null" json:"is_final_confirm"`      // 标识终审,1表示已终审，0未终审
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"` // 上传时间
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	BidFormat      string    `gorm:"column:bid_format" json:"bid_format"` // 投标文件格式（AI提取/生成的目录结构+格式要求JSON）
}

// TableName TenderProject's table name
func (*TenderProject) TableName() string {
	return TableNameTenderProject
}
