// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelSource = "tender_intel_source"

// TenderIntelSource mapped from table <tender_intel_source>
type TenderIntelSource struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	SourceKey           string    `gorm:"column:source_key;not null" json:"source_key"`                           // 源唯一标识，与采集服务 recipe 对应
	Name                string    `gorm:"column:name;not null" json:"name"`                                       // 源名称
	HomepageURL         string    `gorm:"column:homepage_url;not null" json:"homepage_url"`                       // 门户地址
	ListURL             string    `gorm:"column:list_url;not null" json:"list_url"`                               // 列表页地址（覆盖 recipe 默认值）
	Category            string    `gorm:"column:category;not null" json:"category"`                               // 网站性质：国家级/地方级/国央企/银行/高校等
	Region              string    `gorm:"column:region;not null" json:"region"`                                   // 地区
	IndustryHint        string    `gorm:"column:industry_hint;not null" json:"industry_hint"`                     // 网站行业属性提示
	DiscoveryMode       string    `gorm:"column:discovery_mode;not null;default:list" json:"discovery_mode"`      // 发现方式：api/list/browser
	NeedsBrowser        int32     `gorm:"column:needs_browser;not null" json:"needs_browser"`                     // 是否需要无头浏览器：1=需要
	Enabled             int32     `gorm:"column:enabled;not null;default:1" json:"enabled"`                       // 是否启用：1=启用 0=停用
	Priority            int32     `gorm:"column:priority;not null;default:100" json:"priority"`                   // 执行优先级，升序
	Params              string    `gorm:"column:params" json:"params"`                                            // 参数覆盖（JSON）
	Cursor              string    `gorm:"column:cursor;not null" json:"cursor"`                                   // 增量游标
	LastRunAt           time.Time `gorm:"column:last_run_at" json:"last_run_at"`                                  // 最近一次执行时间
	LastSuccessAt       time.Time `gorm:"column:last_success_at" json:"last_success_at"`                          // 最近一次成功时间
	LastError           string    `gorm:"column:last_error" json:"last_error"`                                    // 最近一次错误
	ConsecutiveFailures int32     `gorm:"column:consecutive_failures;not null" json:"consecutive_failures"`       // 连续失败次数
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt           time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TenderIntelSource's table name
func (*TenderIntelSource) TableName() string {
	return TableNameTenderIntelSource
}
