// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenderIntelCollectRun = "tender_intel_collect_run"

// TenderIntelCollectRun mapped from table <tender_intel_collect_run>
type TenderIntelCollectRun struct {
	ID              int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键
	RunID           string     `gorm:"column:run_id;not null" json:"run_id"`                                   // 批次 ID
	TriggerType     string     `gorm:"column:trigger_type;not null;default:cron" json:"trigger_type"`          // 触发方式：cron/manual
	Status          string     `gorm:"column:status;not null;default:running" json:"status"`                   // 状态：running/success/partial/failed
	StartedAt       time.Time  `gorm:"column:started_at;not null;default:CURRENT_TIMESTAMP" json:"started_at"` // 开始时间
	FinishedAt      *time.Time `gorm:"column:finished_at" json:"finished_at"`                                  // 结束时间
	SourceTotal     int32      `gorm:"column:source_total;not null" json:"source_total"`                       // 本批次源总数
	SourceSuccess   int32      `gorm:"column:source_success;not null" json:"source_success"`                   // 成功源数
	SourceFailed    int32      `gorm:"column:source_failed;not null" json:"source_failed"`                     // 失败源数
	DiscoveredCount int32      `gorm:"column:discovered_count;not null" json:"discovered_count"`               // 发现公告数
	ExtractedCount  int32      `gorm:"column:extracted_count;not null" json:"extracted_count"`                 // 抽取成功数
	InsertedCount   int32      `gorm:"column:inserted_count;not null" json:"inserted_count"`                   // 新增入库数
	DuplicateCount  int32      `gorm:"column:duplicate_count;not null" json:"duplicate_count"`                 // 重复跳过数
	EnrichedCount   int32      `gorm:"column:enriched_count;not null" json:"enriched_count"`                   // 完成打标数
	MatchedCount    int32      `gorm:"column:matched_count;not null" json:"matched_count"`                     // 本轮匹配出的提醒数
	ErrorSummary    string     `gorm:"column:error_summary" json:"error_summary"`                              // 错误摘要
	CreatedAt       time.Time  `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt       time.Time  `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
	Scope           string     `gorm:"column:scope;not null;default:all" json:"scope"`                         // 采集范围：all=全部启用源，single=指定源
	SourceKeys      string     `gorm:"column:source_keys" json:"source_keys"`                                  // 本次采集覆盖的源（JSON 数组）
	RetryOf         string     `gorm:"column:retry_of;not null" json:"retry_of"`                               // 重试来源批次 run_id
}

// TableName TenderIntelCollectRun's table name
func (*TenderIntelCollectRun) TableName() string {
	return TableNameTenderIntelCollectRun
}
