// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UserID        int64  `gorm:"column:user_id;primaryKey;autoIncrement:true" json:"user_id"` // 用户ID
	CompanyID     int32  `gorm:"column:company_id;not null" json:"company_id"`                // 公司ID
	Nickname      string `gorm:"column:nickname;not null" json:"nickname"`                    // 昵称
	Username      string `gorm:"column:username;not null" json:"username"`                    // 用户名
	Mobile        string `gorm:"column:mobile;not null" json:"mobile"`                        // 手机号
	Status        int32  `gorm:"column:status;not null" json:"status"`                        // 状态, 0:不可用 1:可用
	CreateTime    int64  `gorm:"column:create_time;not null" json:"create_time"`              // 创建时间(unix timestamp)
	UpdateTime    int64  `gorm:"column:update_time;not null" json:"update_time"`              // 更新时间(unix timestamp)
	ViewedVersion string `gorm:"column:viewed_version;not null" json:"viewed_version"`        // 最后一次查看的版本号
	Role          int32  `gorm:"column:role;not null" json:"role"`                            // 角色,0:普通用户 1:系统管理员
	AvatarFile    string `gorm:"column:avatar_file;not null" json:"avatar_file"`              // 用户头像图片的objectKey
	Email         string `gorm:"column:email;not null" json:"email"`                          // 用户邮箱
	Password      string `gorm:"column:password;not null" json:"password"`                    // bcrypt加密密码
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
