// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLlmConfig = "user_llm_config"

// UserLlmConfig mapped from table <user_llm_config>
type UserLlmConfig struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                                // 主键
	UserID              int64  `gorm:"column:user_id;not null" json:"user_id"`                                           // 用户ID
	Module              string `gorm:"column:module;not null;default:all" json:"module"`                                 // 模块: all/bid_analysis/bid_generation/bid_review/material/prediction
	BaseURL             string `gorm:"column:base_url;not null" json:"base_url"`                                         // Base URL
	APIKey              string `gorm:"column:api_key;not null" json:"api_key"`                                           // API Key(明文)
	Model               string `gorm:"column:model;not null" json:"model"`                                               // 模型ID
	EndpointPath        string `gorm:"column:endpoint_path;not null;default:/chat/completions" json:"endpoint_path"`     // /chat/completions 或 /responses
	ContextWindowTokens int32  `gorm:"column:context_window_tokens;not null;default:32768" json:"context_window_tokens"` // 模型上下文窗口Token数
	MaxOutputTokens     int32  `gorm:"column:max_output_tokens;not null;default:8192" json:"max_output_tokens"`          // 单次最大输出Token数
	CreateTime          int64  `gorm:"column:create_time;not null" json:"create_time"`                                   // 创建时间
	UpdateTime          int64  `gorm:"column:update_time;not null" json:"update_time"`                                   // 更新时间
}

// TableName UserLlmConfig's table name
func (*UserLlmConfig) TableName() string {
	return TableNameUserLlmConfig
}
